const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pbl-open-reflections-'));
Object.assign(process.env,{DB_PATH:path.join(dir,'test.db'),UPLOAD_PATH:path.join(dir,'uploads'),NODE_ENV:'test',JWT_SECRET:'isolated-open-reflection-secret',LOGIN_RATE_LIMIT_IP:'1000'});
const app=require('../app'),db=require('../config/database'),{validateReflection}=require('../helpers/reflectionContent');let server,base;const tokens={};
async function api(role,url,method='GET',body){const r=await fetch(base+'/api'+url,{method,headers:{Authorization:'Bearer '+tokens[role],'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return{status:r.status,body:await r.json()};}
before(async()=>{const hash=require('bcryptjs').hashSync('test123',4);for(const[id,role]of [[1,'admin'],[2,'academic_mentor'],[3,'student'],[4,'teacher'],[5,'academic_mentor'],[6,'media'],[7,'teacher'],[8,'student']])db.prepare('INSERT INTO users(id,username,password_hash,real_name,role) VALUES(?,?,?,?,?)').run(id,'u'+id,hash,'隔离账号'+id,role);db.prepare('UPDATE users SET teacher_id=4 WHERE id=3').run();db.exec("INSERT INTO courses(id,title,grade_level,difficulty,status,created_by) VALUES(1,'隔离开放反思','junior','basic','published',2),(2,'其他导师课程','junior','basic','published',5);INSERT INTO lessons(id,course_id,title,status) VALUES(1,1,'隔离课时','scheduled'),(2,2,'其他课时','scheduled'),(3,1,'已取消','cancelled');INSERT INTO enrollments(id,student_id,course_id,status) VALUES(1,3,1,'active');INSERT INTO reflections(id,student_id,enrollment_id,lesson_id,difficulty,solution,improvement,new_question,created_at) VALUES(1,3,1,1,'旧困难','旧解决','旧改进','旧第四项？','2020-01-01');");await new Promise(r=>server=app.listen(0,r));base='http://127.0.0.1:'+server.address().port;for(const role of[1,2,3,4,5,6,7,8])tokens[role]=(await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'u'+role,password:'test123'})}).then(r=>r.json())).token;});
after(async()=>{await new Promise(r=>server.close(r));db.close();});
const payload={enrollment_id:1,lesson_id:1,reflection_version:2};
test('反思模型：三个框任选一项，全部空、类型、混合版本与长度拒绝',()=>{for(const key of ['entry_note','together_note','extra_note'])assert.equal(validateReflection({reflection_version:2,[key]:' 一点想法。 '})[key],' 一点想法。 ');for(const value of[{reflection_version:2,entry_note:' '},{reflection_version:2,entry_note:42},{reflection_version:2,entry_note:'x',difficulty:{}},{reflection_version:2,entry_note:'x',new_question:'旧第四项'},{reflection_version:3,entry_note:'x'},{reflection_version:2,entry_note:'a'.repeat(2001)}])assert.throws(()=>validateReflection(value),e=>e.status===400);assert.equal(validateReflection({new_question:'只写旧第四项'}).new_question,'只写旧第四项');});
test('独立反思三个框分别真实保存，日限失败不新增；原文及旧四项保持',async()=>{for(const field of ['entry_note','together_note','extra_note']){db.prepare("UPDATE reflections SET created_at='2020-01-01' WHERE id>1").run();const r=await api(3,'/archives/reflection','POST',{...payload,[field]:'隔离原文。'});assert.equal(r.status,200);const row=db.prepare('SELECT * FROM reflections ORDER BY id DESC LIMIT 1').get();assert.equal(row[field],'隔离原文。');assert.equal(row.reflection_version,2);assert.equal(row.difficulty,null);assert.equal((await api(3,'/archives/reflection','POST',{...payload,entry_note:'次数失败保留'})).status,400);}const old=db.prepare('SELECT * FROM reflections WHERE id=1').get();assert.equal(old.reflection_version,1);assert.deepEqual([old.difficulty,old.solution,old.improvement,old.new_question],['旧困难','旧解决','旧改进','旧第四项？']);});
test('日志与报告的授权老师正确读取新旧结构，无关角色及同学拒绝',async()=>{for(const role of [1,2,4]){const r=await api(role,'/archives/generate?student_id=3');assert.equal(r.status,200);assert.ok(r.body.reflections.some(x=>x.new_question==='旧第四项？'));assert.ok(r.body.reflections.some(x=>x.extra_note==='隔离原文。'));}for(const role of[5,6,7])assert.ok([400,403].includes((await api(role,'/archives/generate?student_id=3')).status));const own=await api(8,'/archives/generate?student_id=3');assert.ok(own.body.reflections.every(x=>x.student_id===8));for(const role of[1,2,4,5,6,7,8])assert.equal((await api(role,'/archives/reflection','POST',payload)).status,role===8?400:403);});
test('旧端点实际核验发布、有效报名、归属、取消与账号，拒绝不新增',async()=>{const count=db.prepare('SELECT count(*) n FROM reflections').get().n;for(const value of[{...payload,entry_note:' ',extra_note:' '},{...payload,enrollment_id:999,entry_note:'不应保存'},{...payload,lesson_id:2,entry_note:'跨课不保存'},{...payload,lesson_id:3,entry_note:'取消课不保存'}])assert.equal((await api(3,'/archives/reflection','POST',value)).status,400);for(const change of["UPDATE courses SET status='draft' WHERE id=1","UPDATE enrollments SET status='removed' WHERE id=1"]){db.exec(change);assert.equal((await api(3,'/archives/reflection','POST',{...payload,entry_note:'不应保存'})).status,400);db.exec("UPDATE courses SET status='published' WHERE id=1;UPDATE enrollments SET status='active' WHERE id=1");}db.exec('UPDATE users SET force_reset_password=1 WHERE id=3');assert.equal((await api(3,'/archives/reflection','POST',{...payload,entry_note:'不应保存'})).status,403);db.exec('UPDATE users SET force_reset_password=0,is_active=0 WHERE id=3');assert.equal((await api(3,'/archives/reflection','POST',{...payload,entry_note:'不应保存'})).status,401);db.exec('UPDATE users SET is_active=1 WHERE id=3');assert.equal(db.prepare('SELECT count(*) n FROM reflections').get().n,count);});
test('报告附带反思任选一项，报告总结门槛、版本、评审与日志包含次数不变',async()=>{db.exec("UPDATE reflections SET created_at='2020-01-01' WHERE id>1");assert.equal((await api(3,'/learning/lessons/1/report','POST',{report:{summary:'隔离总结'},reflection:{reflection_version:2,extra_note:'报告感受。'}})).status,409);assert.equal((await api(3,'/learning/lessons/1/review-complete','POST',{})).status,200);db.exec("INSERT INTO knowledge_cards(id,lesson_id,title,content,status,created_by) VALUES(1,1,'隔离卡片','隔离正文','published',2)");assert.equal((await api(3,'/learning/cards/1/complete','POST',{})).status,200);for(const body of[{report:{summary:''},reflection:{reflection_version:2,entry_note:'有反思'}},{report:{summary:'有总结'},reflection:{reflection_version:2,extra_note:' '}}])assert.equal((await api(3,'/learning/lessons/1/report','POST',body)).status,400);const r=await api(3,'/learning/lessons/1/report','POST',{report:{summary:'隔离总结'},reflection:{reflection_version:2,extra_note:'报告感受。'}});assert.equal(r.status,201);const reflection=db.prepare('SELECT * FROM reflections WHERE report_id=?').get(r.body.report.id);assert.equal(reflection.extra_note,'报告感受。');assert.equal(reflection.reflection_version,2);assert.equal((await api(3,'/archives/reflection','POST',{...payload,entry_note:'次数失败'})).status,400);const detail=await api(2,'/mentor-reviews/'+r.body.report.id);assert.equal(detail.body.reflection.extra_note,'报告感受。');assert.equal((await api(4,'/mentor-reviews/'+r.body.report.id+'/review','POST',{status:'approved',score:80})).status,403);});
