const router=require('express').Router(),s=require('../services/studentRewards');
const {requireAuth,requirePasswordChanged,requireRole}=require('../middleware/auth');
router.use(requireAuth,requirePasswordChanged,requireRole('student'),(req,res,next)=>{res.setHeader('Cache-Control','no-store');if(Object.keys(req.query).length)return res.status(400).json({error:'奖励仅操作当前账号'});next();});
const action=fn=>(req,res,next)=>{try{res.json(fn(req));}catch(e){if(e.status)return res.status(e.status).json({error:e.message});next(e);}};
router.get('/day',action(()=>{const now=new Date(),date=now.toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});return {date,validForMs:Date.parse(date+'T00:00:00+08:00')+86400000-now.getTime()};}));
router.get('/badges',action(req=>s.profile(req.user.id)));
router.get('/lessons/:lessonId',action(req=>s.eligibility(req.user.id,req.params.lessonId)));
router.post('/badges/reconcile',action(req=>{s.fields(req.body,[]);return s.reconcile(req.user.id);}));
router.post('/badges/present',action(req=>s.present(req.user.id,req.body)));
router.get('/exchanges',action(req=>({events:s.exchanges(req.user.id),demo:true})));
router.post('/exchanges',action(req=>s.exchange(req.user.id,req.body)));
module.exports=router;
