import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {mapSegments} from '../src/student/mapGeometry.js';
import {applyPageEdits,mergePayloads} from '../../scripts/copy-validation.mjs';
import {readCopy} from '../../scripts/fortune-copy.mjs';
const copy={...readCopy(new URL('../src/content/uiCopy.jsx',import.meta.url)),...JSON.parse(fs.readFileSync(new URL('../src/content/systemCopy.js',import.meta.url),'utf8').split('export const systemCopy = ')[1].trim().replace(/;$/,''))};
const payload=(id,text,extra={})=>({format:'page-copy-review-v1',edits:[{id,text,enabled:true,baseText:copy[id].text,baseEnabled:copy[id].enabled,...extra}]});
test('地图九段仅连接真实顺序，相邻换行固定外侧并保留错落',()=>{
 const nodes=Array.from({length:10},(_,i)=>{const row=Math.floor(i/3),col=row%2?2-i%3:i%3,left=40+col*260,top=row*280+(i%3===1?-16:0);return{id:i+1,row,left,right:left+200,width:200,top,bottom:top+210,padY:top+150};});
 const result=mapSegments(nodes,{width:840});assert.equal(result.length,9);assert.deepEqual(result.map(s=>[s.from,s.to]),nodes.slice(1).map((n,i)=>[nodes[i].id,n.id]));assert.equal(result[2].kind,'turn-right');assert.equal(result[5].kind,'turn-left');assert.equal(result[8].kind,'turn-right');assert.equal(result[0].start.x,249);assert.equal(result[0].end.x,291);
});
test('窄屏采用垂直间隙，连线不穿按钮范围',()=>{const nodes=[0,1,2].map(i=>({id:i,row:i,left:80,right:280,width:200,top:i*260,bottom:i*260+210,padY:i*260+150}));const result=mapSegments(nodes,{width:360,narrow:true});for(const [i,s]of result.entries()){assert.equal(s.kind,'vertical');assert.ok(s.start.y>nodes[i].bottom);assert.ok(s.end.y<nodes[i+1].top);}});
test('改稿只应用变化项，脚本文字原样保存，不执行表达式',()=>{const id='fortune.good.ask',text='<script>globalThis.bad=true</script>';const {next}=applyPageEdits(copy,payload(id,text));assert.equal(next[id].text,text);assert.equal(globalThis.bad,undefined);assert.deepEqual(next['system.tasks.030'],copy['system.tasks.030']);});
test('旧副本、未知范围、重复ID、模板占位符丢失均拒绝',()=>{const id='fortune.good.ask';assert.throws(()=>applyPageEdits(copy,payload(id,'x',{baseText:'old'})),/基线冲突/);const p=payload(id,'x');p.edits.push(p.edits[0]);assert.throws(()=>applyPageEdits(copy,p),/重复/);assert.throws(()=>applyPageEdits(copy,payload(id,'x',{id:'other'})),/非法/);const template=Object.keys(copy).find(k=>copy[k].text.includes('{slot0}'));assert.throws(()=>applyPageEdits(copy,payload(template,'丢失动态值')),/占位符/);});
test('必要状态不能清空，仅隔离该条，辅助文字可隐藏且不回补',()=>{const required='fortune.failed',optional=Object.keys(copy).find(k=>copy[k].optional);const p=mergePayloads([payload(required,''),payload(optional,'',{enabled:false})]);const {next,issues}=applyPageEdits(copy,p);assert.equal(issues.length,1);assert.equal(next[required].text,copy[required].text);assert.equal(next[optional].enabled,false);assert.equal(next[optional].text,'');});
test('公共ID多文件冲突明确拒绝，相同改稿只应用一次',()=>{const p=payload('fortune.good.ask','test');assert.equal(mergePayloads([p,p]).edits.length,1);assert.throws(()=>mergePayloads([p,payload('fortune.good.ask','other')]),/公共 ID 冲突/);});
test('60条线上候选可审阅，实际文字不重名；关闭/重复候选不能伪造每天变化',()=>{for(const prefix of['fortune.good.','fortune.avoid.']){const entries=Object.entries(copy).filter(([id])=>id.startsWith(prefix));assert.equal(entries.length,30);assert.equal(new Set(entries.map(([,e])=>e.text.trim())).size,30);}assert.throws(()=>applyPageEdits(copy,payload('fortune.good.ask',Object.entries(copy).find(([id])=>id.startsWith('fortune.good.')&&id!=='fortune.good.ask')[1].text)),/显示重复/);assert.equal(applyPageEdits(copy,payload('fortune.good.ask','',{enabled:false})).issues.length,1);});
