import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';import {chromium} from 'playwright';import {readReviewHtml,applyPageEdits} from '../scripts/page-copy.mjs';import {readCopy} from '../scripts/fortune-copy.mjs';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'docs/badge-room/step-01/copy-browser'),directory=path.join(root,'docs/badge-room/step-01/copy-review'),coverage=JSON.parse(fs.readFileSync(path.join(directory,'coverage.json'))),copy=readCopy(path.join(root,'frontend/src/content/uiCopy.jsx'));fs.mkdirSync(out,{recursive:true});
test('四份增量审阅可双击打开，稳定ID与当前基线一致，原46份仍保留',{timeout:60000},async()=>{
 const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();try{for(const page of coverage.pages){await p.goto('file:///'+path.join(directory,page.title+'.html').replaceAll('\\','/'));assert.equal(await p.locator('[data-copy-id]').count(),page.ids.length);assert.deepEqual(readReviewHtml(path.join(directory,page.title+'.html')).edits,[]);}const old=JSON.parse(fs.readFileSync(path.join(root,'docs/experience-patch/copy-review/coverage.json')));assert.equal(old.pages.length,46);for(const page of old.pages)assert.ok(fs.existsSync(path.join(root,'docs/experience-patch/copy-review',page.html)));await p.goto('file:///'+path.join(directory,'index.html').replaceAll('\\','/'));await p.screenshot({path:path.join(out,'increment-directory.png')});}finally{await b.close();}
});
test('新文案点字、保存重开与变化项导出；脚本文字为纯文本，导入只改受控ID',{timeout:60000},async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pbl-badge-copy-')),b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();try{await p.goto('file:///'+path.join(directory,'徽章陈列室.html').replaceAll('\\','/'));const text='<script>window.badgeRoomInjected=true</script>';await p.locator('[data-copy-id="badgeRoom.title"]').fill(text);let download=p.waitForEvent('download');await p.locator('#export').click();const json=path.join(temp,'edit.json');await(await download).saveAs(json);const payload=JSON.parse(fs.readFileSync(json));assert.deepEqual(payload.edits.map(e=>e.id),['badgeRoom.title']);const next=applyPageEdits(copy,payload).next;assert.equal(next['badgeRoom.title'].text,text);assert.deepEqual(next['fortune.avoid.compare'],copy['fortune.avoid.compare']);download=p.waitForEvent('download');await p.locator('#save').click();const html=path.join(temp,'edit.html');await(await download).saveAs(html);await p.goto('file:///'+html.replaceAll('\\','/'));assert.equal(await p.locator('[data-copy-id="badgeRoom.title"]').innerText(),text);assert.equal(await p.evaluate(()=>window.badgeRoomInjected),undefined);assert.equal(readReviewHtml(html).edits[0].text,text);await p.screenshot({path:path.join(out,'edited-copy.png')});}finally{await b.close();}
});
test('旧反馈字段改稿发生基线冲突时不覆盖迁移，其他人工文案和运势词库保持',()=>{
 const delta=JSON.parse(fs.readFileSync(path.join(root,'docs/badge-room/step-01/copy-delta.json')));assert.equal(delta.changed.length,2);const changed=delta.changed[0];assert.throws(()=>applyPageEdits(copy,{format:'page-copy-review-v1',edits:[{id:changed.id,baseText:changed.before,baseEnabled:true,text:'来自旧副本的改稿',enabled:true}]}),/基线冲突/);assert.equal(copy[changed.id].text,changed.after);assert.equal(copy['fortune.avoid.compare'].text,'和别人比分数');assert.equal(copy['fortune.avoid.argument'].text,'和别人拌嘴');const previous=JSON.parse(execFileSync('git',['show','6a4d7dd:frontend/src/content/uiCopy.jsx'],{cwd:root,encoding:'utf8'}).split('export const uiCopy = ')[1].trim().replace(/;$/,''));assert.deepEqual(copy['fortune.boundary'],previous['fortune.boundary']);
});
