import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {createRequire} from 'node:module';import {chromium} from 'playwright';
import {fixture,root,Database} from './v2-fixture.mjs';import {prepareSkeleton} from '../scripts/teaching.mjs';import {readReviewHtml,applyPageEdits} from '../scripts/page-copy.mjs';import {readCopy} from '../scripts/fortune-copy.mjs';
const out=path.join(root,'docs/experience-patch/copy-browser-'+(process.env.PBL_COPY_RUN||'first')),base='http://127.0.0.1:4208';fs.mkdirSync(out,{recursive:true});
const ready=async url=>{for(let i=0;i<150;i++){try{if((await fetch(url)).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('not ready '+url);};
test('逐页文案 HTML、安全改稿与真实管理员审阅授权',{timeout:240000},async t=>{
 const f=fixture(3178,4208),db=new Database(f.env.DB_PATH),plan=prepareSkeleton(db),records=[],errors=[];const bcrypt=createRequire(path.join(root,'backend/package.json'))('bcryptjs');db.prepare("INSERT INTO users(username,password_hash,real_name,role) VALUES('copy_media',?,'隔离新媒体','media')").run(bcrypt.hashSync('media123',4));
 const server=spawn(process.execPath,['app.js'],{cwd:path.join(root,'backend'),env:f.env,stdio:'ignore',windowsHide:true});await ready('http://127.0.0.1:3178/api/health');const vite=spawn(process.execPath,[path.join(root,'frontend/node_modules/vite/bin/vite.js'),'preview','--host','127.0.0.1','--port','4208','--strictPort','--outDir',path.join(root,'build/teaching')],{cwd:path.join(root,'frontend'),env:f.env,stdio:'ignore',windowsHide:true});await ready(base);
 const browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({viewport:{width:1440,height:900}});p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));
 const login=async(name,password)=>{await p.goto(base+'/login');await p.getByLabel('账号',{exact:true}).fill(name);await p.getByLabel('密码',{exact:true}).fill(password);await p.getByRole('button',{name:'登录',exact:true}).click();await p.waitForURL(u=>u.pathname!='/login');};
 const scene=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();records.push({name,status:'passed'});}catch(e){failure=e;records.push({name,status:'failed',error:e.message});await p.screenshot({path:path.join(out,'failure-'+records.length+'.png')});throw e;}});if(failure)throw failure;};
 try{
  await scene('46份实际页面文件可双击打开，基线与字段一致，均带角色、路由、区域和来源',async()=>{
   const coverage=JSON.parse(fs.readFileSync(path.join(root,'docs/experience-patch/copy-review/coverage.json'))),html=await browser.newPage();
   for(const page of coverage.pages){const file=path.join(root,'docs/experience-patch/copy-review',page.html);await html.goto('file:///'+file.replaceAll('\\','/'));assert.equal(await html.locator('[data-copy-id]').count(),page.editableIds.length);assert.ok(page.editableIds.length>0);assert.equal(new Set(page.editableIds).size,page.editableIds.length);const result=readReviewHtml(file);assert.deepEqual(result.edits,[]);assert.equal(result.baseline.length,page.editableIds.length);}
   await html.close();
  });
  await scene('HTML改稿保存重开、纯文本脚本不执行、变化项导出与基线冲突拒绝',async()=>{
   const html=await browser.newPage(),file=path.join(root,'docs/experience-patch/copy-review/今日运势全部词库.html');await html.goto('file:///'+file.replaceAll('\\','/'));const value='<script>window.__copyExecuted=true</script>学习建议';await html.locator('[data-copy-id="fortune.good.ask"]').fill(value);let pending=html.waitForEvent('download');await html.locator('#save').click();const edited=path.join(f.scratch,'edited.html');await(await pending).saveAs(edited);await html.goto('file:///'+edited.replaceAll('\\','/'));assert.equal(await html.locator('[data-copy-id="fortune.good.ask"]').innerText(),value);assert.equal(await html.evaluate(()=>window.__copyExecuted),undefined);const result=readReviewHtml(edited);assert.equal(result.edits.length,1);assert.equal(result.edits[0].text,value);const copy=readCopy(path.join(root,'frontend/src/content/uiCopy.jsx'));assert.equal(applyPageEdits(copy,{format:'fortune-review-v1',edits:result.edits}).next['fortune.good.ask'].text,value);copy['fortune.good.ask'].text='不同新基线';assert.throws(()=>applyPageEdits(copy,{format:'page-copy-review-v1',edits:result.edits}),/基线冲突/);await html.close();
  });
  await login('adminpbl','admin123');
  await scene('管理员真实页面点字审阅、导出只含一处变化，不写教学数据',async()=>{
   const before=db.prepare('SELECT * FROM courses ORDER BY id').all();await p.goto(base+'/courses');await p.getByRole('heading',{name:'课程管理',exact:true}).waitFor();await p.getByRole('button',{name:'文案审阅',exact:true}).click();await p.getByRole('heading',{name:'课程管理',exact:true}).click();const modal=p.locator('.ant-modal').filter({visible:true});await modal.getByLabel('改稿文字').fill('管理员改稿测试');await modal.getByRole('button',{name:'保留在本次改稿',exact:true}).click();const pending=p.waitForEvent('download');await p.getByRole('button',{name:/导出\s*1\s*处改稿/}).click();const output=path.join(f.scratch,'admin-copy.json');await(await pending).saveAs(output);const edits=JSON.parse(fs.readFileSync(output)).edits;assert.equal(edits.length,1);assert.equal(edits[0].baseText,'课程管理');assert.equal(edits[0].text,'管理员改稿测试');assert.deepEqual(db.prepare('SELECT * FROM courses ORDER BY id').all(),before);await p.screenshot({path:path.join(out,'admin-inspector.png')});
  });
  await scene('管理员目录点字编辑、本账号草稿恢复，旧基线和存储失败明确拒绝',async()=>{
   await p.goto(base+'/copy-review');await p.getByRole('heading',{name:'系统文案审阅',exact:true}).waitFor();await p.getByLabel('查找文案',{exact:true}).fill('fortune.good.ask');const field=p.locator('[data-copy-id="fortune.good.ask"]');await field.fill('目录保存测试');await p.getByRole('button',{name:'保存浏览器草稿',exact:true}).click();await p.reload();await p.getByRole('button',{name:'恢复草稿',exact:true}).click();await p.getByLabel('查找文案',{exact:true}).fill('fortune.good.ask');assert.equal(await p.locator('[data-copy-id="fortune.good.ask"]').innerText(),'目录保存测试');
   await p.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.startsWith('pbl-copy-review:')),v=JSON.parse(localStorage.getItem(key));v.edits[0].baseText='过期原稿';localStorage.setItem(key,JSON.stringify(v));});await p.getByRole('button',{name:'恢复草稿',exact:true}).click();await p.getByRole('status').filter({hasText:'草稿无效或存储不可用'}).waitFor();await p.screenshot({path:path.join(out,'admin-copy-directory.png')});
  });
  await scene('学生、只读教师、新媒体、执行导师不能进入系统编辑；负责导师保留真实教学维护',async()=>{
   for(const [username,password]of[['student_wang','student123'],['teacher_li','teacher123'],['copy_media','media123'],['mentor_zhang','mentor123']]){await login(username,password);await p.goto(base+'/copy-review');assert.equal(await p.locator('.copy-review').count(),0);assert.equal(await p.getByRole('button',{name:'文案审阅',exact:true}).count(),0);await p.getByText(/无权访问|无权限|工作范围|无法访问|没有权限/).first().waitFor();}
   await p.goto(base+`/courses/${plan.courseId}?tab=maintenance`);await p.getByRole('tab',{name:'可视化填写 / 学生效果预览',exact:true}).click();await p.getByTestId('teaching-preview').waitFor();assert.equal(await p.getByRole('button',{name:'文案审阅',exact:true}).count(),0);await p.screenshot({path:path.join(out,'mentor-teaching-review.png')});
  });
  assert.deepEqual(errors,[]);
 }finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({records,pageErrors:errors,browser:browser.version(),scope:'Fresh synthetic DB; production teaching build; HTML parsed as data; actual .local/teaching untouched'},null,2));await browser.close();db.close();vite.kill();server.kill();}
});
