import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {chromium} from 'playwright';import {fixture,root,Database} from './v2-fixture.mjs';import {prepareSkeleton} from '../scripts/teaching.mjs';
const phase=process.env.PBL_BADGE_PHASE||'final',out=path.join(root,'docs/lesson-authoring/regression/badges',phase),base='http://127.0.0.1:4227',api='http://127.0.0.1:3197';
const ready=async url=>{for(let i=0;i<120;i++){try{if((await fetch(url)).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Not ready '+url);};
test('徽章陈列室与小智交互',{timeout:240000},async t=>{
 fs.mkdirSync(out,{recursive:true});const f=fixture(3197,4227),db=new Database(f.env.DB_PATH),plan=prepareSkeleton(db),[visit,theory,experiment]=plan.lessonIds,records=[],errors=[];
 db.prepare("UPDATE ai_settings SET enabled=1").run();db.prepare("UPDATE lessons SET content_state='ready' WHERE id=?").run(theory);
 const card=Number(db.prepare("INSERT INTO knowledge_cards(lesson_id,title,content,status,created_by) VALUES(?,'陈列室隔离卡片','非正式教学内容','published',2)").run(theory).lastInsertRowid);
 db.prepare('INSERT INTO lesson_review_completions(student_id,lesson_id) VALUES(4,?)').run(theory);db.prepare('INSERT INTO student_card_progress(student_id,card_id,completed_at) VALUES(4,?,CURRENT_TIMESTAMP)').run(card);db.prepare("INSERT INTO lesson_learning_reports(student_id,lesson_id,summary,status) VALUES(4,?,'隔离陈列室报告','submitted')").run(theory);
 db.prepare("INSERT INTO enrollments(student_id,course_id,status) VALUES(5,?,'active')").run(plan.courseId);
 const backend=spawn(process.execPath,['scripts/local-server.cjs'],{cwd:root,env:f.env,windowsHide:true,stdio:'ignore'});await ready(api+'/api/health');
 const server=await import('node:http');const dist=path.join(root,'build/teaching');const front=server.createServer((req,res)=>{const pathname=new URL(req.url,base).pathname;if(pathname.startsWith('/api/')){const upstream=server.request(api+req.url,{method:req.method,headers:req.headers},r=>{res.writeHead(r.statusCode,r.headers);r.pipe(res);});upstream.on('error',()=>{res.writeHead(502);res.end();});req.pipe(upstream);return;}const candidate=path.resolve(dist,'.'+pathname);const file=candidate.startsWith(dist+path.sep)&&fs.existsSync(candidate)&&fs.statSync(candidate).isFile()?candidate:path.join(dist,'index.html');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});await new Promise(r=>front.listen(4227,'127.0.0.1',r));
 const browser=await chromium.launch({channel:'msedge',headless:true}),contexts=[],context=await browser.newContext({viewport:{width:1440,height:900}});contexts.push(context);const p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));
 const login=async(page,user='student_wang',password='student123')=>{await page.goto(base+'/login');await page.getByLabel('账号',{exact:true}).fill(user);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.waitForURL(u=>u.pathname!='/login');};
 const go=async url=>{await p.goto(base+url);};const room=async()=>{await go('/me/badges');await p.locator('[data-locked-lesson],[data-real-grant],.badge-room-empty').first().waitFor();};const dialog=()=>p.locator('.badge-room-modal .ant-modal-container');
 const shot=async(name,page=p)=>{await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,name+'.png'),animations:'disabled'});};
 const hit=async page=>page.locator('.course-robot').evaluate(el=>{const r=el.getBoundingClientRect(),e=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{reachable:e===el||el.contains(e),coveredByChat:!!e?.closest('#course-chat'),x:r.x,y:r.y,w:r.width,h:r.height};});
 const scene=async(name,fn)=>{if(process.env.PBL_BADGE_SCENE&&!name.includes(process.env.PBL_BADGE_SCENE))return;let failure;await t.test(name,async()=>{try{await fn();records.push({name,status:'passed'});}catch(e){failure=e;records.push({name,status:'failed',error:e.message});await shot('failure-'+records.length).catch(()=>{});throw e;}});if(failure)throw failure;};
 try{
 await login(p);await go('/courses/'+plan.courseId);
 await scene('原生鼠标首次打开，触发器不被聊天框遮挡；再次点击可靠收起',async()=>{
  await p.locator('.course-robot').click();await p.locator('#course-chat').waitFor({state:'visible'});const result=await hit(p);fs.writeFileSync(path.join(out,'trigger-hit.json'),JSON.stringify(result,null,2));await shot('robot-first-open');assert.equal(result.reachable,true);assert.equal(result.coveredByChat,false);await p.locator('.course-robot').click();await p.locator('#course-chat').waitFor({state:'hidden'});
 });
 if(phase==='before')return;
 await scene('鼠标拖动不打开、下一次点击打开；固定视口、输入与选择不误收起、空白关闭及键盘',async()=>{
  const robot=p.locator('.course-robot'),b=await robot.boundingBox();await p.mouse.move(b.x+30,b.y+30);await p.mouse.down();await p.mouse.move(500,330,{steps:8});await p.mouse.up();assert.equal(await p.locator('#course-chat').isVisible(),false);const pos=await robot.boundingBox();await p.evaluate(()=>scrollTo(0,600));assert.equal((await robot.boundingBox()).y,pos.y);await robot.click();await p.locator('#assistant-question').fill('隔离测试：保留自己的问题，不发送');await p.locator('#assistant-question').press('Control+A');assert.equal(await p.locator('#course-chat').isVisible(),true);await p.locator('#course-chat h2').click();assert.equal(await p.locator('#course-chat').isVisible(),true);await p.mouse.click(230,200);await p.locator('#course-chat').waitFor({state:'hidden'});await robot.focus();await p.keyboard.press('Enter');await p.locator('#course-chat').waitFor({state:'visible'});await p.keyboard.press('Escape');await robot.focus();await p.keyboard.press('Space');await p.locator('#course-chat').waitFor({state:'visible'});await p.keyboard.press('Escape');await robot.focus();await p.keyboard.press('Home');
 });
 await scene('原生模拟触屏轻触只开一次、拖动后轻触、取消拖动后下一次轻触',async()=>{
  const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});contexts.push(c);const q=await c.newPage();q.setDefaultTimeout(8000);await q.addInitScript(()=>{window.badgeRoomPointerEvents=[];for(const type of ['pointerdown','pointerup','pointercancel','lostpointercapture','click'])document.addEventListener(type,e=>{if(e.target.closest('.course-robot'))window.badgeRoomPointerEvents.push({type,pointerType:e.pointerType,detail:e.detail,time:e.timeStamp});},true);});await login(q);await q.goto(base+'/courses/'+plan.courseId);const robot=q.locator('.course-robot');await robot.tap();await q.locator('#course-chat').waitFor({state:'visible'});assert.equal((await hit(q)).reachable,true);await robot.tap();await q.locator('#course-chat').waitFor({state:'hidden'});const session=await c.newCDPSession(q);
  const touch=async(type,x,y)=>session.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y,id:1}]});let r=await robot.boundingBox();await touch('touchStart',r.x+25,r.y+25);await touch('touchMove',120,310);await touch('touchEnd');assert.equal(await q.locator('#course-chat').isVisible(),false);await robot.tap();await q.locator('#course-chat').waitFor({state:'visible'});await q.getByRole('button',{name:'收起对话'}).click();r=await robot.boundingBox();await touch('touchStart',r.x+25,r.y+25);await touch('touchMove',170,390);await touch('touchCancel');assert.equal(await q.locator('#course-chat').isVisible(),false);await robot.tap();await q.locator('#course-chat').waitFor({state:'visible'});await shot('robot-touch',q);fs.writeFileSync(path.join(out,'touch-events.json'),JSON.stringify(await q.evaluate(()=>window.badgeRoomPointerEvents),null,2));await c.close();
 });
 await scene('五尺寸缩放夹紧、默认机器人不被浮窗覆盖、输入与关闭入口可见',async()=>{
  for(const [width,height]of [[1440,900],[768,1024],[390,844],[360,800],[844,390]]){await p.setViewportSize({width,height});await go('/courses/'+plan.courseId);const robot=p.locator('.course-robot');await robot.focus();await p.keyboard.press('Home');await robot.click();await p.locator('#course-chat').waitFor({state:'visible'});const r=await hit(p);assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=width&&r.y+r.h<=height);assert.equal(r.reachable,true);const chat=await p.locator('#course-chat').boundingBox();assert.ok(chat.y+chat.height<=r.y+1);await shot('robot-'+width+'x'+height);await p.getByRole('button',{name:'收起对话'}).click();await p.locator('#course-chat').waitFor({state:'hidden'});}
 });
 await scene('姓名旁徽章入口与账号头像保留；我的旧陈列及徽章页签移除，课程返回有效',async()=>{
  await p.setViewportSize({width:1440,height:900});const source='/courses/'+plan.courseId;await go('/me?returnTo='+encodeURIComponent(source));assert.equal(await p.locator('.next-badge-shelf,.fortune-boundary').count(),0);assert.equal(await p.getByRole('tab',{name:'徽章',exact:true}).count(),0);assert.equal(await p.locator('[data-gift^="digital-"]').count(),0);await p.locator('.space-personal-name .account-avatar-trigger').click();await p.getByRole('button',{name:'校园银杏',exact:true}).waitFor();await p.keyboard.press('Escape');await p.getByRole('link',{name:'徽章墙',exact:true}).click();await p.waitForURL('**/me/badges?*');assert.equal(await p.locator('[data-course-space]').count(),0);await p.getByRole('link',{name:'返回我的',exact:true}).click();await p.getByRole('link',{name:'返回来源课程 →',exact:true}).click();await p.waitForURL('**/courses/'+plan.courseId);for(const width of [1440,390,360]){await p.setViewportSize({width,height:844});await room();await p.evaluate(()=>scrollTo(0,700));const back=p.getByRole('link',{name:'返回我的',exact:true});assert.equal(await back.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit===el||el.contains(hit);}),true);await back.click();await p.locator('.account-avatar-trigger').waitFor();}await p.setViewportSize({width:1440,height:900});
 });
 await scene('零获得与授权未获得定义，灰度下方稳定顺序，没有虚构后七课',async()=>{
  await room();assert.equal(await p.locator('[data-real-grant]').count(),0);const buttons=p.locator('[data-locked-lesson]');assert.equal(await buttons.count(),3);assert.match(await p.getByText('还没有获得课时徽章。',{exact:false}).innerText(),/全部学习任务/);const ids=await buttons.evaluateAll(bs=>bs.map(b=>b.dataset.lockedLesson));assert.deepEqual(ids,[visit,theory,experiment].map(String));assert.match(await buttons.first().locator('.badge-room-medallion').evaluate(e=>getComputedStyle(e).filter),/grayscale/);await p.reload();await buttons.first().waitFor();assert.deepEqual(await buttons.evaluateAll(bs=>bs.map(b=>b.dataset.lockedLesson)),ids);await shot('zero-earned');
 });
 await scene('真实原规则满足后授予，去看看定位新徽章；重复读取与另一标签不重复反馈',async()=>{
  db.prepare("UPDATE lesson_learning_reports SET status='approved' WHERE student_id=4 AND lesson_id=?").run(theory);await go('/me');await p.locator('.next-award').waitFor();const grant=await p.locator('.next-award').getAttribute('data-grant-id');await p.getByRole('link',{name:'去徽章墙看看',exact:true}).click();await p.waitForURL('**/me/badges?grant=*');await p.locator('[data-real-grant="'+grant+'"]').waitFor();assert.equal(await p.locator('.badge-room-badge.is-highlighted').getAttribute('data-real-grant'),grant);assert.equal(await p.locator('.badge-room-badge.is-highlighted').evaluate(e=>e===document.activeElement),true);const q=await context.newPage();await q.goto(base+'/me/badges');await q.locator('[data-real-grant]').waitFor();assert.equal(await q.locator('.next-award').count(),0);await q.close();await p.reload();await p.locator('[data-real-grant]').waitFor();assert.equal(await p.locator('.next-award').count(),0);assert.equal(db.prepare('SELECT count(*) n FROM student_badge_grants WHERE student_id=4').get().n,1);
 });
 await scene('五尺寸真实陈列与中央详情，Esc/遮罩关闭、焦点恢复、短屏内部滚动',async()=>{
  for(const [width,height]of [[1440,900],[768,1024],[390,844],[360,800],[844,390]]){await p.setViewportSize({width,height});await room();await shot('room-'+width+'x'+height);const earned=p.locator('[data-real-grant]').first();await earned.focus();await p.keyboard.press('Enter');await dialog().waitFor();await dialog().evaluate(async el=>{await Promise.all(el.closest('.ant-modal-wrap').getAnimations({subtree:true}).filter(a=>a.effect.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});const r=await dialog().boundingBox();fs.writeFileSync(path.join(out,'detail-geometry-'+width+'x'+height+'.json'),JSON.stringify(r));assert.ok(Math.abs((r.x+r.width/2)-width/2)<8);assert.ok(Math.abs((r.y+r.height/2)-height/2)<15);await shot('detail-'+width+'x'+height);if(height<450){const body=p.locator('.badge-room-modal .ant-modal-body');assert.ok(await body.evaluate(e=>e.scrollHeight>e.clientHeight));await body.hover();await p.mouse.wheel(0,300);await p.waitForFunction(()=>document.querySelector('.badge-room-modal .ant-modal-body').scrollTop>0);const close=await p.getByRole('button',{name:'关闭详情',exact:true}).boundingBox();assert.ok(close.y+close.height<=height);await shot('detail-scrolled-'+width+'x'+height);}await p.keyboard.press('Escape');await dialog().waitFor({state:'hidden'});assert.equal(await earned.evaluate(e=>e===document.activeElement),true);const locked=p.locator('[data-locked-lesson]').first();await locked.click();await dialog().waitFor();await dialog().getByText('参观尚无个人完成记录，暂不能判断通关',{exact:true}).waitFor();await p.mouse.click(3,Math.floor(height/2));await dialog().waitFor({state:'hidden'});assert.equal(await locked.evaluate(e=>e===document.activeElement),true);}
 });
 await scene('徽章及场景图片失败仅降级；读取失败移除陈列并可重试，不清空奖励数据',async()=>{
  await p.setViewportSize({width:390,height:844});await p.route('**/assets/badge-room/**',r=>r.fulfill({status:404,body:''}));await p.route('**/assets/next-rewards/**',r=>r.fulfill({status:404,body:''}));await room();await p.locator('.badge-room[data-scene-failed]').waitFor();await p.locator('[data-real-grant] .pixel-image-fallback').waitFor();await p.locator('[data-real-grant]').click();await dialog().waitFor();await p.keyboard.press('Escape');await shot('image-fallback');await p.unroute('**/assets/badge-room/**');await p.unroute('**/assets/next-rewards/**');await p.route('**/api/rewards/badges',r=>r.fulfill({status:503,json:{error:'隔离测试：徽章读取失败'}}));await go('/me/badges');await p.getByText('隔离测试：徽章读取失败',{exact:true}).waitFor();assert.equal(await p.locator('[data-real-grant]').count(),0);await p.unroute('**/api/rewards/badges');await p.locator('.badge-room').getByRole('button',{name:'重新读取',exact:true}).click();await p.locator('[data-real-grant]').waitFor();
 });
 await scene('课程撤回保留安全获章历史，清除未获得项与失效链接；跨账号隔离',async()=>{
  const snapshot=await p.evaluate(async()=>{const r=await fetch('/api/rewards/badges',{headers:{Authorization:'Bearer '+localStorage.getItem('token')}});return r.json();});let first=true,entered,release;const arrived=new Promise(r=>entered=r),held=new Promise(r=>release=r);await p.route('**/api/rewards/badges',async r=>{if(first){first=false;entered();await held;await r.fulfill({json:snapshot});}else await r.continue();});await p.evaluate(()=>window.dispatchEvent(new Event('focus')));await arrived;db.prepare("UPDATE courses SET status='archived' WHERE id=?").run(plan.courseId);await p.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.locator('[data-real-grant]').waitFor();assert.equal(await p.locator('[data-locked-lesson]').count(),0);release();await p.waitForTimeout(200);assert.equal(await p.locator('[data-locked-lesson]').count(),0);await p.unroute('**/api/rewards/badges');await p.locator('[data-real-grant]').waitFor();assert.equal(await p.locator('[data-locked-lesson]').count(),0);await p.locator('[data-real-grant]').click();await dialog().waitFor();assert.equal(await dialog().locator('a[href*="/courses/"]').count(),0);await dialog().getByText(/来源已不可访问/).waitFor();await p.keyboard.press('Escape');const c=await browser.newContext();contexts.push(c);const q=await c.newPage();await login(q,'student_chen');await q.goto(base+'/me/badges');await q.getByText('目前没有可展示的课时徽章。',{exact:false}).waitFor();assert.equal(await q.locator('[data-real-grant],[data-locked-lesson]').count(),0);await c.close();db.prepare("UPDATE courses SET status='published' WHERE id=?").run(plan.courseId);
 });
 await scene('大量徽章自然纵向陈列与全获得状态，数量不混入演示徽章',async()=>{
  for(let i=0;i<24;i++){const id=Number(db.prepare("INSERT INTO lessons(course_id,title,sort_order,content_state) VALUES(?,?,?,'preparing')").run(plan.courseId,'隔离展柜 '+i,100+i).lastInsertRowid);db.prepare("INSERT INTO lesson_badge_definitions(lesson_id,name,art_id,description) VALUES(?,?,'theory','大量展示合成样例')").run(id,'合成陈列徽章 '+i);db.prepare("INSERT INTO student_badge_grants(id,student_id,lesson_id,course_id,name,art_id,description,lesson_title,course_title,criterion_snapshot,shown_at) VALUES(?,4,?,?,?,'theory','合成展示样例','合成课时','合成陈列课程','{}',CURRENT_TIMESTAMP)").run('display-'+i,id,plan.courseId,'合成陈列徽章 '+i);}
  await room();assert.equal(await p.locator('[data-real-grant]').count(),25);assert.equal(await p.locator('#badge-room-earned span').innerText(),'25');await p.locator('[data-real-grant]').last().click();await dialog().waitFor();await p.keyboard.press('Escape');await shot('many-badges');db.prepare('DELETE FROM lesson_badge_definitions WHERE lesson_id IN (?,?)').run(visit,experiment);await p.reload();await p.getByText('目前没有待获得的课时徽章',{exact:true}).waitFor();assert.equal(await p.locator('[data-locked-lesson]').count(),0);
 });
 await scene('非学生深链仍受角色守卫，外部返回地址被拒；未开启新业务',async()=>{
  const c=await browser.newContext();contexts.push(c);const q=await c.newPage();await login(q,'teacher_li','teacher123');await q.goto(base+'/me/badges');await q.locator('.ant-result-403').waitFor();assert.equal(await q.locator('.badge-room').count(),0);await c.close();await go('/me/badges?returnTo='+encodeURIComponent('https://evil.invalid'));await p.getByRole('link',{name:'返回我的',exact:true}).waitFor();assert.equal(await p.getByRole('link',{name:'返回我的',exact:true}).getAttribute('href'),'/me');assert.equal(db.prepare("SELECT count(*) n FROM schema_migrations WHERE version LIKE '%coin%'").get().n,0);
 });
 assert.deepEqual(errors,[]);
 }finally{for(const c of contexts)for(const page of c.pages()){const events=await page.evaluate(()=>window.badgeRoomPointerEvents).catch(()=>null);if(events)fs.writeFileSync(path.join(out,'touch-events.json'),JSON.stringify(events,null,2));}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({records,pageErrors:errors,browser:browser.version(),scope:'Disposable SQLite only. Native Playwright mouse/touchscreen and CDP touch events; no force clicks or DOM-dispatched activation. Existing real server grants/authorization; synthetic large gallery explicitly separated.'},null,2));for(const c of contexts)await c.close().catch(()=>{});await browser.close();await new Promise(r=>front.close(r));backend.kill();db.close();}
});
