import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
import {fixture,root,Database} from './v2-fixture.mjs';
const out=path.join(root,'docs/next-version/step-01'),run=process.env.PBL_NEXT_RUN||'first',evidence=path.join(out,'evidence-'+run);
fs.mkdirSync(evidence,{recursive:true});
const base='http://127.0.0.1:4194',api='http://127.0.0.1:3164';
async function ready(url){for(let i=0;i<150;i++){try{if((await fetch(url)).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Not ready '+url);}
const records=[];
test('下一版第一步：隔离持久环境和真实浏览器', {timeout:360000}, async t=>{
 const f=fixture(3164,4194);
 // Metadata is kept ignored, not in the public evidence gallery.
 const privateSource=path.join(root,'test-results','next-step01-source-'+run+'.json');fs.mkdirSync(path.dirname(privateSource),{recursive:true});fs.writeFileSync(privateSource,JSON.stringify({db:f.env.DB_PATH,scratch:f.scratch}));
 const rel='.local/acceptance-'+run+'-'+Date.now(),dir=path.join(root,rel);
 execFileSync(process.execPath,['scripts/teaching.mjs','init','--source',privateSource,'--data',rel],{cwd:root,stdio:'pipe',windowsHide:true});
 const configPath=path.join(dir,'private.json'),config=JSON.parse(fs.readFileSync(configPath));config.apiPort=3164;config.frontPort=4194;fs.writeFileSync(configPath,JSON.stringify(config));
 const report=JSON.parse(fs.readFileSync(path.join(dir,'import-report.json'))),id=report.courseId,[visit,theory,experiment]=report.lessonIds;
 let child;const start=async()=>{child=spawn(process.execPath,['scripts/teaching.mjs','start','--data',rel],{cwd:root,env:{...process.env,LOGIN_RATE_LIMIT_IP:'500',LOGIN_RATE_LIMIT_USER:'500'},stdio:'pipe',windowsHide:true});child.stdout.resume();child.stderr.resume();await ready(api+'/api/health');await ready(base);};
 const stop=async()=>{execFileSync(process.execPath,['scripts/teaching.mjs','stop','--data',rel],{cwd:root,stdio:'pipe',windowsHide:true});await new Promise(r=>child.once('exit',r));};
 await start();const db=new Database(path.join(dir,'teaching.db'));const browser=await chromium.launch({channel:'msedge',headless:true});
 const mc=await browser.newContext(),sc=await browser.newContext(),m=await mc.newPage(),s=await sc.newPage(),errors=[];for(const p of[m,s]){p.on('pageerror',e=>errors.push(e.message));p.on('console',message=>{if(message.type()==='error')console.log('BROWSER_CONSOLE',message.text());});p.on('request',r=>{if(r.url().includes('/download'))console.log('DOWNLOAD_REQUEST',r.url());});p.on('response',r=>{if(r.url().includes('/download'))console.log('DOWNLOAD_RESPONSE',r.status());});p.setDefaultTimeout(15000);}
 const login=async(p,name='student_wang',pw='student123')=>{await p.goto(base+'/login');await p.getByLabel('账号',{exact:true}).fill(name);await p.getByLabel('密码',{exact:true}).fill(pw);await p.getByRole('button',{name:'登录',exact:true}).click();await p.waitForURL(u=>u.pathname!='/login');};
 const go=async(p,url)=>{await p.goto(base+url);await p.locator('.student-content,.maintenance-workspace,.course-detail').first().waitFor().catch(()=>{});};
 const request=async(name,pw,url,method='GET',data)=>{const log=await fetch(api+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password:pw})}),auth=await log.json();const r=await fetch(api+'/api'+url,{method,headers:{Authorization:'Bearer '+auth.token,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return{status:r.status,data:await r.json()};};
 const b=(p,name)=>p.getByRole('button',{name:new RegExp('^'+[...name].join('\\s*')+'$')}),modal=p=>p.locator('.ant-modal').filter({visible:true});
 const shot=async(p,name)=>{await p.screenshot({path:path.join(out,'screenshots',name+'.png'),fullPage:false});};
 async function scene(name,fn){let failure;await t.test(name,async()=>{try{await fn();records.push({name,status:'passed'});}catch(e){failure=e;records.push({name,status:'failed',error:e.message});console.log('FAILURE',e.message,m.url(),(await m.locator('body').innerText()).slice(-1800),s.url(),(await s.locator('body').innerText()).slice(-1800));await shot(m,'failure-maintenance-'+run);await shot(s,'failure-student-'+run);throw e;}});if(failure)throw failure;}
 let resourceId;
 try{
 await scene('导师保存真实课时文字与附件；独立前后端重启和二次启动不覆盖',async()=>{
  await login(m,'mentor_zhang','mentor123');await m.goto(base+`/courses/${id}?tab=maintenance`);await m.getByTestId('content-maintenance').waitFor();await m.getByRole('tab',{name:'地图计划与课时',exact:true}).click();const card=m.locator('.ant-card').filter({has:m.getByText('滑翔机试飞理论课',{exact:true})}).last();await b(card,'编辑课时说明与归属').click();await modal(m).getByLabel('说明',{exact:true}).fill('隔离验收：重启后保留的课时说明。');await b(modal(m),'保存').click();await modal(m).getByText(/已保存 #/).waitFor();await modal(m).locator('.ant-modal-close').click();
  await m.getByRole('tab',{name:'教学资料与回放',exact:true}).click();const q=m.getByTestId('upload-resource');await q.locator('input[type=file]').setInputFiles({name:'持久验收.txt',mimeType:'text/plain',buffer:Buffer.from('真实文件字节：隔离持久验收')});await b(q,'上传待处理文件').click();await q.getByText('上传成功',{exact:true}).waitFor();resourceId=db.prepare("SELECT id FROM resources WHERE course_id=? AND file_name='持久验收.txt'").get(id).id;
  await stop();await start();assert.equal(db.prepare('SELECT description FROM lessons WHERE id=?').get(theory).description,'隔离验收：重启后保留的课时说明。');const after=db.prepare('SELECT id,file_path FROM resources WHERE id=?').get(resourceId);assert.equal(fs.readFileSync(after.file_path,'utf8'),'真实文件字节：隔离持久验收');assert.equal(db.prepare('SELECT count(*) n FROM course_plan_nodes WHERE course_id=?').get(id).n,10);
  await login(s);await go(s,`/courses/${id}/lessons/${theory}/learn`);await s.getByText('隔离验收：重启后保留的课时说明',{exact:true}).waitFor();const download=await Promise.all([s.waitForEvent('download'),s.getByRole('button',{name:'下载：持久验收.txt',exact:true}).click()]);const file=await download[0].path();assert.equal(fs.readFileSync(file,'utf8'),'真实文件字节：隔离持久验收');await shot(s,'persisted-learning');await stop();await start();assert.equal(db.prepare('SELECT count(*) n FROM resources WHERE id=?').get(resourceId).n,1);
 });
 await scene('一致性备份与独立副本恢复保留数据库、文件与稳定密钥',async()=>{
  const backup=rel+'-backup',restored=rel+'-restored';execFileSync(process.execPath,['scripts/teaching.mjs','backup','--data',rel,'--to',backup],{cwd:root,stdio:'pipe',windowsHide:true});execFileSync(process.execPath,['scripts/teaching.mjs','restore','--data',restored,'--from',backup],{cwd:root,stdio:'pipe',windowsHide:true});const d=new Database(path.join(root,restored,'teaching.db'),{readonly:true});assert.equal(d.pragma('integrity_check',{simple:true}),'ok');assert.equal(d.prepare('SELECT description FROM lessons WHERE id=?').get(theory).description,'隔离验收：重启后保留的课时说明。');const r=d.prepare('SELECT file_path FROM resources WHERE id=?').get(resourceId);assert.ok(r.file_path.startsWith(path.join(root,restored)));assert.equal(fs.readFileSync(r.file_path,'utf8'),'真实文件字节：隔离持久验收');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,restored,'private.json'))),config);d.close();assert.throws(()=>execFileSync(process.execPath,['scripts/teaching.mjs','init','--source',privateSource,'--data',rel],{cwd:root,stdio:'pipe',windowsHide:true}));
 });
 await scene('十关首三真实对象、未知节点、曲线路线五视口与地图末端',async()=>{
  await go(s,`/courses/${id}`);await s.locator('[data-plan-position="10"]').waitFor();assert.equal(await s.locator('.route-node').count(),10);assert.match(await s.locator('.space-route-summary').innerText(),/10个关卡/);assert.deepEqual(await s.locator('[data-lesson-id]').evaluateAll(es=>es.map(e=>Number(e.dataset.lessonId))),[visit,theory,experiment]);assert.equal(await s.getByText(/测试章节/).count(),0);
  for(const [w,h]of [[1440,900],[768,1024],[390,844],[360,800],[844,390]]){await s.setViewportSize({width:w,height:h});await s.evaluate(()=>scrollTo(0,0));await s.waitForTimeout(200);const d=await s.locator('.pixel-map-track-dashes').getAttribute('d');assert.ok((d.match(/C /g)||[]).length>=9);assert.equal(await s.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot(s,'map-'+w);await s.locator('.space-map-extra').scrollIntoViewIfNeeded();const gap=await s.locator('.space-map-extra').evaluate(e=>document.documentElement.scrollHeight-(e.getBoundingClientRect().bottom+scrollY));assert.ok(gap<100,'bottom gap '+gap);await shot(s,'map-end-'+w);await s.locator('[data-plan-position="10"] button').click();await modal(s).getByText('这一关尚未开放，课时和任务正在准备',{exact:true}).waitFor();assert.equal(await modal(s).getByRole('button',{name:'进入课时',exact:true}).count(),0);await s.keyboard.press('Escape');await s.waitForFunction(()=>document.activeElement===document.querySelector('[data-plan-position="10"] button'));assert.equal(await s.locator('[data-plan-position="10"] button').evaluate(e=>document.activeElement===e),true);}
  await s.setViewportSize({width:1440,height:900});await go(s,`/courses/${id}`);await s.locator('.space-place-astronaut').waitFor();assert.equal(await s.locator('.space-place-avatar').count(),0);
 });
 await scene('参观空精彩瞬间和文章位；理论实验无样例教材且不批量完成',async()=>{
  await go(s,`/courses/${id}/lessons/${visit}/learn`);await s.getByText('精彩瞬间',{exact:true}).waitFor();await s.getByText('文章链接待提供',{exact:true}).waitFor();assert.equal(await s.locator('iframe').count(),0);assert.equal(await s.getByRole('button',{name:/完成课堂回顾|提交报告/}).count(),0);await shot(s,'visit-1440');
  for(const l of[theory,experiment]){await go(s,`/courses/${id}/lessons/${l}/learn`);await s.getByTestId('lesson-template').waitFor();assert.equal(await s.locator('.study-exercise').count(),0);assert.equal(db.prepare('SELECT count(*) n FROM knowledge_cards WHERE lesson_id=?').get(l).n,0);const r=await request('student_wang','student123',`/learning/lessons/${l}/review-complete`,'POST',{});assert.equal(r.status,409);assert.equal(db.prepare('SELECT count(*) n FROM lesson_review_completions WHERE lesson_id=?').get(l).n,0);}
 });
 await scene('实验第三课关联往返；未关联课时无入口且独立实验仍可用',async()=>{
  await go(s,`/courses/${id}/lessons/${theory}/learn`);await s.getByTestId('lesson-template').waitFor();assert.equal(await b(s,'滑翔机试飞').count(),0);await go(s,`/courses/${id}/lessons/${experiment}/learn`);await b(s,'滑翔机试飞').click();await s.waitForURL(/\/glider\?/);await s.getByRole('button',{name:/返回来源课程/}).click();await s.waitForURL(new RegExp('/lessons/'+experiment+'/learn'));assert.equal(new URL(s.url()).searchParams.get('stage'),'0');await shot(s,'experiment-return');await go(s,'/lab');await s.locator('.lab-start-link').click();await s.waitForURL('**/glider');await s.getByText('实验环境就绪，可以开始试飞',{exact:true}).waitFor();await b(s,'开始试飞').click();await s.getByText('计算成功',{exact:true}).waitFor({timeout:120000});const flight=db.prepare('SELECT * FROM glider_simulations WHERE student_id=4 ORDER BY id DESC').get();assert.equal(flight.course_id,null);assert.equal(flight.lesson_id,null);assert.equal(db.prepare('SELECT count(*) n FROM lesson_review_completions WHERE lesson_id=?').get(experiment).n,0);await shot(s,'free-flight');
 });
 await scene('账号头像真实读写重登、课程选择隔离及失败/回读失败',async()=>{
  await go(s,'/me');await b(s,'选择账号头像').click();await b(modal(s),'校园银杏').click();await s.getByText('账号头像已保存',{exact:true}).first().waitFor();assert.equal(db.prepare('SELECT avatar_preset FROM users WHERE id=4').get().avatar_preset,'ginkgo');await s.keyboard.press('Escape');await s.reload();await s.locator('.account-avatar-trigger img[src*="ginkgo"]').waitFor();
  for(const [width,height]of [[1440,900],[768,1024],[390,844]]){await s.setViewportSize({width,height});await b(s,'选择账号头像').click();await s.locator('.account-avatar-grid button').last().waitFor();await shot(s,'avatars-'+width);await s.keyboard.press('Escape');}await s.setViewportSize({width:1440,height:900});
  const role=db.prepare('SELECT avatar_id FROM course_avatar_preferences WHERE student_id=4 AND course_id=?').get(id);assert.equal(role,undefined);await b(s,'选择账号头像').click();await s.route('**/api/account/avatar',r=>r.request().method()==='PUT'?r.fulfill({status:503,json:{error:'隔离验收：头像保存失败'}}):r.continue());await b(modal(s),'小火箭').click();await s.getByText('隔离验收：头像保存失败',{exact:true}).first().waitFor();assert.equal(await b(modal(s),'校园银杏').getAttribute('aria-pressed'),'true');await s.unroute('**/api/account/avatar');
  await s.route('**/api/auth/me',r=>r.fulfill({status:503,json:{error:'隔离验收：回读失败'}}));await b(modal(s),'小火箭').click();await s.getByText(/头像已写入服务器/).first().waitFor();assert.equal(db.prepare('SELECT avatar_preset FROM users WHERE id=4').get().avatar_preset,'rocket');await shot(s,'avatar-read-failure');await s.unroute('**/api/auth/me');await s.keyboard.press('Escape');await login(s);await go(s,'/me');await s.locator('.account-avatar-trigger img[src*="rocket"]').waitFor();
  await go(s,`/courses/${id}`);await b(s,'选择角色头像').click();await s.locator('.course-avatar-grid button').filter({hasText:'江予川'}).click();await s.getByRole('status').filter({hasText:'已保存'}).waitFor();await s.keyboard.press('Escape');assert.equal(db.prepare('SELECT avatar_preset FROM users WHERE id=4').get().avatar_preset,'rocket');await login(s,'student_chen');await go(s,'/me');await s.locator('.account-avatar-trigger img[src*="pilot"]').waitFor();assert.equal(db.prepare('SELECT avatar_preset FROM users WHERE id=5').get().avatar_preset,null);await login(s);
 });
 await scene('机器人 Portal 固定视口、鼠标拖动不打开、缩放夹紧、键盘重置',async()=>{
  await go(s,`/courses/${id}`);const robot=s.locator('.course-robot');await robot.waitFor();assert.equal(await robot.evaluate(e=>e.closest('.course-assistant-host').parentNode===document.body),true);const before=await robot.boundingBox();await s.evaluate(()=>scrollTo(0,700));await s.waitForTimeout(150);const after=await robot.boundingBox();assert.ok(Math.abs(before.y-after.y)<1);
  await s.mouse.move(after.x+30,after.y+30);await s.mouse.down();await s.mouse.move(430,260,{steps:10});await s.mouse.up();assert.equal(await s.locator('#course-chat').isVisible(),false);const dragged=await robot.boundingBox();assert.ok(dragged.x<600);await s.evaluate(()=>scrollTo(0,0));assert.ok(Math.abs((await robot.boundingBox()).y-dragged.y)<1);await s.setViewportSize({width:360,height:800});await s.waitForTimeout(200);const box=await robot.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=360);await robot.focus();await s.keyboard.press('Home');await s.keyboard.press('Enter');await s.locator('#course-chat').waitFor({state:'visible'});await shot(s,'robot-chat-360');await s.keyboard.press('Escape');assert.equal(await robot.evaluate(e=>document.activeElement===e),true);await s.setViewportSize({width:844,height:390});await robot.click();const chat=await s.locator('#course-chat').boundingBox();assert.ok(chat.x>=0&&chat.y>=0&&chat.x+chat.width<=844&&chat.y+chat.height<=391);await s.keyboard.press('Escape');await s.setViewportSize({width:1440,height:900});
 });
 await scene('触屏拖动不误开；减少运动、页面滚动、横屏和模拟软键盘夹紧',async()=>{
  const tc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await tc.newPage();p.on('pageerror',e=>errors.push(e.message));
  try{
   await login(p);await go(p,`/courses/${id}`);const robot=p.locator('.course-robot');await robot.waitFor();assert.equal(await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);
   const box=await robot.boundingBox(),cdp=await tc.newCDPSession(p),touch=(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y,id:1}]});
   await touch('touchStart',box.x+30,box.y+30);for(let n=1;n<=8;n++)await touch('touchMove',box.x+30+(110-box.x-30)*n/8,box.y+30+(250-box.y-30)*n/8);await touch('touchEnd');await p.waitForTimeout(150);
   assert.equal(await p.locator('#course-chat').isVisible(),false);const dragged=await robot.boundingBox();assert.ok(dragged.x<150&&dragged.y<300);await p.evaluate(()=>scrollTo(0,600));assert.ok(Math.abs((await robot.boundingBox()).y-dragged.y)<1);assert.equal(await p.evaluate(()=>document.body.style.overflow==='hidden'),false);await shot(p,'robot-touch-390');
   await robot.tap();await p.locator('#course-chat').waitFor({state:'visible'});await p.keyboard.press('Escape');await p.setViewportSize({width:844,height:390});await p.waitForTimeout(180);const landscape=await robot.boundingBox();assert.ok(landscape.x>=0&&landscape.y>=0&&landscape.x+landscape.width<=844&&landscape.y+landscape.height<=390);
   // A real OS keyboard is unavailable in headless Edge. Explicitly simulate its visualViewport events.
   await tc.addInitScript(()=>{const v=new EventTarget();Object.assign(v,{width:390,height:844,offsetLeft:0,offsetTop:0});Object.defineProperty(window,'visualViewport',{value:v,configurable:true});window.acceptanceKeyboard=(height,top)=>{Object.assign(v,{height,offsetTop:top});v.dispatchEvent(new Event('resize'));v.dispatchEvent(new Event('scroll'));};});
   await p.setViewportSize({width:390,height:844});await go(p,`/courses/${id}`);await robot.waitFor();await p.evaluate(()=>window.acceptanceKeyboard(300,70));await p.waitForTimeout(180);const key=await robot.boundingBox();assert.ok(key.x>=0&&key.x+key.width<=390&&key.y>=70&&key.y+key.height<=370);await robot.tap();const chat=await p.locator('#course-chat').boundingBox();assert.ok(chat.y>=70&&chat.y+chat.height<=370);await shot(p,'robot-keyboard-simulated');await p.keyboard.press('Escape');assert.equal(await robot.evaluate(e=>document.activeElement===e),true);await robot.focus();await p.keyboard.press('Home');await p.keyboard.press('Enter');assert.equal(await p.locator('#course-chat').isVisible(),true);
  }finally{await tc.close();}
 });
 await scene('未知平台图像失效仍显示编号、说明和可用详情',async()=>{
  await s.route('**/assets/next-version/step-01/web/**',r=>r.fulfill({status:404,body:''}));try{await go(s,`/courses/${id}`);const future=s.locator('[data-plan-position="10"]');await future.scrollIntoViewIfNeeded();await future.locator('[data-place-failed]').waitFor();assert.match(await future.innerText(),/10/);await future.locator('button').click();await modal(s).getByText('这一关尚未开放，课时和任务正在准备',{exact:true}).waitFor();await shot(s,'map-image-fallback');await s.keyboard.press('Escape');}finally{await s.unroute('**/assets/next-version/step-01/web/**');}
 });
 await scene('权限失效清除；教师学生不可写；未来计划不绕过授权',async()=>{
  for(const [name,pw]of [['student_wang','student123'],['teacher_li','teacher123']]){const r=await request(name,pw,`/courses/${id}/maintenance/lessons/${theory}`,'PUT',{description:'不得写入'});assert.equal(r.status,403);}
  const wrong=await request('mentor_zhang','mentor123',`/courses/${id}/maintenance/plan`,'PUT',{nodes:[{position:1,lessonId:90011}]});assert.equal(wrong.status,400);const bad=await request('student_wang','student123','/account/avatar','PUT',{presetId:'https://bad',userId:2});assert.equal(bad.status,400);
  await go(s,`/courses/${id}`);await s.locator('.route-node').first().waitFor();db.prepare("UPDATE courses SET status='draft' WHERE id=?").run(id);await s.evaluate(()=>{dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));});await s.locator('.route-node').first().waitFor({state:'hidden'});assert.equal((await request('student_wang','student123',`/learning/lessons/${visit}`)).status,404);await shot(s,'course-withdrawn');db.prepare("UPDATE courses SET status='published' WHERE id=?").run(id);
  await go(s,`/courses/${id}`);await s.locator('.route-node').first().waitFor();db.prepare("UPDATE enrollments SET status='removed' WHERE course_id=? AND student_id=4").run(id);await s.reload();await s.locator('.route-node').first().waitFor({state:'hidden'});db.prepare("UPDATE enrollments SET status='active' WHERE course_id=? AND student_id=4").run(id);
 });
 assert.deepEqual(errors,[]);
 }finally{fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify({records,pageErrors:errors,courseId:id,lessonIds:report.lessonIds,ports:{base,api},scope:'isolated synthetic persistent runtime; existing teaching/4174 untouched'},null,2));await browser.close();db.close();await stop().catch(()=>child?.kill());}
});
