import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {chromium} from 'playwright';import {fixture,root,Database} from './v2-fixture.mjs';
const out=path.join(root,'docs/next-version/step-03/recovery-'+(process.env.PBL_RECOVERY_RUN||'first'));fs.mkdirSync(out,{recursive:true});const base='http://127.0.0.1:4224',api='http://127.0.0.1:3194';
test('下一版第三步补充：徽章队列、回读失败、账号切换及离线重置恢复',{timeout:180000},async t=>{
 const f=fixture(3194,4224),source=path.join(root,'test-results/recovery-source-'+Date.now()+'.json');fs.writeFileSync(source,JSON.stringify({db:f.env.DB_PATH,scratch:f.scratch}));const rel='.local/reward-recovery-'+Date.now(),dir=path.join(root,rel);execFileSync(process.execPath,['scripts/teaching.mjs','init','--source',source,'--data',rel],{cwd:root,stdio:'pipe',windowsHide:true});const cp=path.join(dir,'private.json'),config=JSON.parse(fs.readFileSync(cp));config.apiPort=3194;config.frontPort=4224;fs.writeFileSync(cp,JSON.stringify(config));const report=JSON.parse(fs.readFileSync(path.join(dir,'import-report.json'))),db=new Database(path.join(dir,'teaching.db'));
 for(const id of report.lessonIds.slice(1)){db.prepare("UPDATE lessons SET content_state='ready' WHERE id=?").run(id);const card=Number(db.prepare("INSERT INTO knowledge_cards(lesson_id,title,content,status,created_by) VALUES(?,'恢复合成卡片','非正式材料','published',2)").run(id).lastInsertRowid);db.prepare('INSERT INTO lesson_review_completions(student_id,lesson_id) VALUES(4,?)').run(id);db.prepare('INSERT INTO student_card_progress(student_id,card_id,completed_at) VALUES(4,?,CURRENT_TIMESTAMP)').run(card);db.prepare("INSERT INTO lesson_learning_reports(student_id,lesson_id,summary,status) VALUES(4,?,'合成报告','approved')").run(id);}
 const child=spawn(process.execPath,['scripts/teaching.mjs','start','--data',rel],{cwd:root,windowsHide:true,stdio:'pipe'});child.stdout.resume();child.stderr.resume();for(let i=0;i<100;i++){try{if((await fetch(api+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await chromium.launch({channel:'msedge',headless:true}),c=await browser.newContext({viewport:{width:1440,height:900}}),p=await c.newPage(),records=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);const modal=()=>p.locator('.ant-modal').filter({visible:true}).last();
 const login=async(name='student_wang')=>{await p.goto(base+'/login');await p.getByLabel('账号',{exact:true}).fill(name);await p.getByLabel('密码',{exact:true}).fill('student123');await p.getByRole('button',{name:'登录',exact:true}).click();await p.waitForURL(u=>u.pathname!='/login');};const go=async url=>{await p.goto(base+url);await p.locator('.student-content').waitFor();};const scene=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();records.push({name,status:'passed'});}catch(e){failure=e;records.push({name,status:'failed',error:e.message});await p.screenshot({path:path.join(out,'failure-'+records.length+'.png')});throw e;}});if(failure)throw failure;};
 try{
 await p.route('**/api/rewards/badges',r=>r.abort());await login();await go('/me');
 await scene('颁发已提交但主页回读失败，不称已佩戴；重读后两个徽章依次可关闭且不重复',async()=>{
  await p.getByText('Network Error',{exact:true}).first().waitFor();assert.equal(db.prepare('SELECT count(*) n FROM student_badge_grants').get().n,2);assert.equal(db.prepare('SELECT count(*) n FROM student_badge_grants WHERE shown_at IS NOT NULL').get().n,0);assert.equal(await p.locator('.next-award').count(),0);
  await p.unroute('**/api/rewards/badges');await p.getByRole('button',{name:'重新读取',exact:true}).first().click();await p.locator('.next-award').waitFor();const first=await p.locator('.next-award').getAttribute('data-grant-id');assert.equal(await p.locator('.next-award').count(),1);await p.waitForTimeout(500);
  const frames=await p.locator('.next-award').evaluate(n=>{const a=n.getAnimations().find(a=>a.animationName==='badge-arrive');return a?.effect.getKeyframes();});assert.ok(frames.some(f=>f.opacity==='0'));assert.ok(frames.some(f=>f.opacity==='1'));fs.writeFileSync(path.join(out,'animation-keyframes.json'),JSON.stringify(frames,null,2));
  for(const ms of [120,420]){await p.locator('.next-award').evaluate((n,ms)=>{const a=n.getAnimations().find(a=>a.animationName==='badge-arrive');a.pause();a.currentTime=ms;},ms);await p.screenshot({path:path.join(out,'animation-frame-'+ms+'.png')});}
  await modal().locator('.ant-modal-close').click();await p.waitForFunction(id=>document.querySelector('.next-award')?.dataset.grantId!==id&&document.querySelector('.next-award'),first);assert.equal(await p.locator('.next-award').count(),1);await p.mouse.click(2,150);await p.locator('.next-award').waitFor({state:'hidden'});assert.equal(db.prepare('SELECT count(*) n FROM student_badge_grants WHERE shown_at IS NOT NULL').get().n,2);await p.waitForFunction(()=>document.activeElement.getAttribute('aria-current')==='page');await p.reload();await p.locator('[data-real-grant]').first().waitFor();assert.equal(await p.locator('.next-award').count(),0);
 });
 await scene('离线已扣币后重置保留原意图，切账号不发旧意图；回到原账号补发一条消息',async()=>{
  await p.route('**/api/rewards/exchanges',r=>r.abort());await p.locator('[data-gift="notebook"]').getByRole('button').click();await modal().getByRole('button',{name:'演示兑换',exact:true}).click();await modal().getByRole('button',{name:'确认演示兑换',exact:true}).click();await modal().getByText('演示兑换已记录，消息待同步',{exact:true}).waitFor();await p.getByTestId('reward-balance').filter({hasText:'80'}).waitFor();await p.keyboard.press('Escape');await p.getByRole('button',{name:'重置演示数据',exact:true}).click();await modal().getByRole('button',{name:'确认重置演示数据',exact:true}).click();await p.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();await p.getByText('演示兑换已记录，消息待同步',{exact:true}).waitFor();
  const intent=await p.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('star-voyage-rewards',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('accounts'),q=t.objectStore('accounts').get('4');q.onsuccess=()=>{resolve(q.result.meta.outbox[0].id);db.close();};q.onerror=reject;};}));await p.getByRole('button',{name:'退出登录',exact:true}).click();await login('student_chen');await p.unroute('**/api/rewards/exchanges');await go('/me');await p.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();await p.waitForTimeout(400);assert.equal(db.prepare('SELECT count(*) n FROM demo_exchange_events').get().n,0);assert.equal(await p.locator('[data-real-grant]').count(),0);await p.getByRole('button',{name:'退出登录',exact:true}).click();await login();await go('/me');await p.getByText('演示兑换已记录，消息待同步',{exact:true}).waitFor({state:'hidden'});await p.getByRole('tab',{name:'兑换记录',exact:true}).click();await p.getByText('账号演示兑换记录（后端）',{exact:true}).waitFor();await p.waitForFunction(()=>!document.querySelector('.reward-notice')?.textContent?.includes('消息待同步'));
  assert.equal(db.prepare('SELECT count(*) n FROM demo_exchange_events').get().n,1);assert.equal(db.prepare('SELECT operation_id FROM demo_exchange_events').get().operation_id,intent);assert.equal(db.prepare("SELECT count(*) n FROM notifications WHERE event_key='demo_exchange'").get().n,1);await p.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();await p.screenshot({path:path.join(out,'reset-recovered-history.png')});
 });
 await scene('真实浏览器存储拒绝不签到成功，恢复后只保存一次；日期重读仍真实',async()=>{
  await p.evaluate(()=>{window.realIDB=indexedDB;Object.defineProperty(window,'indexedDB',{configurable:true,get(){throw Error('synthetic storage denied');}});});await p.getByRole('button',{name:'签到 +5',exact:true}).click();await p.getByText(/浏览器不允许访问奖励数据库/).first().waitFor();assert.equal(await p.getByText('签到已保存，获得 5 枚演示金币',{exact:true}).count(),0);await p.evaluate(()=>Object.defineProperty(window,'indexedDB',{configurable:true,value:window.realIDB}));await p.locator('.reward-notice').filter({hasText:'演示数据暂不可用'}).getByRole('button',{name:'重试读取',exact:true}).click();await p.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();await p.getByRole('button',{name:'签到 +5',exact:true}).click();await p.getByTestId('reward-balance').filter({hasText:'125'}).waitFor();await p.getByRole('button',{name:'今日已签到',exact:true}).waitFor();
 });
 assert.deepEqual(errors,[]);
 }finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({records,pageErrors:errors,scope:'All qualification data, storage faults and account switching use isolated synthetic database/browser. Animation frames are real CSS animation paused at 120/420ms in this test only.'},null,2));await browser.close();db.close();execFileSync(process.execPath,['scripts/teaching.mjs','stop','--data',rel],{cwd:root,stdio:'pipe',windowsHide:true});}
});
