import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {chromium} from 'playwright';import {fixture,root,Database} from './v2-fixture.mjs';
const run=process.env.PBL_STEP03_RUN||'first',out=path.join(root,'docs/next-version/step-03/browser-'+run),shots=path.join(out,'screenshots');fs.mkdirSync(shots,{recursive:true});const base='http://127.0.0.1:4214',api='http://127.0.0.1:3184';
const ready=async url=>{for(let i=0;i<160;i++){try{if((await fetch(url)).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Not ready '+url);};
test('下一版第三步：真实教学预览奖励端到端验收',{timeout:480000},async t=>{
 const f=fixture(3184,4214),source=path.join(root,'test-results','step03-source-'+run+'.json');fs.mkdirSync(path.dirname(source),{recursive:true});fs.writeFileSync(source,JSON.stringify({db:f.env.DB_PATH,scratch:f.scratch}));const rel='.local/step03-'+run+'-'+Date.now(),dir=path.join(root,rel);execFileSync(process.execPath,['scripts/teaching.mjs','init','--source',source,'--data',rel],{cwd:root,stdio:'pipe',windowsHide:true});const cp=path.join(dir,'private.json'),config=JSON.parse(fs.readFileSync(cp));config.apiPort=3184;config.frontPort=4214;fs.writeFileSync(cp,JSON.stringify(config));const imported=JSON.parse(fs.readFileSync(path.join(dir,'import-report.json'))),courseId=imported.courseId,[visit,theory,experiment]=imported.lessonIds,db=new Database(path.join(dir,'teaching.db'));
 db.prepare("UPDATE lessons SET content_state='ready' WHERE id=?").run(theory);
 const card=Number(db.prepare("INSERT INTO knowledge_cards(lesson_id,title,content,status,created_by) VALUES(?,'第三步隔离知识卡片','合成验收，非正式教材','published',2)").run(theory).lastInsertRowid);
 const taskId=Number(db.prepare("INSERT INTO tasks(lesson_id,title,require_upload) VALUES(?,'第三步合成文字作品',0)").run(theory).lastInsertRowid);
 const workId=Number(db.prepare("INSERT INTO works(student_id,task_id,title,description,review_status) VALUES(4,?,'合成文字作品','验证徽章作品判据','rejected')").run(taskId).lastInsertRowid);
 db.prepare('INSERT INTO lesson_review_completions(student_id,lesson_id) VALUES(4,?)').run(theory);db.prepare('INSERT INTO student_card_progress(student_id,card_id,completed_at) VALUES(4,?,CURRENT_TIMESTAMP)').run(card);
 db.prepare("INSERT INTO lesson_learning_reports(student_id,lesson_id,summary,status) VALUES(4,?,'合成已通过报告','approved')").run(theory);db.prepare('INSERT INTO lesson_progress(student_id,lesson_id,progress) VALUES(4,?,100)').run(theory);
 let child;const start=async()=>{child=spawn(process.execPath,['scripts/teaching.mjs','start','--data',rel],{cwd:root,env:{...process.env,LOGIN_RATE_LIMIT_IP:'1000',LOGIN_RATE_LIMIT_USER:'1000'},stdio:'pipe',windowsHide:true});child.stdout.resume();child.stderr.resume();await ready(api+'/api/health');await ready(base);};const stop=async()=>{execFileSync(process.execPath,['scripts/teaching.mjs','stop','--data',rel],{cwd:root,stdio:'pipe',windowsHide:true});if(child.exitCode===null)await new Promise(r=>child.once('exit',r));};await start();
 const browser=await chromium.launch({channel:'msedge',headless:true}),contexts=[],errors=[],records=[],tokens={};
 const make=async()=>{const c=await browser.newContext({viewport:{width:1440,height:900}});contexts.push(c);const p=await c.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));return {c,p};};
 const login=async(p,user='student_wang',password='student123')=>{await p.goto(base+'/login');await p.getByLabel('账号',{exact:true}).fill(user);await p.getByLabel('密码',{exact:true}).fill(password);await p.getByRole('button',{name:'登录',exact:true}).click();await p.waitForURL(u=>u.pathname!='/login');};
 const b=(p,text)=>p.getByRole('button',{name:new RegExp('(?:^|\\s)'+[...text].map(c=>RegExp.escape(c)).join('\\s*')+'$')}),dialog=p=>p.locator('.ant-modal').filter({visible:true}).last();
 const go=async(p,url)=>{await p.goto(base+url);await p.locator('.student-content,.staff-content').first().waitFor();};
 const shot=async(p,name)=>{await p.bringToFront();await p.waitForTimeout(600);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(150);await p.screenshot({path:path.join(shots,name+'.png')});};
 const request=async(role,url,method='GET',body)=>{if(!tokens[role]){const [username,password]=role==='admin'?['adminpbl','admin123']:['student_wang','student123'];tokens[role]=(await fetch(api+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}).then(r=>r.json())).token;}const r=await fetch(api+'/api'+url,{method,headers:{Authorization:'Bearer '+tokens[role],'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return{status:r.status,data:await r.json()};};
 const scene=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();records.push({name,status:'passed'});}catch(e){failure=e;records.push({name,status:'failed',error:e.message});await shot(s,'failure-'+records.length).catch(()=>{});throw e;}});if(failure)throw failure;};
 const {c,p:s}=await make();let other,a;
 try{
 await login(s);await go(s,'/me');await s.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();
 await scene('本人签到双标签去重、余额和明细共享；报告已通过但作品退回不发徽章',async()=>{
  other=await c.newPage();await go(other,'/me');await b(s,'签到 +5').waitFor();await Promise.all([b(s,'签到 +5').click(),b(other,'签到 +5').click()]);for(const p of[s,other]){await p.getByTestId('reward-balance').filter({hasText:'125'}).waitFor();assert.match(await p.getByTestId('header-demo-points').innerText(),/125/);await b(p,'今日已签到').waitFor();}
  assert.equal(db.prepare('SELECT count(*) n FROM student_badge_grants').get().n,0);await s.getByRole('tab',{name:'金币明细',exact:true}).click();assert.equal(await s.getByText('每日签到（本地演示）',{exact:true}).count(),1);await shot(s,'checkin-ledger');await s.reload();await b(s,'今日已签到').waitFor();
 });
 await scene('离线日期不放行；模拟北京午夜及重新可见后次日只加一次',async()=>{
  await s.route('**/api/rewards/day',r=>r.abort());await s.evaluate(()=>dispatchEvent(new Event('focus')));await s.getByText('Network Error',{exact:true}).first().waitFor();assert.equal(await b(s,'签到 +5').isEnabled(),false);await s.unroute('**/api/rewards/day');
  await s.route('**/api/rewards/day',r=>r.fulfill({json:{date:'2099-12-31',validForMs:60000}}));await s.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await b(s,'签到 +5').click();await s.getByTestId('reward-balance').filter({hasText:'130'}).waitFor();await b(s,'今日已签到').waitFor();await s.unroute('**/api/rewards/day');await s.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await b(s,'今日已签到').waitFor();
 });
 await scene('真实课时徽章资格和十关未知节点可见；无自动发放空参观与实验',async()=>{
  await go(s,`/courses/${courseId}`);await s.locator('[data-plan-position="2"] .route-node').click();await s.getByText('完成后可获得：理论探索',{exact:true}).waitFor();await s.getByText(/作品任务《第三步合成文字作品》需要修改/).waitFor();await shot(s,'map-badge-criteria');await s.keyboard.press('Escape');assert.equal((await request('student','/rewards/badges')).data.grants.length,0);assert.equal(await s.locator('.route-node').count(),10);
 });
 await scene('首次真正满足全部要求才持久获章；动画已读稳定ID、Esc关闭及原焦点恢复',async()=>{
  db.prepare("UPDATE works SET review_status='approved' WHERE id=?").run(workId);await go(s,'/me');await s.locator('.next-award').waitFor();assert.match(await dialog(s).innerText(),/恭喜你获得了理论探索徽章！已经佩戴在你的主页啦！快去看看吧~/);const id=await s.locator('.next-award').getAttribute('data-grant-id');assert.equal((await request('student','/rewards/badges')).data.grants[0].id,id);await shot(s,'award-feedback');await s.keyboard.press('Escape');await s.locator('.next-award').waitFor({state:'hidden'});await s.locator('[data-real-grant]').waitFor();await s.reload();await s.locator('[data-real-grant]').waitFor();assert.equal(await s.locator('.next-award').count(),0);await shot(s,'earned-profile');
 });
 await scene('实物演示兑换确认、指定结果文案、余额扣一次和管理员通知',async()=>{
  await s.getByRole('tab',{name:'礼品',exact:true}).click();await s.locator('[data-gift="notebook"]').getByRole('button').click();await b(dialog(s),'演示兑换').click();await dialog(s).getByText('本地演示，不会真实发货，也不代表老师已承诺配送',{exact:false}).waitFor();await b(dialog(s),'确认演示兑换').click();await dialog(s).getByText('兑换成功！老师会在下次课把奖品带给你哦~',{exact:true}).waitFor();await s.getByTestId('reward-balance').filter({hasText:'90'}).waitFor();await shot(s,'physical-success');await s.keyboard.press('Escape');
  const {p}=await make();a=p;await login(a,'adminpbl','admin123');await go(a,'/notifications');const event=db.prepare('SELECT notification_id FROM demo_exchange_events WHERE gift_id=\'notebook\'').get();await go(a,'/notifications/'+event.notification_id);await a.getByText(/本地演示，不代表真实扣款或发货/).waitFor();await shot(a,'admin-exchange-notification');assert.equal(db.prepare("SELECT count(*) n FROM demo_exchange_events WHERE gift_id='notebook'").get().n,1);
 });
 await scene('数字徽章兑换单独标识；另一浏览器可读后端事件但金币仍为本地120',async()=>{
  await s.locator('[data-gift="digital-theory"]').getByRole('button').click();await b(dialog(s),'演示兑换').click();await b(dialog(s),'确认演示兑换').click();await dialog(s).getByText('演示徽章已保存，可以在我的主页查看',{exact:true}).waitFor();await s.keyboard.press('Escape');await s.getByText('演示兑换 · 不是课时通关',{exact:true}).waitFor();await s.getByTestId('reward-balance').filter({hasText:'60'}).waitFor();await shot(s,'digital-badge');
  const {p}=await make();await login(p);await go(p,'/me');await p.locator('[data-real-grant]').waitFor();await p.getByText('演示兑换 · 不是课时通关',{exact:true}).waitFor();await p.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();assert.equal(await p.locator('.next-award').count(),0);await p.close();
 });
 await scene('服务器已写但响应丢失：重试/刷新同编号，只扣一次、只通知一次',async()=>{
  const before=db.prepare('SELECT count(*) n FROM demo_exchange_events').get().n;await s.route('**/api/rewards/exchanges',async r=>{if(r.request().method()==='POST'){await r.fetch();await r.abort();}else await r.continue();});
  await s.locator('[data-gift="digital-glider"]').getByRole('button').click();await b(dialog(s),'演示兑换').click();await b(dialog(s),'确认演示兑换').click();await dialog(s).getByText('演示兑换已记录，消息待同步',{exact:true}).waitFor();await s.getByTestId('reward-balance').filter({hasText:'30'}).waitFor();await shot(s,'pending-response-lost');await s.keyboard.press('Escape');assert.equal(db.prepare('SELECT count(*) n FROM demo_exchange_events').get().n,before+1);
  await s.unroute('**/api/rewards/exchanges');await s.reload();await s.getByText('试飞纪念徽章（演示）',{exact:true}).first().waitFor();await s.getByTestId('reward-balance').filter({hasText:'30'}).waitFor();await s.getByText('演示兑换已记录，消息待同步',{exact:true}).waitFor({state:'hidden'});assert.equal(db.prepare('SELECT count(*) n FROM demo_exchange_events').get().n,before+1);assert.equal(db.prepare("SELECT count(*) n FROM notifications WHERE event_key='demo_exchange'").get().n,before+1);
 });
 await scene('重置保留签到去重与真实徽章，金币不足/库存不足仍解释并禁用',async()=>{
  await b(s,'重置演示数据').click();await b(dialog(s),'确认重置演示数据').click();await b(s,'今日已签到').waitFor();await s.getByTestId('reward-balance').filter({hasText:'120'}).waitFor();assert.equal(db.prepare('SELECT count(*) n FROM student_badge_grants').get().n,1);await s.locator('[data-gift="model"]').getByText(/还差 40/).waitFor();await s.locator('[data-gift="sticker"]').getByText('演示库存不足',{exact:true}).waitFor();
 });
 await scene('维护可编辑名称及受控艺术，已获得快照保持不变',async()=>{
  await go(a,`/courses/${courseId}`);await a.getByRole('tab',{name:'通关徽章配置',exact:true}).click();const card=a.locator('.maintenance-list .ant-card').filter({hasText:'滑翔机试飞理论课'});await card.getByRole('button',{name:'通关徽章配置',exact:true}).click();await dialog(a).getByLabel('徽章展示名称',{exact:true}).fill('合成验收改名');await dialog(a).getByRole('button',{name:'保存徽章配置',exact:true}).click();await dialog(a).getByText('徽章配置已保存',{exact:true}).waitFor();await shot(a,'badge-maintenance');await a.keyboard.press('Escape');assert.equal((await request('student','/rewards/badges')).data.grants[0].name,'理论探索');
 });
 await scene('权限撤回后停止课时入口，历史徽章保留安全快照；恢复正常',async()=>{
  db.prepare("UPDATE courses SET status='draft' WHERE id=?").run(courseId);await go(s,'/me');await s.getByText('历史获得记录；来源已不可访问，无法进入课时',{exact:true}).waitFor();assert.equal(await s.getByRole('link',{name:'查看来源课时',exact:true}).count(),0);assert.equal((await request('student',`/rewards/lessons/${theory}`)).status,404);await shot(s,'historical-withdrawn');db.prepare("UPDATE courses SET status='published' WHERE id=?").run(courseId);await s.reload();await s.getByRole('link',{name:'查看来源课时',exact:true}).waitFor();
 });
 for(const [w,h]of [[1440,900],[768,1024],[390,844],[360,800],[844,390]])await scene(`我的页与奖励反馈 ${w}×${h} 无横溢、键盘关闭和 reduced-motion`,async()=>{
  await s.setViewportSize({width:w,height:h});await go(s,'/me');await s.locator('[data-real-grant]').waitFor();assert.ok(await s.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot(s,`profile-${w}x${h}`);await s.locator('.next-badge-shelf').scrollIntoViewIfNeeded();await shot(s,`badge-shelf-${w}x${h}`);
  db.prepare('UPDATE student_badge_grants SET shown_at=NULL WHERE student_id=4').run();await s.emulateMedia({reducedMotion:'reduce'});await s.evaluate(()=>dispatchEvent(new Event('focus')));await s.locator('.next-award').waitFor();assert.equal(await s.locator('.next-award').evaluate(n=>getComputedStyle(n).animationName),'none');await s.keyboard.press('Tab');assert.ok(await dialog(s).evaluate(n=>n.contains(document.activeElement)));await shot(s,`award-${w}x${h}`);await s.keyboard.press('Escape');await s.locator('.next-award').waitFor({state:'hidden'});await s.emulateMedia({reducedMotion:'no-preference'});
 });
 await scene('服务重启后真实徽章和兑换记录仍一致；参观和未准备第三关无假获得',async()=>{
  const before=(await request('student','/rewards/badges')).data;await stop();await start();const after=(await request('student','/rewards/badges')).data;assert.deepEqual(after.grants,before.grants);assert.deepEqual(after.exchanges,before.exchanges);assert.equal(after.grants.length,1);assert.ok(after.locked.find(l=>l.lessonId===visit).checks.some(c=>c.key==='visit_records'&&!c.satisfied));assert.equal(after.locked.find(l=>l.lessonId===experiment).eligible,false);
 });
 assert.deepEqual(errors,[]);
 }finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({browser:browser.version(),records,pageErrors:errors,courseId,lessonIds:imported.lessonIds,scope:'Isolated synthetic teaching database only. Date rollover is an explicitly intercepted server date DTO; no actual teaching records or server clock changed.'},null,2));await browser.close();db.close();await stop().catch(()=>child?.kill());}
});
