import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';import {chromium} from 'playwright';import {readReviewHtml,applyPageEdits} from '../scripts/page-copy.mjs';import {readCopy} from '../scripts/fortune-copy.mjs';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'docs/real-coins/step-02/copy-browser'),directory=path.join(root,'docs/real-coins/step-02/copy-review'),coverage=JSON.parse(fs.readFileSync(path.join(directory,'coverage.json'))),copy=readCopy(path.join(root,'frontend/src/content/uiCopy.jsx'));fs.mkdirSync(out,{recursive:true});
test('三份增量审阅可双击打开，稳定ID与当前基线一致，原46份仍保留',{timeout:60000},async()=>{
 const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();try{for(const page of coverage.pages){await p.goto('file:///'+path.join(directory,page.title+'.html').replaceAll('\\','/'));assert.equal(await p.locator('[data-copy-id]').count(),page.ids.length);assert.deepEqual(readReviewHtml(path.join(directory,page.title+'.html')).edits,[]);}const old=JSON.parse(fs.readFileSync(path.join(root,'docs/experience-patch/copy-review/coverage.json')));assert.equal(old.pages.length,46);for(const page of old.pages)assert.ok(fs.existsSync(path.join(root,'docs/experience-patch/copy-review',page.html)));await p.goto('file:///'+path.join(directory,'index.html').replaceAll('\\','/'));await p.screenshot({path:path.join(out,'increment-directory.png')});}finally{await b.close();}
});
test('新文案点字、保存重开与变化项导出；脚本文字为纯文本，导入只改受控ID',{timeout:60000},async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pbl-coins-copy-')),b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();try{await p.goto('file:///'+path.join(directory,'真实金币余额与来源明细.html').replaceAll('\\','/'));const text='<script>window.coinCopyInjected=true</script>';await p.locator('[data-copy-id="coins.title"]').fill(text);let download=p.waitForEvent('download');await p.locator('#export').click();const json=path.join(temp,'edit.json');await(await download).saveAs(json);const payload=JSON.parse(fs.readFileSync(json));assert.deepEqual(payload.edits.map(e=>e.id),['coins.title']);const next=applyPageEdits(copy,payload).next;assert.equal(next['coins.title'].text,text);assert.deepEqual(next['fortune.avoid.compare'],copy['fortune.avoid.compare']);download=p.waitForEvent('download');await p.locator('#save').click();const html=path.join(temp,'edit.html');await(await download).saveAs(html);await p.goto('file:///'+html.replaceAll('\\','/'));assert.equal(await p.locator('[data-copy-id="coins.title"]').innerText(),text);assert.equal(await p.evaluate(()=>window.coinCopyInjected),undefined);assert.equal(readReviewHtml(html).edits[0].text,text);await p.screenshot({path:path.join(out,'edited-copy.png')});}finally{await b.close();}
});
test('旧改稿不覆盖新字段，全部旧注册值与30/30运势词库保持',()=>{
 const previous=JSON.parse(execFileSync('git',['show','1d9954d:frontend/src/content/uiCopy.jsx'],{cwd:root,encoding:'utf8'}).split('export const uiCopy = ')[1].trim().replace(/;$/,''));for(const [id,value]of Object.entries(previous))assert.deepEqual(copy[id],value,id);const delta=JSON.parse(fs.readFileSync(path.join(root,'docs/real-coins/step-02/copy-delta.json')));assert.equal(delta.changed.length,0);assert.equal(delta.added.length,42);assert.throws(()=>applyPageEdits(copy,{format:'page-copy-review-v1',edits:[{id:'coins.title',baseText:'旧版不匹配标题',baseEnabled:true,text:'不应覆盖',enabled:true}]}),/基线冲突/);for(const group of['fortune.good.','fortune.avoid.'])assert.equal(Object.keys(copy).filter(k=>k.startsWith(group)).length,30);
});
