import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {setup,login,go,gate,base} from './helpers/step02.fixture.mjs';
import {root} from './v2-fixture.mjs';
const dir=path.join(root,'docs/redesign-v2/step-02/visual-patch'),shots=path.join(dir,'screenshots');
const sizes=[[1440,900],[1920,1080],[768,1024],[390,844],[360,640],[844,390]];
const robot=p=>p.locator('.course-robot'),modal=p=>p.locator('.space-lesson-modal .ant-modal');
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(180);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'横向溢出 '+name);await p.screenshot({path:path.join(shots,name+'.png'),animations:'disabled'});}
async function fortune(p){await p.locator('.fortune-result').waitFor();return p.getByTestId('daily-fortune').innerText();}
async function accountRead(p){return p.evaluate(async()=>{const r=await fetch('/api/account/daily-fortune',{headers:{Authorization:'Bearer '+localStorage.getItem('token')}});return r.json();});}
test('新版第2步补修：真实素材、运势、居中地图与输入交互',{timeout:420000},async t=>{
 mkdirSync(shots,{recursive:true});mkdirSync(path.join(dir,'evidence'),{recursive:true});const f=await setup(),records=[],errors=[];
 const c=await f.browser.newContext({viewport:{width:1440,height:900}}),p=await c.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
 const scenario=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();records.push({name,result:'pass'});}catch(e){failure=e;records.push({name,result:'fail',error:e.message});await shot(p,'failure');throw e;}});if(failure)throw failure;};
 try{
  await scenario('独立桌面/手机登录构图、六尺寸整屏不滚动，短屏表单内部可达',async()=>{
   const loaded=[];p.on('response',r=>{if(r.url().includes('/visual-patch/web/login-'))loaded.push(r.url());});
   for(const[width,height]of sizes){await p.setViewportSize({width,height});await p.goto(base+'/login');await p.locator('.patch-login-scene img').waitFor();await p.waitForFunction(()=>document.querySelector('.patch-login-scene img')?.naturalWidth>0);const mobile=width<=767;assert.match(await p.locator('.patch-login-scene img').evaluate(e=>e.currentSrc),mobile?/login-mobile/:/login-desktop/);assert.ok(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));await shot(p,'login-'+width);}
   await p.setViewportSize({width:390,height:360});await p.getByLabel('密码',{exact:true}).fill('待输入内容。');await p.getByRole('button',{name:'显示密码',exact:true}).click();assert.equal(await p.getByLabel('密码',{exact:true}).getAttribute('type'),'text');await p.getByRole('button',{name:'隐藏密码',exact:true}).click();await p.getByRole('button',{name:'登录',exact:true}).scrollIntoViewIfNeeded();const box=await p.getByRole('button',{name:'登录',exact:true}).boundingBox();assert.ok(box.y>=0&&box.y+box.height<=360);await shot(p,'login-keyboard-height');
   await p.setViewportSize({width:720,height:450});await p.getByRole('button',{name:'登录',exact:true}).scrollIntoViewIfNeeded();await shot(p,'login-200-percent-equivalent');
   assert.ok(loaded.some(url=>url.includes('login-mobile'))&&loaded.some(url=>url.includes('login-desktop')));
  });
  await scenario('登录图片故障不挡表单，真实错误与防重复提交',async()=>{
   await p.route('**/visual-patch/web/login-*.webp',r=>r.abort());await p.goto(base+'/login');await p.locator('.patch-login-scene[data-art-failed]').waitFor();await p.getByLabel('账号',{exact:true}).fill('student_wang');await p.getByLabel('密码',{exact:true}).fill('错误密码');await p.getByRole('button',{name:'登录',exact:true}).click();await p.getByRole('alert').waitFor();await shot(p,'login-image-error');await p.unroute('**/visual-patch/web/login-*.webp');
   const entered=gate(),hold=gate();let writes=0;await p.route('**/api/auth/login',async r=>{writes++;entered.release();await hold.promise;await r.continue();});await p.getByLabel('密码',{exact:true}).fill('student123');await p.getByRole('button',{name:'登录',exact:true}).click();await entered.promise;await p.getByLabel('密码',{exact:true}).press('Enter');assert.equal(writes,1);assert.ok(await p.getByRole('button',{name:'登录',exact:true}).evaluate(e=>e.classList.contains('ant-btn-loading')));await shot(p,'login-loading');hold.release();await p.waitForURL('**/explore');await p.unroute('**/api/auth/login');
  });
  await scenario('六尺寸平台/课程主题，真实运势、地图默认和弹窗、标题透明、封面和聊天',async()=>{
   for(const[width,height]of sizes){await p.setViewportSize({width,height});
    await go(p,'/explore');await p.getByTestId('home-course-card').first().waitFor();assert.match(await p.locator('.space-underlay img').getAttribute('src'),/campus-select/);await shot(p,'selector-'+width);
    await go(p,'/me');await fortune(p);assert.match(await p.locator('.space-underlay img').getAttribute('src'),/campus-personal/);await shot(p,'personal-'+width);
    await go(p,'/courses/9001');await p.locator('.route-node').first().waitFor();assert.equal(await p.getByRole('dialog',{name:'关卡详情',exact:true}).count(),0);assert.equal(await p.locator('.pixel-map-aside,.space-lesson-drawer').count(),0);await shot(p,'map-'+width);
    await p.locator('.route-node').first().locator('.space-place-art').click({position:{x:100,y:55}});await modal(p).waitFor();await p.getByTestId('lesson-details').getByText('科创教室（测试地点）',{exact:true}).waitFor();await shot(p,'detail-'+width);await p.keyboard.press('Escape');await modal(p).waitFor({state:'hidden'});
    await go(p,'/courses/9001/lessons/90011/learn?stage=0');await p.locator('.study-section').first().waitFor();assert.match(await p.locator('.space-underlay img').getAttribute('src'),/voyage-reading/);assert.match(await p.locator('.course-page-heading').evaluate(e=>getComputedStyle(e).backgroundColor),/0\.72/);await shot(p,'learning-'+width);
    await go(p,'/courses/9001/lab');await p.locator('.lab-experiment-cover img').waitFor();assert.match(await p.locator('.space-underlay img').getAttribute('src'),/voyage-lab/);assert.equal(await p.locator('a button').count(),0);if(width<=767){const action=await p.getByRole('link',{name:'开始实验',exact:true}).boundingBox();assert.ok(action.y+action.height<height,'实验首屏按钮可达 '+width);}await shot(p,'lab-'+width);
    const rb=await robot(p).evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,border:s.borderWidth,shadow:s.boxShadow,width:e.clientWidth,height:e.clientHeight};});assert.equal(rb.background,'rgba(0, 0, 0, 0)');assert.equal(rb.border,'0px');assert.equal(rb.shadow,'none');assert.ok(rb.width>=44&&rb.height>=44);await robot(p).click();await p.locator('#assistant-question').waitFor();await shot(p,'chat-'+width);await p.keyboard.press('Escape');
   }
   await go(p,'/courses/9002');await p.locator('.route-node').first().waitFor();assert.match(await p.locator('.space-underlay img').getAttribute('src'),/campus-select/);assert.equal(await p.locator('.course-avatar-button').count(),0);
  });
  await scenario('居中详情焦点/Tab/Escape/遮罩/滚动锁、节点 Enter Space、取消课时与互斥',async()=>{
   await p.setViewportSize({width:1440,height:900});await go(p,'/courses/9001');const node=p.locator('[data-lesson-id="90012"] .route-node');await node.waitFor();await node.focus();await p.keyboard.press('Space');await modal(p).waitFor();assert.equal(await p.getByRole('dialog',{name:'关卡详情',exact:true}).getAttribute('aria-modal'),'true');assert.ok(await robot(p).isDisabled());await modal(p).click({position:{x:100,y:30}});assert.ok(await modal(p).isVisible());
   for(let i=0;i<12;i++)await p.keyboard.press('Tab');assert.ok(await modal(p).evaluate(e=>e.contains(document.activeElement)));await p.keyboard.press('Escape');await modal(p).waitFor({state:'hidden'});await p.waitForFunction(()=>document.querySelector('[data-lesson-id="90012"] .route-node')===document.activeElement);
   await node.click();await modal(p).waitFor();await p.locator('.ant-modal-wrap').click({position:{x:3,y:3}});await modal(p).waitFor({state:'hidden'});
   await node.click();await modal(p).waitFor();const scroll=await p.evaluate(()=>scrollY);assert.equal(await p.evaluate(()=>getComputedStyle(document.body).overflow),'hidden');await p.mouse.move(5,5);await p.mouse.wheel(0,300);await p.waitForTimeout(220);assert.equal(await p.evaluate(()=>scrollY),scroll);await p.keyboard.press('Escape');await modal(p).waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>scrollY),scroll);
   f.db.prepare("UPDATE lessons SET status='cancelled',cancel_reason='隔离测试：本课时取消。' WHERE id=90012").run();await p.reload();await node.click();await p.getByText('隔离测试：本课时取消',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'进入课时',exact:true}).count(),0);await p.keyboard.press('Escape');f.db.prepare("UPDATE lessons SET status='scheduled' WHERE id=90012").run();
   await p.reload();await robot(p).click();await p.locator('#assistant-question').fill('关闭后保留草稿。');await p.locator('.pixel-map-overview').click();assert.equal(await p.locator('#course-chat').isVisible(),false);await robot(p).click();assert.equal(await p.locator('#assistant-question').inputValue(),'关闭后保留草稿。');await p.keyboard.press('Escape');
  });
  await scenario('悬浮/鼠标按下/键盘按下/减少运动，路线锚点固定、输入原值不变',async()=>{
   const node=p.locator('.route-node').first(),pad=node.locator('.space-landing-anchor');await node.scrollIntoViewIfNeeded();const anchor=await pad.boundingBox();await node.hover();await p.waitForTimeout(180);assert.deepEqual(await pad.boundingBox(),anchor);assert.equal(await node.locator('.space-place-visual').evaluate(e=>getComputedStyle(e).scale),'1.025');await shot(p,'interaction-hover');
   await p.mouse.down();await p.waitForTimeout(180);assert.equal(await node.locator('.space-place-visual').evaluate(e=>getComputedStyle(e).scale),'0.98');await shot(p,'interaction-mouse-pressed');await p.mouse.up();await modal(p).waitFor();await p.keyboard.press('Escape');await modal(p).waitFor({state:'hidden'});
   await node.focus();await p.keyboard.down('Space');await p.waitForTimeout(180);assert.equal(await node.getAttribute('data-key-pressed'),'true');await shot(p,'interaction-key-pressed');await p.keyboard.up('Space');await modal(p).waitFor();await p.keyboard.press('Escape');await modal(p).waitFor({state:'hidden'});await node.focus();await shot(p,'interaction-focus');
   await p.emulateMedia({reducedMotion:'reduce'});await node.hover();assert.equal(await node.locator('.space-place-visual').evaluate(e=>getComputedStyle(e).scale),'none');await shot(p,'interaction-reduced-motion');await p.emulateMedia({reducedMotion:'no-preference'});
  });
  await scenario('同账号跨浏览器当天一致，失败重试、不读写奖励存储，切账号迟到响应被丢弃',async()=>{
   await go(p,'/me');await fortune(p);const original=await accountRead(p),storage=await p.evaluate(()=>Object.entries(localStorage).filter(([key])=>key.includes('reward')));
   const another=await f.browser.newContext(),q=await another.newPage();await login(q);await go(q,'/me');await fortune(q);assert.deepEqual(await accountRead(q),original);await another.close();
   await p.route('**/account/daily-fortune',r=>r.fulfill({status:503,json:{error:'隔离测试：暂时失败。'}}));await p.reload();await p.getByRole('alert').filter({hasText:'暂时失败'}).waitFor();assert.equal(await p.locator('.fortune-result').count(),0);await shot(p,'fortune-failed');await p.unroute('**/account/daily-fortune');await p.getByRole('button',{name:'重新读取',exact:true}).click();await fortune(p);assert.deepEqual(await accountRead(p),original);assert.deepEqual(await p.evaluate(()=>Object.entries(localStorage).filter(([key])=>key.includes('reward'))),storage);
   const hold=gate(),entered=gate();let first=true;await p.route('**/account/daily-fortune',async r=>{if(first){first=false;entered.release();await hold.promise;await r.fulfill({status:200,json:{...original,date:'旧账号迟到结果',level:'great'}});}else await r.continue();});await p.reload();await entered.promise;await p.getByRole('button',{name:'退出登录',exact:true}).click();await p.waitForURL('**/login');await login(p,'step02_other');await go(p,'/me');await fortune(p);hold.release();await p.waitForTimeout(200);assert.doesNotMatch(await fortune(p),/旧账号迟到结果/);await p.unroute('**/account/daily-fortune');
  });
  await scenario('API 原文保留、教学显示只去尾句号；输入和机器人失败降级保持可用',async()=>{
   f.db.prepare("UPDATE lessons SET description='先检查条件。然后记录证据。' WHERE id=90011").run();await go(p,'/courses/9001');await p.locator('.route-node').first().click();await p.getByText('先检查条件。然后记录证据',{exact:true}).waitFor();assert.equal(f.db.prepare('SELECT description FROM lessons WHERE id=90011').get().description,'先检查条件。然后记录证据。');await p.keyboard.press('Escape');
   await p.route('**/visual-patch/web/robot-wink-*.webp',r=>r.abort());await p.reload();await robot(p).locator('.pixel-icon').waitFor();await robot(p).click();await p.locator('#assistant-question').fill('输入的原文。第二句。');assert.equal(await p.locator('#assistant-question').inputValue(),'输入的原文。第二句。');await shot(p,'robot-fallback');await p.keyboard.press('Escape');await p.unroute('**/visual-patch/web/robot-wink-*.webp');
   await p.route('**/visual-patch/web/glider-cover-*.webp',r=>r.abort());await go(p,'/courses/9001/lab');await p.locator('.lab-experiment-cover.pixel-image--error').waitFor();await p.getByRole('link',{name:'开始实验',exact:true}).click();await p.waitForURL(/courses\/9001\/glider/);await p.unroute('**/visual-patch/web/glider-cover-*.webp');
  });
  await scenario('定时和重新可见重读运势；触摸按下、长详情、停用和强制改密真实分流',async()=>{
   await p.setViewportSize({width:390,height:844});await go(p,'/me');const real=await accountRead(p);let reads=0;await p.route('**/account/daily-fortune',async route=>{reads++;if(reads===1)await route.fulfill({status:200,json:{...real,date:'定时重读测试',nextUpdateAt:new Date(Date.now()+650).toISOString()}});else await route.continue();});await p.reload();await p.getByTestId('daily-fortune').getByText('定时重读测试',{exact:true}).waitFor();await p.getByTestId('daily-fortune').getByText(real.date,{exact:true}).waitFor();const before=reads;await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await p.waitForFunction(()=>!document.querySelector('[data-testid="daily-fortune"] [role="status"]'));assert.ok(reads>before);await p.unroute('**/account/daily-fortune');
   const touch=await f.browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),q=await touch.newPage();await login(q);await go(q,'/courses/9001');const node=q.locator('.route-node').first();await node.waitFor();await node.scrollIntoViewIfNeeded();const box=await node.boundingBox(),cdp=await touch.newCDPSession(q);assert.equal(await q.evaluate(()=>matchMedia('(hover: none)').matches),true);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+70}]});await q.waitForTimeout(180);assert.equal(await node.locator('.space-place-visual').evaluate(e=>getComputedStyle(e).scale),'0.98');await shot(q,'interaction-touch-pressed');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await modal(q).waitFor();await q.keyboard.press('Escape');
   f.db.prepare('UPDATE lessons SET description=? WHERE id=90011').run('长详情测试：先检查条件。再记录证据。'.repeat(120));await q.reload();await node.click();await modal(q).waitFor();assert.ok(await q.locator('.space-lesson-modal .ant-modal-body').evaluate(e=>e.scrollHeight>e.clientHeight));const enter=await q.getByRole('button',{name:'进入课时',exact:true}).boundingBox();assert.ok(enter.y+enter.height<844);await shot(q,'detail-long-mobile');await q.keyboard.press('Escape');
   f.db.prepare('UPDATE users SET force_reset_password=1 WHERE id=4').run();await q.evaluate(()=>dispatchEvent(new Event('focus')));await q.waitForURL(/change-password/);await shot(q,'forced-password');assert.equal(await robot(q).count(),0);f.db.prepare('UPDATE users SET force_reset_password=0,is_active=0 WHERE id=4').run();await q.reload();await q.waitForURL(/login/);await shot(q,'login-disabled');f.db.prepare('UPDATE users SET is_active=1 WHERE id=4').run();await touch.close();
  });
  assert.deepEqual(errors,[]);
 }finally{
  writeFileSync(path.join(dir,'evidence/visual-browser.json'),JSON.stringify({date:new Date().toISOString(),browser:f.browser.version(),sizes,records,pageErrors:errors,fixture:'isolated synthetic courses 9001/9002; loopback HTTPS assistant provider; not physical-device testing'},null,2));await f.close();
 }
});
