import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import path from 'node:path';
import {setup,login,go,base,api,gate} from './helpers/step02.fixture.mjs';
import {root} from './v2-fixture.mjs';
import {syntheticReplay} from './helpers/syntheticReplay.mjs';
const out=path.join(root,'docs/redesign-v2/step-03/screenshots'),sizes=[[1440,900],[768,1024],[390,844],[360,800],[844,390]];
const b=(p,name)=>p.getByRole('button',{name:new RegExp('(?:^| )'+[...name].map(ch=>ch.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('\\s*')+'$')}),dialog=p=>p.locator('.ant-modal').filter({visible:true});
async function select(p,label,value){await p.getByLabel(label,{exact:true}).click();const owner=typeof p.page==='function'?p.page():p;await owner.locator('.ant-select-dropdown').filter({visible:true}).getByText(value,{exact:true}).click();}
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth+1);await p.screenshot({path:path.join(out,name+'.png'),animations:'disabled'});}
async function write(p,payload){return p.evaluate(async({url,body})=>{const r=await fetch(url,{method:'PUT',headers:{Authorization:'Bearer '+localStorage.getItem('token'),'Content-Type':'application/json'},body:JSON.stringify(body)});return{status:r.status,data:await r.json()};},payload);}
test('第三步真实内容维护→学生读取与上传恢复完整旅程',{timeout:540000},async t=>{
 mkdirSync(out,{recursive:true});const f=await setup(),records=[],errors=[];
 const mc=await f.browser.newContext({viewport:{width:1440,height:900}}),sc=await f.browser.newContext({viewport:{width:1440,height:900}}),m=await mc.newPage(),s=await sc.newPage();m.setDefaultTimeout(12000);s.setDefaultTimeout(12000);
 for(const p of[m,s])p.on('pageerror',e=>errors.push(e.message));m.on('dialog',d=>d.accept());
 let id,l1,l2,cardId,taskId,chapterId,publicId,scopedId,experimentId;const title='内容维护闭环 · 隔离验收课程';
 const scenario=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();records.push({name,result:'pass'});}catch(e){failure=e;records.push({name,result:'fail',error:e.message});console.log('失败页面',m.url(),(await m.locator('body').innerText()).slice(-2400),s.url(),(await s.locator('body').innerText()).slice(-1400));if(await s.locator('video').count()){console.log('视频诊断',await s.locator('video').evaluate(v=>({error:v.error?.code,ready:v.readyState,type:v.currentSrc?new URL(v.currentSrc).pathname:'none'})));const stream=(await s.locator('video').getAttribute('src'));if(stream){const r=await s.request.get(base+stream);console.log('视频请求诊断',r.status(),r.headers()['content-type'],(await r.body()).length);}}await shot(m,'failure-maintenance');await shot(s,'failure-student');throw e;}});if(failure)throw failure;};
 const tab=(p,name)=>p.getByRole('tab',{name,exact:true}).click(),save=p=>b(dialog(p),'保存').click();
 const close=async()=>{await dialog(m).locator('.ant-modal-close').click();await m.locator('.maintenance-editor').waitFor({state:'hidden'});};
 const maintenance=async()=>{await go(m,`/courses/${id}?tab=maintenance`);await m.getByTestId('content-maintenance').waitFor();};
 try{
  await scenario('导师通过页面创建明确主题课程，原入口排课和任务保留',async()=>{
   await login(m,'mentor_zhang','mentor123');await go(m,'/courses/create');await m.getByLabel('课程名称',{exact:true}).fill(title);await m.getByLabel('课程描述',{exact:true}).fill('仅用于隔离端到端验收，不是正式教学内容。');await select(m,'界面主题','星海远航');await select(m,'适用学段','初中');await select(m,'难度等级','基础');await b(m,'创建课程').click();await m.waitForURL('**/courses');
   id=f.db.prepare('SELECT id FROM courses WHERE title=?').get(title).id;assert.notEqual(id,9001);assert.equal(f.db.prepare('SELECT presentation_theme FROM courses WHERE id=?').get(id).presentation_theme,'voyage');await go(m,`/courses/${id}?tab=lessons`);
   for(const name of['观察与比较（验收课时）','整理证据（验收课时）']){await b(m,'添加课时').click();const d=dialog(m);await d.getByLabel('课时名称',{exact:true}).fill(name);await d.getByLabel('描述',{exact:true}).fill('初始说明（合成材料）');await d.getByLabel('时长（分钟）',{exact:true}).fill('45');await d.getByLabel('上课地点',{exact:true}).fill('北航测试教室');await b(d,'确定').click();await d.waitFor({state:'hidden'});}
   [l1,l2]=f.db.prepare('SELECT id FROM lessons WHERE course_id=? ORDER BY sort_order').all(id).map(r=>r.id);
   await b(m,'添加任务').first().click();await dialog(m).getByLabel('任务名称',{exact:true}).fill('自己的试飞证据（验收任务）');await dialog(m).getByLabel('描述',{exact:true}).fill('初始要求');await b(dialog(m),'确定').click();await dialog(m).waitFor({state:'hidden'});taskId=f.db.prepare('SELECT id FROM tasks WHERE lesson_id=?').get(l1).id;
  });
  await scenario('页面填写介绍、章节/排序、课时提示与任务要求，清空说明和读失败保输入',async()=>{
   await maintenance();const ws=m.getByTestId('content-maintenance');await ws.getByLabel('驱动问题',{exact:true}).fill('怎样用自己的证据比较设计（验收问题）？');await ws.getByLabel('所需材料',{exact:true}).fill('记录纸（验收材料）');await b(ws,'保存').click();await ws.getByText('已保存 #'+id,{exact:true}).waitFor();
   await tab(ws,'章节与课时');for(const name of['观察准备（验收章节）','实践整理（验收章节）']){await b(ws,'新增章节').click();await dialog(m).getByLabel('名称',{exact:true}).fill(name);await save(m);await dialog(m).getByText(/已保存 #/).waitFor();await close();}
   chapterId=f.db.prepare('SELECT id FROM course_chapters WHERE course_id=? ORDER BY sort_order').all(id)[0].id;
   await b(ws,'编辑课时说明与归属').first().click();await dialog(m).getByLabel('说明',{exact:true}).fill('记录条件，再比较自己的观察（验收说明）。');await dialog(m).getByLabel('教学提示',{exact:true}).fill('先固定条件，再解释你的证据（验收提示）。');await select(dialog(m),'所属章节','观察准备（验收章节）');await save(m);await dialog(m).getByText(/已保存 #/).waitFor();await close();
   await b(ws,'编辑课时说明与归属').nth(1).click();await select(dialog(m),'所属章节','实践整理（验收章节）');await save(m);await dialog(m).getByText(/已保存 #/).waitFor();await close();await ws.getByLabel('上移 实践整理（验收章节）',{exact:true}).click();await m.waitForFunction(()=>!document.querySelector('.maintenance-workspace button.ant-btn-loading'));assert.equal(f.db.prepare('SELECT title FROM course_chapters WHERE course_id=? ORDER BY sort_order').all(id)[0].title,'实践整理（验收章节）');await ws.getByLabel('下移 实践整理（验收章节）',{exact:true}).click();
   await tab(ws,'任务要求与教学提示');await b(ws,'编辑任务文字').click();await dialog(m).getByLabel('说明',{exact:true}).fill('提交自己的记录与改进理由（验收要求）。');await save(m);await dialog(m).getByText(/已保存 #/).waitFor();await close();
   await tab(ws,'课程介绍与显示');await ws.getByLabel('故事线',{exact:true}).fill('不要丢失的新输入。');await m.route(`**/courses/${id}`,r=>r.request().method()==='PUT'?r.fulfill({status:503,json:{error:'隔离验收：保存失败，输入保留'}}):r.continue());await b(ws,'保存').click();await ws.getByText('隔离验收：保存失败，输入保留',{exact:true}).waitFor();assert.equal(await ws.getByLabel('故事线',{exact:true}).inputValue(),'不要丢失的新输入。');await shot(m,'save-error');await m.unroute(`**/courses/${id}`);await b(ws,'保存').click();await ws.getByText('已保存 #'+id,{exact:true}).waitFor();
   await ws.getByLabel('故事线',{exact:true}).fill('');let failed=false;await m.route(`**/courses/${id}/maintenance`,r=>r.request().method()==='GET'&&!failed?(failed=true,r.fulfill({status:503,json:{error:'隔离验收：列表读取失败'}})):r.continue());await b(ws,'保存').click();await ws.getByText('已保存，列表读取失败；请重新读取，不要重复提交',{exact:true}).waitFor();assert.equal(f.db.prepare('SELECT story_line FROM courses WHERE id=?').get(id).story_line,null);assert.ok(await b(ws,'保存').isDisabled());await shot(m,'saved-read-error');await m.unroute(`**/courses/${id}/maintenance`);await b(ws,'重新读取').first().click();await ws.getByText('隔离验收：列表读取失败',{exact:true}).waitFor({state:'hidden'});
  });
  await scenario('原卡片/练习编辑发布和真实持久化滑翔机关联',async()=>{
   await go(m,`/courses/${id}/lessons/${l1}/content`);await b(m,'新增知识卡片').click();await dialog(m).getByLabel('标题',{exact:true}).fill('比较条件（验收卡片）');await dialog(m).getByLabel('正文',{exact:true}).fill('先记录条件，再开展试飞观察（合成内容）。');await dialog(m).getByLabel('关键要点',{exact:true}).fill('自己的判断需要证据（合成提示）。');await b(dialog(m),'保存并发布').click();await dialog(m).waitFor({state:'hidden'});cardId=f.db.prepare('SELECT id FROM knowledge_cards WHERE lesson_id=?').get(l1).id;
   await b(m,'添加练习').click();await select(dialog(m),'题型','判断题');await dialog(m).getByLabel('题目',{exact:true}).fill('比较前需要记录条件吗（验收题）');await dialog(m).getByLabel('标准答案（多选用英文逗号分隔）',{exact:true}).fill('true');await dialog(m).getByLabel('答案详解',{exact:true}).fill('先记录条件才能比较（合成解释）');await b(dialog(m),'确定').click();await dialog(m).waitFor({state:'hidden'});
   await maintenance();await tab(m,'实验关联');await b(m,'新增滑翔机关联').click();await select(dialog(m),'所属课时','观察与比较（验收课时）');await select(dialog(m),'学习阶段','知识卡片');await select(dialog(m),'知识卡片','比较条件（验收卡片）');await dialog(m).getByLabel('关联入口名称',{exact:true}).fill('证据试飞（验收关联）');await save(m);await dialog(m).getByText(/已保存 #/).waitFor();await close();experimentId=f.db.prepare('SELECT id FROM course_experiments WHERE course_id=?').get(id).id;
  });
  await scenario('公共/课时资料与四种新增格式、混合失败队列、重试不重复成功',async()=>{
   await tab(m,'教学资料与回放');const q=m.getByTestId('upload-resource');await q.locator('input[type=file]').setInputFiles([{name:'公共说明.md',mimeType:'text/markdown',buffer:Buffer.from('# 公共材料\n合成验收资料')},{name:'观察记录.csv',mimeType:'text/csv',buffer:Buffer.from('条件,距离\n相同,12')}]);
   let fail=true;await m.route(`**/courses/${id}/resources`,r=>r.request().postDataBuffer()?.includes(Buffer.from('观察记录.csv'))&&fail?(fail=false,r.fulfill({status:503,json:{error:'隔离验收：第二项上传失败'}})):r.continue());await b(q,'上传待处理文件').click();await q.getByText('隔离验收：第二项上传失败',{exact:true}).waitFor();await q.getByText('上传成功',{exact:true}).waitFor();assert.equal(f.db.prepare('SELECT count(*) n FROM resources WHERE course_id=?').get(id).n,1);await shot(m,'upload-mixed');await m.unroute(`**/courses/${id}/resources`);await b(q,'只重试失败项').click();await q.getByText('上传成功',{exact:true}).nth(1).waitFor();assert.equal(f.db.prepare('SELECT count(*) n FROM resources WHERE course_id=?').get(id).n,2);
   const XLSX=await import('../backend/node_modules/xlsx/xlsx.mjs');const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['观察',12]]),'记录');await q.locator('input[type=file]').setInputFiles(['biff8','xlsx'].map((kind,i)=>({name:i?'记录.xlsx':'记录.xls',mimeType:'application/octet-stream',buffer:Buffer.from(XLSX.write(book,{type:'buffer',bookType:kind}))})));await b(q,'上传待处理文件').click();await q.getByText('上传成功',{exact:true}).nth(3).waitFor();
   await q.getByRole('combobox').first().click();await m.locator('.ant-select-dropdown').filter({visible:true}).getByText('观察与比较（验收课时）',{exact:true}).click();await q.locator('input[type=file]').setInputFiles({name:'本课时资料.txt',mimeType:'text/plain',buffer:Buffer.from('对应当前课时的合成文字资料。')});await b(q,'上传待处理文件').click();await q.getByText('上传成功',{exact:true}).nth(4).waitFor();
   publicId=f.db.prepare("SELECT id FROM resources WHERE course_id=? AND file_name='公共说明.md'").get(id).id;scopedId=f.db.prepare("SELECT id FROM resources WHERE course_id=? AND file_name='本课时资料.txt'").get(id).id;assert.equal(f.db.prepare('SELECT lesson_id FROM resources WHERE id=?').get(scopedId).lesson_id,l1);await m.getByText('格式不支持',{exact:true}).first().waitFor();
  });
  await scenario('页面上传真实可播放回放和私有封面，三尺寸维护/队列/格式矩阵可用',async()=>{
   const video=syntheticReplay();
   const q=m.getByTestId('upload-replay');await q.getByRole('combobox').click();await m.locator('.ant-select-dropdown').filter({visible:true}).getByText('观察与比较（验收课时）',{exact:true}).click();await q.locator('input[type=file]').setInputFiles({name:'课堂回顾.webm',mimeType:'video/webm',buffer:Buffer.from(video)});await b(q,'上传待处理文件').click();await q.getByText('上传成功',{exact:true}).waitFor();
   await tab(m,'课程介绍与显示');const cover=m.getByTestId('upload-cover');await cover.locator('input[type=file]').setInputFiles({name:'验收封面.webp',mimeType:'image/webp',buffer:readFileSync(path.join(root,'frontend/public/assets/redesign-v2/web/campus-960.webp'))});await b(cover,'上传待处理文件').click();await cover.getByText('上传成功',{exact:true}).waitFor();
   for(const[width,height]of sizes){await m.setViewportSize({width,height});await tab(m,'课程介绍与显示');await shot(m,'maintenance-'+width);await tab(m,'章节与课时');await shot(m,'chapters-'+width);await tab(m,'教学资料与回放');await b(m.getByTestId('upload-resource'),'选择文件').scrollIntoViewIfNeeded();await shot(m,'uploads-'+width);await m.locator('.ant-table-wrapper').scrollIntoViewIfNeeded();await shot(m,'formats-'+width);}
   await m.setViewportSize({width:1440,height:900});
  });
  await scenario('原导入学生与发布入口授权；学生真实主题、章节、详情、资料/回放范围',async()=>{
   await go(m,`/courses/${id}?tab=students`);await b(m,'导入学生').click();await dialog(m).getByRole('row').filter({hasText:'王小明'}).getByRole('checkbox').check();await dialog(m).getByRole('button',{name:/导入.*1/}).click();await dialog(m).waitFor({state:'hidden'});await b(m,'发布课程').click();await m.getByText('已发布',{exact:true}).first().waitFor();
   await login(s);await s.getByTestId('home-course-card').filter({hasText:title}).waitFor();await s.getByTestId('home-course-card').filter({hasText:title}).locator('.space-real-cover').waitFor();await s.waitForFunction(()=>[...document.querySelectorAll('.space-real-cover')].some(img=>img.naturalWidth>0));await s.getByTestId('home-course-card').filter({hasText:title}).click();await s.locator('[data-lesson-id="'+l1+'"] .route-node').waitFor();assert.equal(await s.locator('.space-course-navigation').getAttribute('data-course-theme'),'voyage');await s.getByText('观察准备（验收章节）',{exact:false}).first().waitFor();
   await b(s,'课程信息').click();await s.locator('#course-information .ant-collapse-header').click();assert.equal(await s.locator('#course-information').getByText('故事线',{exact:true}).count(),0);await shot(s,'student-cleared-optional');await b(s,'课程信息').click();
   for(const[width,height]of sizes){await s.setViewportSize({width,height});await shot(s,'student-map-'+width);await s.locator('[data-lesson-id="'+l1+'"] .route-node').click();await s.getByTestId('lesson-details').getByText('记录条件，再比较自己的观察（验收说明）',{exact:true}).waitFor();await shot(s,'student-detail-'+width);await s.keyboard.press('Escape');}
   await s.setViewportSize({width:1440,height:900});await go(s,`/courses/${id}/lessons/${l1}/learn`);await s.getByText('先固定条件，再解释你的证据（验收提示）',{exact:true}).waitFor();await s.getByText('本课时资料.txt',{exact:true}).waitFor();await s.getByText('公共说明.md',{exact:true}).waitFor();await s.locator('video').waitFor();await s.waitForFunction(()=>document.querySelector('video')?.readyState>=2);await s.locator('video').evaluate(video=>video.play());await s.waitForFunction(()=>document.querySelector('video')?.currentTime>0&&document.querySelector('video')?.videoWidth===320);await shot(s,'student-replay');
   const download=s.waitForEvent('download');await s.locator('.study-resource').filter({hasText:'公共说明.md'}).getByRole('button',{name:'下载资料',exact:true}).click();assert.equal((await download).suggestedFilename(),'公共说明.md');await go(s,`/courses/${id}/lessons/${l2}/learn`);await s.getByText('公共说明.md',{exact:true}).waitFor();assert.equal(await s.getByText('本课时资料.txt',{exact:true}).count(),0);
  });
  await scenario('课堂回顾→一次练习→指定卡片真实试飞→原卡片返回，解除关联不删试飞',async()=>{
   await go(s,`/courses/${id}/lessons/${l1}/learn`);await b(s,'我已完成课堂回顾').click();await s.getByRole('radio',{name:'正确',exact:true}).check();await b(s,'提交答案').click();await s.getByText('先记录条件才能比较（合成解释）',{exact:false}).first().waitFor();assert.equal(await b(s,'提交答案').isDisabled(),true);assert.equal(f.db.prepare('SELECT count(*) n FROM card_exercise_attempts WHERE student_id=4 AND exercise_id IN (SELECT id FROM card_exercises WHERE card_id=?)').get(cardId).n,1);
   await b(s,'证据试飞（验收关联）').click();await s.waitForURL(/\/glider\?/);await s.getByText('实验环境就绪，可以开始试飞',{exact:true}).waitFor();await b(s,'开始试飞').click();await s.getByText('计算成功',{exact:true}).waitFor({timeout:120000});await s.getByRole('img',{name:'三维航迹',exact:true}).waitFor();await shot(s,'student-flight');const sim=f.db.prepare('SELECT * FROM glider_simulations WHERE course_id=? ORDER BY id DESC').get(id);assert.equal(sim.lesson_id,l1);assert.equal(sim.student_id,4);assert.equal(f.db.prepare('SELECT count(*) n FROM works WHERE task_id=?').get(taskId).n,0);
   await b(s,'返回来源课程').click();await s.waitForURL(`**/learn?stage=1&cardId=${cardId}`);await s.getByRole('heading',{name:'比较条件（验收卡片）',exact:true}).waitFor();await shot(s,'student-return-card');await b(s,'证据试飞（验收关联）').click();await s.getByText('实验环境就绪，可以开始试飞',{exact:true}).waitFor();const result=await m.evaluate(async({id,experimentId})=>{const r=await fetch(`/api/courses/${id}/maintenance/experiments/${experimentId}`,{method:'DELETE',headers:{Authorization:'Bearer '+localStorage.getItem('token')}});return r.status;},{id,experimentId});assert.equal(result,200);await b(s,'返回来源课程').click();await s.waitForURL('**/courses/'+id);await s.getByText('原实验关联已解除或来源已变化，已返回课程地图',{exact:true}).waitFor();assert.equal(f.db.prepare('SELECT count(*) n FROM glider_simulations WHERE course_id=?').get(id).n,1);
  });
  await scenario('主题与章节刷新保报告/助手草稿，报告作品分开提交、原评审/版本/档案',async()=>{
   await go(s,`/courses/${id}/lessons/${l1}/learn?stage=1&cardId=${cardId}`);await b(s,'我已学完本卡片').click();await s.getByLabel('学习总结',{exact:true}).fill('草稿不能因修改主题和章节丢失。');await s.locator('.course-robot').click();await s.locator('#assistant-question').fill('助手输入也要保留。');await s.keyboard.press('Escape');assert.equal((await write(m,{url:`/api/courses/${id}`,body:{presentation_theme:'campus'}})).status,200);assert.equal((await write(m,{url:`/api/courses/${id}/maintenance/chapters/${chapterId}`,body:{title:'观察准备 · 已更新（验收章节）'}})).status,200);await s.evaluate(()=>dispatchEvent(new Event('focus')));await s.locator('.space-course-navigation[data-course-theme=campus]').waitFor();assert.equal(await s.getByLabel('学习总结',{exact:true}).inputValue(),'草稿不能因修改主题和章节丢失。');await s.locator('.course-robot').click();assert.equal(await s.locator('#assistant-question').inputValue(),'助手输入也要保留。');await s.keyboard.press('Escape');
   await s.getByText('结构化反思（必填）',{exact:true}).click();await s.getByLabel('遇到的困难',{exact:true}).fill('整理证据（合成反思）。');await b(s,'提交学习报告与反思').click();await s.getByRole('button',{name:/确\s*定/,exact:true}).click();await s.getByText(/报告正在等待执行导师评审/).waitFor();await s.getByRole('link',{name:'提交作品',exact:true}).click();await s.getByLabel('作品名称',{exact:true}).fill('维护旅程试飞证据（验收作品）');await s.getByLabel('成果文字',{exact:true}).fill('自己的比较记录和改进理由（合成作品）。');await b(s,'提交作品').click();await s.waitForURL('**/lessons/'+l1+'/learn');
   const report=f.db.prepare('SELECT id FROM lesson_learning_reports WHERE lesson_id=?').get(l1);await go(m,'/mentor/reviews/'+report.id);await m.getByLabel('总分',{exact:true}).fill('87');await m.getByLabel('评审意见',{exact:true}).fill('合成验收评审：保留原评分规则');await b(m,'通过报告').click();await b(dialog(m),'确定').click();await m.getByText('报告已通过 · 87 分',{exact:true}).waitFor();assert.equal(f.db.prepare('SELECT score FROM lesson_learning_reports WHERE id=?').get(report.id).score,87);await shot(m,'mentor-original-review');
   const oldWork=f.db.prepare('SELECT id FROM works WHERE task_id=? ORDER BY id').get(taskId);await go(m,'/works/'+oldWork.id);await select(m,'评审结果','需修改');await m.getByLabel('导师评语',{exact:true}).fill('请补充比较依据（合成作品评审）');await m.getByLabel('修改建议',{exact:true}).fill('保留已有记录再改进');await b(m,'保存评审').click();await m.getByText('需修改',{exact:true}).first().waitFor();await go(s,`/courses/${id}/works/${oldWork.id}`);await b(s,'修改后重新提交').click();await s.getByLabel('成果文字',{exact:true}).fill('第二版保留记录并补充比较依据（合成作品）。');await b(s,'提交作品').click();await s.waitForURL('**/lessons/'+l1+'/learn');const version=f.db.prepare('SELECT version,parent_work_id FROM works WHERE task_id=? ORDER BY id DESC').get(taskId);assert.equal(version.version,2);assert.equal(version.parent_work_id,oldWork.id);
   await go(s,`/courses/${id}/archives`);await tab(s,'作品与迭代');await s.getByText('维护旅程试飞证据（验收作品）',{exact:true}).first().waitFor();await shot(s,'student-archive');assert.equal(f.db.prepare('SELECT description FROM tasks WHERE id=?').get(taskId).description,'提交自己的记录与改进理由（验收要求）。');
  });
  await scenario('只读教师/无关导师与失去负责范围：旧表单被拒绝，课程撤回/恢复及时清理',async()=>{
   const tc=await f.browser.newContext(),p=await tc.newPage();await login(p,'teacher_li','teacher123');await go(p,`/courses/${id}?tab=maintenance`);assert.equal(await p.getByTestId('content-maintenance').count(),0);await tc.close();
   await maintenance();await tab(m,'课程介绍与显示');await m.getByTestId('content-maintenance').getByLabel('驱动问题',{exact:true}).fill('不得写入的迟到修改');f.db.prepare('UPDATE courses SET created_by=3 WHERE id=?').run(id);await b(m.getByTestId('content-maintenance'),'保存').click();await m.getByText('课程不存在或已不在负责范围',{exact:true}).waitFor();assert.notEqual(f.db.prepare('SELECT driving_question FROM courses WHERE id=?').get(id).driving_question,'不得写入的迟到修改');await shot(m,'maintenance-permission-lost');f.db.prepare('UPDATE courses SET created_by=2 WHERE id=?').run(id);await b(m,'重新读取').click();await m.getByTestId('content-maintenance').waitFor();
   await go(s,`/courses/${id}`);await s.locator('.route-node').first().waitFor();f.db.prepare("UPDATE courses SET status='draft' WHERE id=?").run(id);await s.evaluate(()=>dispatchEvent(new Event('focus')));await s.getByRole('heading',{name:'当前内容已不可访问',exact:true}).waitFor();assert.equal(await s.locator('.route-node').count(),0);await shot(s,'student-withdrawn');f.db.prepare("UPDATE courses SET status='published' WHERE id=?").run(id);await b(s,'重新检查').click();await s.locator('.route-node').first().waitFor();await shot(s,'student-restored');
  });
  await scenario('队列取消/防双击/成功回读失败，切课不带文件；解析失败只重试索引',async()=>{
   await maintenance();await tab(m,'教学资料与回放');const q=m.getByTestId('upload-resource'),before=f.db.prepare('SELECT count(*) n FROM resources WHERE course_id=?').get(id).n;
   await q.locator('input[type=file]').setInputFiles([{name:'不允许.exe',mimeType:'application/octet-stream',buffer:Buffer.from('invalid')},{name:'取消.txt',mimeType:'text/plain',buffer:Buffer.from('cancelled')}]);await q.getByText('文件类型或大小不符合本入口规则',{exact:false}).first().waitFor();await b(q,'取消待上传文件').click();assert.equal(f.db.prepare('SELECT count(*) n FROM resources WHERE course_id=?').get(id).n,before);
   await q.locator('input[type=file]').setInputFiles({name:'回读失败.txt',mimeType:'text/plain',buffer:Buffer.from('uploaded once only')});const hold=gate(),entered=gate();let writes=0,failRead=true;await m.route(`**/courses/${id}/resources`,async r=>{writes++;entered.release();await hold.promise;await r.continue();});await m.route(`**/courses/${id}/maintenance`,r=>r.request().method()==='GET'&&failRead?(failRead=false,r.fulfill({status:503,json:{error:'隔离验收：上传列表回读失败'}})):r.continue());await b(q,'上传待处理文件').click();await entered.promise;await b(q,'上传待处理文件').evaluate(e=>e.click());assert.equal(writes,1);hold.release();await q.getByText('已上传，列表读取失败；请重新读取，不要重新上传',{exact:true}).waitFor();assert.equal(f.db.prepare("SELECT count(*) n FROM resources WHERE course_id=? AND file_name='回读失败.txt'").get(id).n,1);await shot(m,'uploaded-read-error');await m.unroute(`**/courses/${id}/resources`);await m.unroute(`**/courses/${id}/maintenance`);await b(q,'重新读取').click();await q.getByText('已上传，列表读取失败；请重新读取，不要重新上传',{exact:true}).waitFor({state:'hidden'});
   await q.locator('input[type=file]').setInputFiles({name:'解析失败.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n% deliberately invalid synthetic extraction fixture\n%%EOF')});await b(q,'上传待处理文件').click();await q.getByText('上传成功',{exact:true}).nth(1).waitFor();await go(m,`/courses/${id}/ai-knowledge`);const row=m.getByRole('row').filter({hasText:'解析失败.pdf'});await row.getByText('解析失败',{exact:true}).waitFor();const total=f.db.prepare('SELECT count(*) n FROM resources WHERE course_id=?').get(id).n;await b(row,'重试').click();await row.getByText('解析失败',{exact:true}).waitFor();assert.equal(f.db.prepare('SELECT count(*) n FROM resources WHERE course_id=?').get(id).n,total);await shot(m,'index-failed-retry');
   await maintenance();await tab(m,'教学资料与回放');await m.getByTestId('upload-resource').locator('input[type=file]').setInputFiles({name:'不得带到另一课.md',mimeType:'text/markdown',buffer:Buffer.from('# bound to source course')});let prompts=0;m.on('dialog',()=>prompts++);await m.locator('.course-detail-header a').click();await m.waitForURL('**/courses');assert.ok(prompts>0);await go(m,'/courses/9002?tab=maintenance');await m.locator('[data-testid=content-maintenance][data-course-id="9002"]').waitFor();await tab(m,'教学资料与回放');assert.equal(await m.getByTestId('upload-item').count(),0);assert.equal(f.db.prepare("SELECT count(*) n FROM resources WHERE file_name='不得带到另一课.md'").get().n,0);await shot(m,'queue-course-isolation');
  });
  assert.deepEqual(errors,[]);writeFileSync(path.join(out,'journey.json'),JSON.stringify({base,api,courseId:id,lessonIds:[l1,l2],cardId,taskId,publicId,scopedId,experimentId,records,pageErrors:errors,data:'isolated synthetic course created through real maintenance UI'},null,2));
 }finally{await mc.close();await sc.close();await f.close();}
});
