/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {Alert,Empty,Spin} from 'antd';
import {copyText,copyTemplate} from '../content/copy';
import Sentence from '../content/Sentence';
import {formatBeijingTime} from '../utils/date';
import {PixelButton,PixelPanel} from './visual/PixelUI';
import PixelIcon from './visual/PixelIcon';
import {useRealCoins} from './useRealCoins';
import {calendarDays,shiftMonth} from './coinCalendar';
import './visual/real-coins.css';
const t=id=>copyText('coins.'+id),fmt=(id,slots)=>copyTemplate('coins.'+id,Object.fromEntries(Object.values(slots).map((value,i)=>['slot'+i,value])));
export default function RealCoins(){
 const remote=useRealCoins(),{data,loading,error,request,refresh}=remote;
 const [month,setMonth]=useState(''),[calendar,setCalendar]=useState(null),[calendarError,setCalendarError]=useState(''),[ledger,setLedger]=useState(null),[ledgerError,setLedgerError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[ledgerBusy,setLedgerBusy]=useState(false);const live=useRef(false),lock=useRef(false),ledgerSequence=useRef(0),ledgerLock=useRef(false),serverMonth=useRef('');
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{if(data?.today.date){const next=data.today.date.slice(0,7),previous=serverMonth.current;setMonth(m=>!m||m===previous?next:m);serverMonth.current=next;}},[data?.today.date]);
 useEffect(()=>{if(!month)return;let active=true;setCalendar(null);setCalendarError('');request('/coins/calendar?month='+encodeURIComponent(month)).then(d=>{if(active)setCalendar(d);}).catch(e=>{if(active)setCalendarError(e.response?.data?.error||e.message);});return()=>{active=false;};},[request,month,retry,data]);
 useEffect(()=>{let active=true;const ticket=++ledgerSequence.current;setLedger(null);setLedgerError('');setLedgerBusy(false);ledgerLock.current=false;request('/coins/ledger').then(d=>{if(active&&ticket===ledgerSequence.current)setLedger(d);}).catch(e=>{if(active&&ticket===ledgerSequence.current)setLedgerError(e.response?.data?.error||e.message);});return()=>{active=false;};},[request,retry,data]);
 const more=async()=>{if(ledgerLock.current||!ledger?.nextBefore)return;ledgerLock.current=true;setLedgerBusy(true);setLedgerError('');const ticket=ledgerSequence.current;try{const next=await request('/coins/ledger?before='+ledger.nextBefore);if(live.current&&ticket===ledgerSequence.current)setLedger(s=>({...next,entries:[...s.entries,...next.entries]}));}catch(e){if(live.current&&ticket===ledgerSequence.current)setLedgerError(e.response?.data?.error||e.message);}finally{if(live.current&&ticket===ledgerSequence.current){ledgerLock.current=false;setLedgerBusy(false);}}};
 const checkin=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{const result=await request('/coins/checkin',{});if(!live.current)return;setNotice(fmt(result.created?'success':'already',{amount:result.entry.amount}));await refresh({settle:false});}catch{if(!live.current)return;setNotice(t('uncertain'));const recovered=await refresh({settle:false});if(live.current&&recovered?.today.checked)setNotice(fmt('already',{amount:recovered.today.amount}));}finally{if(live.current){lock.current=false;setBusy(false);setRetry(v=>v+1);}}};
 return <section className="real-coins" aria-label={t('title')}>
  <PixelPanel className="real-coins-summary"><div><h2>{t('title')}</h2><p>{t('accountScope')}</p><div className="real-coin-balance"><PixelIcon name="coin" size={32}/><strong data-testid="real-coin-balance">{data?data.balance:'—'}</strong><span>{t('unit')}</span></div></div><PixelButton onClick={()=>void refresh()} loading={loading}>{t('refresh')}</PixelButton></PixelPanel>
  {loading&&<p role="status"><Spin/>{t('loading')}</p>}{error&&<Alert type="error" title={t('readFailed')} description={error} action={<PixelButton onClick={()=>void refresh()}>{t('retry')}</PixelButton>}/>}
  {remote.settlementError&&<Alert type="warning" title={t('settlementFailed')} description={remote.settlementError}/>}
  <PixelPanel className="real-checkin"><header><div><h2>{t('checkinTitle')}</h2><p>{data?data.today.date:t('serverDate')}</p></div><PixelButton type="primary" onClick={checkin} loading={busy} disabled={!data||busy||data.today.checked}>{t(data?.today.checked?'done':'checkin')}</PixelButton></header>
   {data&&<p data-testid="real-checkin-state">{fmt(data.today.checked?'checkedState':'nextState',{streak:data.today.checked?data.today.streak:data.today.todayStreak,amount:data.today.amount})} · {fmt('total',{count:data.totalCheckins})}</p>}<Sentence>{t('rule')}</Sentence>{notice&&<Alert role="status" type={notice===t('uncertain')?'warning':'info'} title={notice}/>}
   <div className="coin-calendar-toolbar"><PixelButton aria-label={t('previous')} disabled={!month||month<='2000-01'} onClick={()=>setMonth(shiftMonth(month,-1))}>←</PixelButton><h3 aria-live="polite">{month||'—'}</h3><PixelButton aria-label={t('next')} disabled={!month||month>='2099-12'} onClick={()=>setMonth(shiftMonth(month,1))}>→</PixelButton><PixelButton onClick={()=>data&&setMonth(data.today.date.slice(0,7))} disabled={!data}>{t('current')}</PixelButton></div>
   {calendarError?<Alert type="warning" title={t('calendarFailed')} description={calendarError} action={<PixelButton onClick={()=>setRetry(v=>v+1)}>{t('retry')}</PixelButton>}/>:!calendar?<p role="status">{t('calendarLoading')}</p>:<div className="coin-calendar-scroll" tabIndex={0} aria-label={t('calendarLabel')}><div className="coin-calendar" role="group" aria-label={month+' '+t('calendarLabel')}><div className="coin-calendar-week">{t('weekdays').split(' ').map(d=><span key={d}>{d}</span>)}</div><div className="coin-calendar-grid">{calendarDays(month).map((date,i)=>{const record=calendar.records.find(r=>r.checkin_date===date);return <div key={date||'pad'+i} className={'coin-calendar-day'+(record?' is-checked':'')+(date===calendar.today.date?' is-today':'')} data-checkin-date={record?date:undefined} aria-current={date===calendar.today.date?'date':undefined}>{date&&<><time dateTime={date}>{Number(date.slice(-2))}</time>{record?<strong>+{record.amount}</strong>:<span aria-hidden="true">·</span>}</>}</div>;})}</div></div></div>}
   {calendar&&!calendar.records.length&&<p>{t('calendarEmpty')}</p>}
  </PixelPanel>
  <PixelPanel className="real-coin-ledger"><h2>{t('ledgerTitle')}</h2><Sentence>{t('snapshot')}</Sentence>{ledgerError&&<Alert type="warning" title={t('ledgerFailed')} description={ledgerError} action={<PixelButton onClick={()=>setRetry(v=>v+1)}>{t('retry')}</PixelButton>}/>}{!ledger&&!ledgerError?<Spin/>:ledger?.entries.length?<ol>{ledger.entries.map(e=><li key={e.id} data-real-coin-entry={e.id}><div><strong>{e.reward_type==='checkin'?fmt('checkinSource',{date:e.checkin_date}):e.lesson_title}</strong><p>{formatBeijingTime(e.occurred_at)}</p>{e.reward_type==='lesson'?<><p>{fmt('reportSource',{version:e.report_version,score:e.report_score})}</p>{e.accessible?<Link to={`/courses/${e.course_id}/lessons/${e.lesson_id}/learn`}>{t('lesson')}</Link>:<p>{t('history')}</p>}</>:<p>{fmt('streakSource',{streak:e.snapshot.streak})}</p>}</div><strong className="real-coin-amount">+{e.amount}</strong></li>)}</ol>:!ledgerError&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t('ledgerEmpty')}/>}{ledger?.nextBefore&&<PixelButton onClick={more} loading={ledgerBusy}>{t('more')}</PixelButton>}</PixelPanel>
  {!!remote.pending.length&&<details className="real-coin-pending"><summary>{t('pending')}</summary>{remote.pending.map(l=><div key={l.lessonId}><strong>{l.lessonTitle}</strong><ul>{l.checks.map(c=><li key={c.key}>{c.reason}</li>)}</ul></div>)}</details>}
 </section>;
}
