// Actual App.jsx views. Shared routes are listed on the same page; StudentView
// variants have separate entries. IDs and URLs are context, never editable copy.
const all=['admin','academic_mentor','teacher','student','media'];
const staff=['admin','academic_mentor'];
const page=(id,title,routes,roles,sources,groups=[])=>({id,title,routes,roles,sources:sources.map(s=>'frontend/src/'+s),groups});
export const reviewPages=[
 page('login','登录',['/login'],all,['pages/auth/Login.jsx']),
 page('password','修改密码',['/change-password'],all,['pages/auth/ChangePassword.jsx']),
 page('explore','课程选择',['/explore','/courses','/dashboard'],['student'],['student/Explore.jsx'],['平台','platform']),
 page('personal','我的、签到与兑换',['/me','/archives/rewards'],['student'],['student/space/Personal.jsx'],['me','avatar','角色头像','平台我的 / 运势','签到徽章兑换']),
 page('badge-room','徽章陈列室',['/me/badges'],['student'],['student/space/BadgeRoom.jsx'],['徽章陈列室']),
 page('map','课程地图与关卡详情',['/courses/:id'],['student'],['student/Explore.jsx'],['map','课程地图','课程','视觉补修']),
 page('learn','课时学习：回顾、卡片、练习、报告、反思',['/courses/:courseId/lessons/:lessonId/learn'],['student'],['pages/learning/LessonLearn.jsx'],['learning','学习报告','维护填写 / 报告 / 反思']),
 page('course-learning','课程学习兼容页',['/courses/:id/learn'],['student'],['pages/courses/Learning.jsx']),
 page('lab','实验室',['/courses/:courseId/lab'],['student'],['student/Lab.jsx'],['lab','课程实验']),
 page('flight','滑翔机试飞与结果',['/courses/:courseId/glider','/glider'],['student','admin','academic_mentor'],['pages/glider/Simulator.jsx'],['flight']),
 page('tasks','课后任务',['/courses/:courseId/tasks','/tasks'],['student',...staff],['pages/tasks/List.jsx'],['tasks']),
 page('task-detail','任务详情',['/courses/:courseId/tasks/:id','/tasks/:id'],['student',...staff],['pages/tasks/Detail.jsx']),
 page('works','作品列表',['/courses/:courseId/works','/works'],['student',...staff],['pages/works/List.jsx'],['works']),
 page('work-upload','作品提交与版本更新',['/courses/:courseId/works/upload','/works/upload'],['student'],['pages/works/Upload.jsx'],['workUpload']),
 page('work-detail','作品详情、版本与评审',['/courses/:courseId/works/:id','/works/:id'],['student',...staff],['pages/works/Detail.jsx'],['workDetail']),
 page('archive','成长档案、报告与实验记录',['/courses/:courseId/archives','/archives'],['student',...staff,'teacher'],['pages/archives/Index.jsx'],['archive','reports','records']),
 page('reflection','课程反思',['/courses/:courseId/reflection','/archives/reflection'],['student'],['pages/archives/Reflection.jsx'],['reflection']),
 page('assistant','灵境小智',['/courses/:courseId/assistant','/dashboard/ai'],['student',...staff],['pages/dashboard/AI.jsx'],['机器人','robot','assistant']),
 page('compat','旧入口与独立工具',['/lab','/glider','/dashboard/ai','/works','/tasks','/archives'],['student'],['student/space/LegacyEntry.jsx']),
 page('dashboard','管理、导师和新媒体工作台',['/dashboard'],[...staff,'media'],['pages/dashboard/Index.jsx']),
 page('school','学校详情',['/dashboard/schools/:id'],['admin'],['pages/dashboard/School.jsx']),
 page('ai-settings','助手设置',['/dashboard/ai/settings'],['admin'],['pages/dashboard/AISettings.jsx']),
 page('course-list','管理端课程列表',['/courses'],[...staff,'media'],['pages/courses/List.jsx']),
 page('course-create','创建课程',['/courses/create'],staff,['pages/courses/Form.jsx']),
 page('course-edit','编辑课程',['/courses/:id/edit'],staff,['pages/courses/Form.jsx']),
 page('course-detail','课程配置、成员、课时、资源与回放',['/courses/:id'],staff,['pages/courses/Detail.jsx'],['课程内容维护','下一版第一步','维护端 / 开放反思']),
 page('teaching-preview','教学文字可视化维护（课程内页签）',['/courses/:id'],staff,['pages/courses/TeachingPreview.jsx','pages/courses/maintenanceForms.jsx'],['课程内容维护','维护端 / 开放反思']),
 page('ai-knowledge','课程助手知识库',['/courses/:courseId/ai-knowledge'],staff,['pages/courses/AIKnowledge.jsx']),
 page('content-hub','教学内容编排',['/mentor/content'],staff,['pages/mentor/ContentHub.jsx']),
 page('content-editor','知识卡片与习题维护',['/courses/:courseId/lessons/:lessonId/content'],staff,['pages/mentor/LessonContentEditor.jsx']),
 page('review-list','导师评审队列',['/mentor/reviews'],staff,['pages/mentor/ReviewList.jsx'],['review']),
 page('review-detail','报告评审详情',['/mentor/reviews/:reportId'],staff,['pages/mentor/ReviewDetail.jsx']),
 page('students','用户管理、导入、重置密码',['/students'],staff,['pages/students/List.jsx']),
 page('student-detail','学生详情与课程关联',['/students/:id'],staff,['pages/students/Detail.jsx']),
 page('observer','教师观察工作台',['/observer'],['teacher','admin'],['pages/observer/Dashboard.jsx']),
 page('observer-students','教师负责学生',['/observer/students'],['teacher','admin'],['pages/observer/StudentList.jsx']),
 page('observer-detail','只读学情详情',['/observer/students/:studentId'],['teacher','admin'],['pages/observer/StudentDetail.jsx']),
 page('feedback','我的反馈与筛选',['/feedback'],all,['pages/feedback/List.jsx']),
 page('feedback-new','提交反馈',['/feedback/new'],all,['pages/feedback/Form.jsx']),
 page('feedback-detail','反馈详情、附件、回复与关闭',['/feedback/:id'],all,['pages/feedback/Detail.jsx']),
 page('feedback-manage','管理反馈',['/feedback/manage'],['admin'],['pages/feedback/Manage.jsx']),
 page('notifications','通知列表与筛选',['/notifications'],all,['pages/notifications/List.jsx']),
 page('notification-detail','通知详情与跳转',['/notifications/:id'],all,['pages/notifications/Detail.jsx']),
 page('not-found','地址不存在与角色拦截',['/*'],all,['components/NotFound.jsx','components/RoleGuard.jsx']),
 page('shared','公共导航、加载、错误、空状态与伙伴',['所有已登录页面'],all,['components/AppLayout.jsx','components/Header.jsx','components/Sidebar.jsx','components/PageStatus.jsx','student/visual/StudentShell.jsx','student/visual/Partner.jsx'],['shell','平台']),
 page('real-coins','真实金币、连签与日历',['/me'],['student'],['student/RealCoins.jsx','student/visual/StudentShell.jsx'],['平台我的 / 真实金币']),
 page('fortune','今日运势全部词库',['/me'],['student'],['student/space/DailyFortune.jsx'],['平台我的 / 运势']),
 page('copy-review','系统文案审阅',['/copy-review'],['admin'],['copy-review/CopyReview.jsx']),
];
