import {copyText as siteText} from "../../content/copy";
import {useEffect,useState} from 'react';
import {Alert,Button,Card,Form,Input,Modal,Select} from 'antd';
import client from '../../api/client';
import {BadgeArt} from '../../student/ServerRewards';
import {copyText} from '../../content/copy';
export default function BadgeMaintenance({courseId,lessons,disabled}){
 const [definitions,setDefinitions]=useState([]),[editor,setEditor]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const read=async()=>{try{const result=await client.get(`/courses/${courseId}/maintenance/badges`,{silent:true});setDefinitions(result.definitions);setError('');}catch(e){setError(e.response?.data?.error||e.message);}};
 useEffect(()=>{let active=true;client.get(`/courses/${courseId}/maintenance/badges`,{silent:true}).then(r=>{if(active)setDefinitions(r.definitions);}).catch(e=>{if(active)setError(e.response?.data?.error||e.message);});return()=>{active=false;};},[courseId]);
 const save=async values=>{setBusy(true);setError('');try{await client.put(`/courses/${courseId}/maintenance/badges/${editor.id}`,values,{silent:true});setSaved(true);await read();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}};
 return <section><h3>{copyText('next3.maintenance.title')}</h3><p>{copyText('next3.maintenance.scope')}</p>{error&&<Alert type="warning" title={error} action={<Button onClick={read}>{copyText('next3.retry')}</Button>}/>}<div className="maintenance-list">{lessons.map(l=>{const d=definitions.find(d=>d.lesson_id===l.id);return <Card key={l.id} title={l.title} size="small">{d&&<><BadgeArt art={d.art_id} size={64}/><strong>{d.name}</strong><p>{d.description}</p></>}<Button disabled={disabled||l.status==='cancelled'} onClick={()=>{setEditor({id:l.id,title:l.title,name:d?.name||'',description:d?.description||'',artId:d?.art_id||'theory'});setSaved(false);}}>{copyText('next3.maintenance.title')}</Button></Card>;})}</div>
 <Modal open={!!editor} title={editor?.title} onCancel={()=>{if(!busy)setEditor(null);}} footer={null} destroyOnHidden><Form key={editor?.id} layout="vertical" initialValues={editor} onFinish={save} onValuesChange={()=>setSaved(false)} disabled={busy}><Form.Item name="name" label={copyText('next3.maintenance.name')} rules={[{required:true,max:60}]}><Input maxLength={60}/></Form.Item><Form.Item name="artId" label={copyText('next3.maintenance.art')} rules={[{required:true}]}><Select options={[{value:'vr',label:siteText("site.f72e3361d5882e5a")},{value:'theory',label:siteText("site.7d67044ca76b6ff1")},{value:'glider',label:siteText("site.3b1078a2bffe0f9f")}]}/></Form.Item><Form.Item name="description" label={copyText('next3.maintenance.description')}><Input.TextArea maxLength={500}/></Form.Item>{saved&&<Alert type="success" title={copyText('next3.maintenance.saved')}/>}<Button htmlType="submit" type="primary" loading={busy} disabled={saved}>{copyText('next3.maintenance.save')}</Button></Form></Modal></section>;
}
