/* eslint-disable react-hooks/set-state-in-effect */
import {useState,useEffect,useCallback,useRef} from 'react';
import {Link} from 'react-router-dom';
import {Alert,Button,Card,Form,Input,Select,Switch,Tabs,Modal,Space,Table,Tag,Popconfirm} from 'antd';
import {courseAPI} from '../../api';
import {maintenanceAPI as api} from './maintenanceApi';
import {maintenanceText as c} from './maintenanceCopy';
import Sentence from '../../content/Sentence';
import {copyText} from '../../content/copy';
import {requestError} from '../../utils/requestError';
import UploadQueue from './UploadQueue';
import './maintenance.css';
function useWrite(refresh){
 const live=useRef(true),busy=useRef(false),[state,setState]=useState({busy:false,saved:false,error:'',id:null});
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const write=async(fn,after)=>{
  if(busy.current)return false;busy.current=true;setState({busy:true,saved:false,error:'',id:null});let result;
  try{result=await fn();if(!live.current)return false;setState({busy:true,saved:true,error:'',id:result.id??null});after?.(result);await refresh();if(live.current)setState({busy:false,saved:true,error:'',id:result.id??null});return true;}
  catch(error){if(!result&&[403,404].includes(error.response?.status))await refresh().catch(()=>{});if(live.current)setState({busy:false,saved:Boolean(result),id:result?.id??null,error:result?c('readFailed'):requestError(error)});return false;}
  finally{busy.current=false;}
 };
 const reread=async()=>{await refresh();if(live.current)setState(s=>s.saved?{...s,error:''}:s);};
 return{state,write,reread,changed:()=>setState(s=>({...s,saved:false,error:''}))};
}
function WriteNotice({state,refresh}){return state.error?<Alert type={state.saved?'warning':'error'} showIcon title={state.error} description={state.id!=null?`${c('upload.id')} #${state.id}`:undefined} action={state.saved?<Button onClick={()=>void refresh().catch(()=>{})}>{c('retryRead')}</Button>:null}/>:state.saved?<Alert type="success" title={`${c('saved')}${state.id!=null?' #'+state.id:''}`} showIcon/>:null;}
function Field({name,max=10000,required=false,children,help}){return <Form.Item name={name} label={c('field.'+name)} extra={help||(!required?c('optional'):undefined)} rules={required?[{required:true,whitespace:true,message:c('required')},{max,message:c('required')}]:[{max}]}>{children||<Input.TextArea rows={name==='title'?1:3} maxLength={max} showCount/>}</Form.Item>;}
function Intro({id,data,refresh,dirty,archived,policy}){
 const[form]=Form.useForm(),w=useWrite(refresh);
 useEffect(()=>{if(data.cover_image?.startsWith('/api/courses/')&&!form.isFieldTouched('cover_image'))form.setFieldValue('cover_image','__private__');},[data.cover_image,form]);
 return <Card><Form name={'course-intro-'+id} form={form} layout="vertical" disabled={w.state.busy||archived} initialValues={{...data,cover_image:data.cover_image?.startsWith('/api/courses/')?'__private__':data.cover_image||''}} onValuesChange={()=>{dirty('intro',true);w.changed();}} onFinish={values=>{const payload={...values};if(payload.cover_image==='__private__'||payload.cover_image===data.cover_image)delete payload.cover_image;void w.write(()=>courseAPI.update(id,payload).then(r=>({...r,id:Number(id)})),()=>dirty('intro',false));}}>
  <div className="maintenance-fields"><Field name="title" max={120} required/><Field name="theme" max={120}/><Field name="presentation_theme" help={c('purpose')}><Select options={['campus','voyage'].map(value=>({value,label:c('theme.'+value)}))}/></Field><Field name="cover_image"><Select options={[['',c('cover.none')],['/assets/redesign-v2/web/campus-960.webp',c('cover.campus')],['/assets/redesign-v2/web/cosmos-960.webp',c('cover.voyage')],...(data.cover_image?.startsWith('/api/courses/')?[['__private__',c('cover.uploaded')]]:[])].map(([value,label])=>({value,label}))}/></Field></div>
  {['description','driving_question','story_line','materials_needed'].map(name=><Field key={name} name={name} max={name==='driving_question'?1000:10000}/>)}
  <WriteNotice state={w.state} refresh={w.reread}/><Button type="primary" htmlType="submit" loading={w.state.busy} disabled={w.state.saved||archived}>{c('save')}</Button>
 </Form><UploadQueue courseId={id} lessons={[]} policy={policy} kind="cover" disabled={archived} refresh={refresh} dirty={value=>dirty('cover',value)}/></Card>;
}
export default function ContentMaintenance({id}){
 const[data,setData]=useState(null),[policy,setPolicy]=useState(null),[error,setError]=useState(''),[reading,setReading]=useState(false),[editor,setEditor]=useState(null),[tab,setTab]=useState('intro');
 const live=useRef(true),revision=useRef(0),unsaved=useRef(new Set());
 const dirty=useCallback((key,value)=>{if(value)unsaved.current.add(key);else unsaved.current.delete(key);},[]);
 const refresh=useCallback(async()=>{const ticket=++revision.current;setReading(true);try{const[next,p]=await Promise.all([api.read(id),api.formats()]);if(live.current&&ticket===revision.current){setData(next);setPolicy(p);setError('');}return next;}catch(e){if(live.current&&ticket===revision.current){setError(requestError(e));if([403,404].includes(e.response?.status))setData(null);}throw e;}finally{if(live.current&&ticket===revision.current)setReading(false);}},[id]);
 // revision is a request counter, never a DOM ref; cleanup invalidates late responses.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{live.current=true;void refresh().catch(()=>{});return()=>{live.current=false;revision.current++;};},[refresh]);
 useEffect(()=>{const unload=e=>{if(unsaved.current.size){e.preventDefault();e.returnValue='';}};const link=e=>{if(!unsaved.current.size)return;const a=e.target.closest?.('a[href]');if(a&&a.getAttribute('href')?.startsWith('/')&&!window.confirm(c('discard'))){e.preventDefault();e.stopImmediatePropagation();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',link,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',link,true);};},[]);
 const w=useWrite(refresh),open=next=>{if(unsaved.current.has('editor')&&!window.confirm(c('discard')))return;dirty('editor',false);w.changed();setEditor(next);};
 const close=()=>open(null);
 if(!data)return <Card aria-busy={reading}><Alert type={error?'error':'info'} title={error||c('saving')} action={<Button loading={reading} onClick={()=>void refresh().catch(()=>{})}>{c('retryRead')}</Button>}/></Card>;
 const archived=data.course.status==='archived',lessonOptions=[{value:null,label:c('public')},...data.lessons.map(l=>({value:l.id,label:l.title,disabled:l.status==='cancelled'}))];
 const edit=(type,row)=>open({type,row:row||{},id:row?.id,formKey:type+':'+(row?.id||'new')});
 const save=values=>{
  const e=editor;let fn;
  if(e.type==='chapter')fn=()=>e.id?api.save(id,'/chapters/'+e.id,values):api.create(id,'/chapters',values);
  if(e.type==='lesson')fn=()=>api.save(id,'/lessons/'+e.id,{...values,chapter_id:values.chapter_id??null});
  if(e.type==='plan')fn=()=>api.save(id,'/plan',{nodes:data.planNodes.map(n=>({position:n.position,lessonId:n.id===e.id?(values.lessonId??null):n.lesson_id}))});
  if(e.type==='task')fn=()=>api.save(id,'/tasks/'+e.id,values);
  if(e.type==='resource')fn=()=>api.save(id,'/resources/'+e.id,{...values,lesson_id:values.lesson_id??null});
  if(e.type==='replay')fn=()=>api.save(id,'/replays/'+e.id,{...values,lesson_id:values.lesson_id??null});
  if(e.type==='experiment'){const payload={...values,experiment:'glider',lessonId:values.lessonId??null,stage:values.stage??null,cardId:values.cardId??null};fn=()=>e.id?api.save(id,'/experiments/'+e.id,payload):api.create(id,'/experiments',payload);}
  // Adopt the server identity before rereading; a read failure cannot undo creation.
  // Keep this form mounted so its current values survive the new -> saved transition.
  void w.write(fn,result=>{dirty('editor',false);if(!e.id&&result.id!=null)setEditor(current=>current===e?{...current,id:result.id}:current);});
 };
 const move=(index,delta)=>{const ids=data.chapters.map(r=>r.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void w.write(()=>api.save(id,'/chapters/order',{ids}));};
 const lessonList=<div className="maintenance-list">{data.lessons.map(l=><Card key={l.id} size="small" title={l.title} extra={<Tag>{data.chapters.find(ch=>ch.id===l.chapter_id)?.title||c('unassigned')}</Tag>}><Sentence>{l.description}</Sentence>{l.teaching_tip&&<Sentence>{l.teaching_tip}</Sentence>}<Space wrap><Button disabled={archived||l.status==='cancelled'} onClick={()=>edit('lesson',l)}>{c('lessonEdit')}</Button><Link to={`/courses/${id}/lessons/${l.id}/content`}>{c('cardsEdit')}</Link></Space></Card>)}</div>;
 const planPage=<><p>{copyText('next.maintenance.planHelp')}</p><div className="maintenance-list">{(data.planNodes||[]).map(n=><Card key={n.id} title={copyText('next.map.node')+' '+n.position}><Sentence>{data.lessons.find(l=>l.id===n.lesson_id)?.title||copyText('next.map.notOpen')}</Sentence><Button disabled={archived||w.state.busy} onClick={()=>edit('plan',{...n,lessonId:n.lesson_id})}>{c('edit')}</Button></Card>)}</div>{lessonList}</>;
 const chapterPage=<><Button onClick={()=>edit('chapter')} disabled={archived}>{c('newChapter')}</Button><div className="maintenance-list">{data.chapters.map((row,index)=><Card key={row.id} size="small" title={row.title}><Space wrap><Button onClick={()=>edit('chapter',row)} disabled={archived}>{c('edit')}</Button><Button aria-label={c('moveUp')+' '+row.title} disabled={archived||w.state.busy||index===0} onClick={()=>move(index,-1)}>{c('moveUp')}</Button><Button aria-label={c('moveDown')+' '+row.title} disabled={archived||w.state.busy||index===data.chapters.length-1} onClick={()=>move(index,1)}>{c('moveDown')}</Button><Popconfirm title={c('chapterDelete')} onConfirm={()=>w.write(()=>api.remove(id,'/chapters/'+row.id))}><Button danger disabled={archived||w.state.busy}>{c('remove')}</Button></Popconfirm></Space></Card>)}</div>{lessonList}</>;
 const taskPage=<><Sentence>{c('originalTasks')}</Sentence><div className="maintenance-list">{data.tasks.map(t=><Card key={t.id} size="small" title={t.title}><Tag>{data.lessons.find(l=>l.id===t.lesson_id)?.title}</Tag><Sentence>{t.description}</Sentence><Button disabled={archived||t.status!=='active'||data.lessons.find(l=>l.id===t.lesson_id)?.status==='cancelled'} onClick={()=>edit('task',t)}>{c('tasksEdit')}</Button></Card>)}</div>{!data.tasks.length&&<Sentence>{c('noTasks')}</Sentence>}{lessonList}</>;
 const experiments=<><Sentence>{c('experimentNote')}</Sentence><Button disabled={archived} onClick={()=>edit('experiment')}>{c('addExperiment')}</Button><div className="maintenance-list">{data.experiments.map(e=><Card key={e.id} size="small" title={e.label}><Sentence>{data.lessons.find(l=>l.id===e.lessonId)?.title||c('free')}{e.cardId?' · '+data.cards.find(card=>card.id===e.cardId)?.title:''}</Sentence><Space><Button disabled={archived} onClick={()=>edit('experiment',e)}>{c('edit')}</Button><Popconfirm title={c('confirmRemove')} onConfirm={()=>w.write(()=>api.remove(id,'/experiments/'+e.id))}><Button disabled={archived||w.state.busy} danger>{c('remove')}</Button></Popconfirm></Space></Card>)}</div></>;
 const download=async row=>{try{const blob=await api.download(id,row.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=row.file_name||row.title;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(requestError(e));}};
 const resources=<><UploadQueue courseId={id} lessons={data.lessons} policy={policy} kind="resource" refresh={refresh} dirty={value=>dirty('queue',value)} disabled={archived}/><UploadQueue courseId={id} lessons={data.lessons} policy={policy} kind="replay" refresh={refresh} dirty={value=>dirty('video',value)} disabled={archived}/><div className="maintenance-list">{data.resources.map(r=><Card key={r.id} size="small" title={r.title}><Tag>{data.lessons.find(l=>l.id===r.lesson_id)?.title||c('public')}</Tag><Tag>{c('type.'+r.resource_type)}</Tag><Sentence>{r.file_name} · {r.file_type?.toUpperCase()} · {r.file_size} B</Sentence>{r.description&&<Sentence>{r.description}</Sentence>}<Tag>{c('index.'+(r.ai_status||'not_added'))}</Tag>{r.ai_error&&<Sentence>{r.ai_error}</Sentence>}<Space wrap><Button onClick={()=>void download(r)}>{c('upload.download')}</Button><Button disabled={archived} onClick={()=>edit('resource',r)}>{c('upload.edit')}</Button><Popconfirm title={c('remove')} onConfirm={()=>w.write(()=>api.remove(id,'/resources/'+r.id))}><Button disabled={archived||w.state.busy} danger>{c('remove')}</Button></Popconfirm></Space></Card>)}{data.replays.map(r=><Card key={'video'+r.id} title={r.title} size="small"><Tag>{c('upload.replay')} · {data.lessons.find(l=>l.id===r.lesson_id)?.title||c('public')}</Tag><Button disabled={archived} onClick={()=>edit('replay',r)}>{c('upload.edit')}</Button></Card>)}</div><Link to={`/courses/${id}/ai-knowledge`}>{c('upload.index')}</Link><Sentence>{c('upload.parseNote')}</Sentence><h3>{c('upload.formatTitle')}</h3><Table size="small" rowKey="ext" pagination={false} scroll={{x:620}} dataSource={policy?.formats||[]} columns={[{title:c('upload.mime'),dataIndex:'ext'},{title:c('upload.max'),render:(_,row)=>row.limitMB+' MB'},{title:c('upload.scope'),render:()=>c('upload.resourceNote')},{title:c('upload.preview'),dataIndex:'preview'},{title:c('upload.ai'),dataIndex:'ai'}]}/></>;
 return <section className="maintenance-workspace" data-testid="content-maintenance" data-course-id={id}><header><h2>{c('title')}</h2><Sentence>{c('purpose')}</Sentence><Button loading={reading} onClick={()=>void refresh().catch(()=>{})}>{c('retryRead')}</Button></header>{error&&<Alert type="warning" title={error}/>} {archived&&<Alert type="warning" title={c('archived')}/>}<WriteNotice state={w.state} refresh={w.reread}/><Tabs activeKey={tab} onChange={setTab} destroyOnHidden={false} items={[{key:'intro',label:c('intro'),children:<Intro id={id} data={data.course} refresh={refresh} dirty={dirty} archived={archived} policy={policy}/>},{key:'chapters',label:data.course.map_mode==='plan'?copyText('next.maintenance.plan'):c('chapters'),children:data.course.map_mode==='plan'?planPage:chapterPage},{key:'tasks',label:c('tasks'),children:taskPage},{key:'resources',label:c('resources'),children:resources},{key:'experiments',label:c('experiments'),children:experiments}]}/>
 <Modal open={Boolean(editor)} title={editor?c(editor.type==='experiment'?'experiments':editor.type==='task'?'tasksEdit':editor.type==='lesson'?'lessonEdit':'edit'):''} onCancel={close} footer={null} destroyOnHidden width={680} className="maintenance-editor"><Editor key={editor?.formKey} editor={editor} data={data} options={lessonOptions} save={save} state={w.state} refresh={w.reread} dirty={()=>{dirty('editor',true);w.changed();}}/></Modal>
 </section>;
}
function Editor({editor:e,data,options,save,state,refresh,dirty}){
 const[form]=Form.useForm();if(!e)return null;
 const initial={...e.row,enabled:e.row.enabled??true};
 return <Form name={'maint-'+e.type+'-'+(e.id||'new')} form={form} layout="vertical" initialValues={initial} onValuesChange={dirty} onFinish={save} disabled={state.busy}>
  {e.type==='plan'?<Form.Item name="lessonId" label={copyText('next.maintenance.link')}><Select allowClear options={options.filter(o=>o.value&&!data.planNodes.some(n=>n.id!==e.id&&n.lesson_id===o.value))}/></Form.Item>:e.type==='experiment'?<><Form.Item name="lessonId" label={c('field.lesson_id')}><Select allowClear options={[{value:null,label:c('free')},...options.filter(o=>o.value)]} onChange={()=>form.setFieldsValue({stage:null,cardId:null})}/></Form.Item><Form.Item noStyle shouldUpdate>{()=>{const lessonId=form.getFieldValue('lessonId');return <><Form.Item name="stage" label={c('field.stage')}><Select allowClear disabled={!lessonId} options={[0,1,2,3].map(value=>({value,label:c('stage.'+value)}))} onChange={()=>form.setFieldValue('cardId',null)}/></Form.Item><Form.Item name="cardId" label={c('field.cardId')}><Select allowClear disabled={!lessonId||form.getFieldValue('stage')!==1} options={data.cards.filter(card=>card.lesson_id===lessonId).map(card=>({value:card.id,label:card.title}))}/></Form.Item></>;}}</Form.Item><Field name="label" max={120} required/><Form.Item name="enabled" valuePropName="checked" label={c('field.enabled')}><Switch/></Form.Item></>:<><Field name="title" max={120} required/>{e.type!=='chapter'&&<Field name="description"/>}{e.type==='lesson'&&<><Field name="teaching_tip" max={2000}/><Form.Item name="presentation_type" label={copyText('next.maintenance.type')}><Select options={['learning','visit','theory','experiment'].map(value=>({value,label:copyText('next.type.'+value)}))}/></Form.Item><Form.Item name="content_state" label={copyText('next.maintenance.state')}><Select options={['preparing','ready'].map(value=>({value,label:copyText('next.state.'+value)}))}/></Form.Item><Form.Item name="moments_note" label={copyText('next.maintenance.moments')}><Input.TextArea rows={3} maxLength={10000}/></Form.Item><Form.Item name="article_title" label={copyText('next.maintenance.articleTitle')}><Input maxLength={120}/></Form.Item><Form.Item name="article_url" label={copyText('next.maintenance.articleUrl')}><Input maxLength={2000}/></Form.Item><Form.Item name="chapter_id" label={c('field.chapter_id')}><Select allowClear options={[{value:null,label:c('unassigned')},...data.chapters.map(row=>({value:row.id,label:row.title}))]}/></Form.Item></>}{['resource','replay'].includes(e.type)&&<Form.Item name="lesson_id" label={c('field.lesson_id')}><Select allowClear options={options}/></Form.Item>}{e.type==='resource'&&<Form.Item name="resource_type" label={c('upload.type')}><Select options={['courseware','lesson_plan','guide_card','template','video','other'].map(value=>({value,label:c('type.'+value)}))}/></Form.Item>}</>}
  <WriteNotice state={state} refresh={refresh}/><Button type="primary" htmlType="submit" loading={state.busy} disabled={state.saved}>{c('save')}</Button>
 </Form>;
}
