import {useCallback,useRef,useState} from 'react';
import {Alert,Button,Form,Input,Select,Space} from 'antd';
import {maintenanceAPI as api} from './maintenanceApi';
import {articleBlocks,ProtectedPhoto} from '../../student/space/ArticleContent';
import {copyText as c} from '../../content/copy';
import UploadQueue from './UploadQueue';
import {requestError} from '../../utils/requestError';
export default function InlineTeachingEditor({field,lesson,courseId,resources,policy,refresh,dirty,onClose,disabled}){
 const [form]=Form.useForm(),[blocks,setBlocks]=useState(()=>articleBlocks(lesson.article_blocks)),[state,setState]=useState({busy:false,saved:false,error:'',id:lesson.id}),known=useRef(lesson.content_revision),busy=useRef(false),changed=useRef(false);
 const download=useCallback(id=>api.download(courseId,id),[courseId]);
 const change=()=>{changed.current=true;dirty(true);setState(s=>({...s,saved:false,error:''}));};
 const update=fn=>{setBlocks(fn);change();};
 const save=async values=>{if(busy.current)return;busy.current=true;setState(s=>({...s,busy:true,error:''}));let result;try{result=await api.save(courseId,'/lessons/'+lesson.id,{...values,...(field==='article'?{article_blocks:blocks}:{}),expected_revision:known.current});known.current=result.content_revision;changed.current=false;dirty(false);setState({busy:true,saved:true,error:'',id:result.id});await refresh();setState({busy:false,saved:true,error:'',id:result.id});}catch(e){setState({busy:false,saved:!!result,error:result?c('next2.save.readFailed'):requestError(e),id:lesson.id});}finally{busy.current=false;}};
 const close=()=>{if(busy.current)return;if(changed.current&&!window.confirm(c('authoring.discard')))return;dirty(false);onClose();};
 const fields=field==='article'?['article_title']:field==='schedule'?['title','location','start_at','end_at','duration','instructor_id','presentation_type','content_state']:[field];
 const imageResources=resources.filter(r=>r.lesson_id===lesson.id&&['jpg','jpeg','png','webp','gif'].includes(r.file_type));
 return <section className="authoring-inline-panel" aria-label={c('authoring.panel')} data-testid="authoring-panel"><h3>{c('authoring.field.'+field)}</h3><p>{c('authoring.help.'+field)}</p><p>{c('authoring.saveMeaning')}</p><Form form={form} layout="vertical" initialValues={lesson} onValuesChange={change} onFinish={save} disabled={state.busy||disabled}>
 {fields.map(name=><Form.Item key={name} name={name} label={c('authoring.field.'+name)} extra={c(['title'].includes(name)?'authoring.required':'authoring.optional')} rules={name==='title'?[{required:true,whitespace:true,max:120}]:[{max:name==='article_title'?120:name==='teaching_tip'?2000:10000}]}>{['title','article_title'].includes(name)?<Input maxLength={120}/>:<Input.TextArea rows={name==='teaching_tip'?3:6} maxLength={name==='teaching_tip'?2000:10000} showCount/>}</Form.Item>)}
 {field==='article'&&<><p>{c('authoring.blocks.help')}</p>{blocks.map((block,index)=><section className="authoring-block" key={block.id} data-testid="article-block"><Space wrap><strong>{index+1} · {c('authoring.block.'+block.type)}</strong><Button disabled={state.busy||index===0} onClick={()=>update(list=>{const next=[...list];[next[index-1],next[index]]=[next[index],next[index-1]];return next;})}>{c('authoring.up')}</Button><Button disabled={state.busy||index===blocks.length-1} onClick={()=>update(list=>{const next=[...list];[next[index+1],next[index]]=[next[index],next[index+1]];return next;})}>{c('authoring.down')}</Button><Button danger disabled={state.busy} onClick={()=>update(list=>list.filter(b=>b.id!==block.id))}>{c('authoring.removeBlock')}</Button></Space>{block.type==='paragraph'?<label>{c('authoring.paragraph')}<Input.TextArea value={block.text} maxLength={10000} rows={4} onChange={e=>update(list=>list.map(b=>b.id===block.id?{...b,text:e.target.value}:b))}/></label>:<><label>{c('authoring.image.select')}<Select value={block.resourceId} style={{width:'100%'}} options={imageResources.map(r=>({value:r.id,label:r.title}))} onChange={value=>update(list=>list.map(b=>b.id===block.id?{...b,resourceId:value}:b))}/></label><label>{c('authoring.image.title')}<Input maxLength={120} value={block.title} onChange={e=>update(list=>list.map(b=>b.id===block.id?{...b,title:e.target.value}:b))}/></label><label>{c('authoring.image.caption')}<Input.TextArea maxLength={1000} value={block.caption} onChange={e=>update(list=>list.map(b=>b.id===block.id?{...b,caption:e.target.value}:b))}/></label>{imageResources.find(r=>r.id===block.resourceId)&&<ProtectedPhoto resource={imageResources.find(r=>r.id===block.resourceId)} download={download} title={block.title} caption={block.caption}/>}</>}</section>)}<Space wrap><Button disabled={state.busy} onClick={()=>update(list=>[...list,{id:crypto.randomUUID(),type:'paragraph',text:''}])}>{c('authoring.addParagraph')}</Button><Button disabled={state.busy||!imageResources.length} onClick={()=>update(list=>[...list,{id:crypto.randomUUID(),type:'image',resourceId:imageResources[0].id,title:'',caption:''}])}>{c('authoring.addImage')}</Button></Space><UploadQueue courseId={courseId} lessons={[lesson]} boundLessonId={lesson.id} policy={policy} kind="resource" imageOnly refresh={refresh} dirty={value=>dirty(value||changed.current)} disabled={state.busy||disabled} onUploaded={r=>update(list=>list.some(b=>b.resourceId===r.id)?list:[...list,{id:crypto.randomUUID(),type:'image',resourceId:r.id,title:r.title,caption:r.description}])}/></>}
 {state.error&&<Alert type={state.saved?'warning':'error'} title={state.error} description={'#'+state.id} action={state.saved?<Button onClick={()=>void refresh().then(()=>setState(s=>({...s,error:''}))).catch(()=>{})}>{c('authoring.retry')}</Button>:null}/>}{state.saved&&!state.error&&<Alert type="success" title={c('authoring.saved')+' #'+state.id}/>}
 <div className="authoring-save"><Space wrap><Button type="primary" htmlType="submit" loading={state.busy} disabled={disabled||state.saved}>{c('authoring.save')}</Button><Button disabled={state.busy} onClick={close}>{c('authoring.close')}</Button></Space></div></Form></section>;
}
