/* eslint-disable react-hooks/set-state-in-effect */
import {useCallback,useEffect,useRef,useState} from 'react';
import {Alert,Button,Form,Modal,Select,Space,Radio,Checkbox,Input} from 'antd';
import {learningManageAPI,courseAPI} from '../../api';
import {maintenanceAPI as api} from './maintenanceApi';
import {copyText} from '../../content/copy';
import {maintenanceText as c} from './maintenanceCopy';
import {requestError} from '../../utils/requestError';
import LessonContentEditor from '../mentor/LessonContentEditor';
import {LessonTemplateView} from '../../student/space/LessonTemplate';
import ExerciseView from '../../student/space/ExerciseView';
import LessonLearningView from '../../student/space/LessonLearningView';
import {StudySection} from '../../student/visual/StudyUI';
import Sentence from '../../content/Sentence';
import InlineTeachingEditor from './InlineTeachingEditor';
import UploadQueue from './UploadQueue';
import {reportFields} from '../../student/reportFields';
import TemplateReplays from '../../student/TemplateReplays';
import {CoursePreviewTheme} from '../../student/space/CoursePresentation';
export function ResourcePreview({courseId,resource,onClose}){
 const[state,setState]=useState({url:'',error:''});
 useEffect(()=>{let live=true,url;api.download(courseId,resource.id).then(blob=>{if(!live)return;url=URL.createObjectURL(blob);setState({url,error:''});}).catch(e=>{if(live)setState({url:'',error:requestError(e)});});return()=>{live=false;if(url)URL.revokeObjectURL(url);};},[courseId,resource.id]);
 const image=['png','jpg','jpeg','webp','gif'].includes(resource.file_type?.toLowerCase());
 return <Modal open title={resource.title} footer={state.url?<Button href={state.url} download={resource.file_name||resource.title}>{c('upload.download')}</Button>:null} onCancel={onClose} width={820} destroyOnHidden>{state.error?<Alert type="error" title={state.error}/>:state.url?image?<img onError={()=>setState(current=>({...current,error:copyText('next2.preview.fallback')}))} src={state.url} alt={resource.title} style={{maxWidth:'100%',maxHeight:'65dvh'}}/>:<><p>{copyText('next2.preview.fallback')}</p>{resource.file_type?.toLowerCase()==='pdf'&&<iframe src={state.url} sandbox="" title={resource.title} style={{width:'100%',height:'60dvh',border:0}}/>}</>:<p>{copyText('next2.preview.reading')}</p>}</Modal>;
}

export default function TeachingPreview({data,courseId,edit,intro,experiments,disabled,refresh,policy,dirty,onBusyChange,resetVersion}){
 const [selected,setSelected]=useState(data.lessons[0]?.id),[cards,setCards]=useState([]),[error,setError]=useState(''),[preview,setPreview]=useState(false),[stage,setStage]=useState(0),[cardIndex,setCardIndex]=useState(0),[panel,setPanel]=useState(null),[cardEditor,setCardEditor]=useState(false),[cardBusy,setCardBusy]=useState(false),[file,setFile]=useState(null),[replay,setReplay]=useState({url:'',id:null}),[form]=Form.useForm();
 const processing=useRef(new Set()),unsaved=useRef(new Set()),lesson=data.lessons.find(l=>l.id===selected),course=data.course;
 const mark=useCallback((key,value)=>{if(value)unsaved.current.add(key);else unsaved.current.delete(key);dirty?.('visual',unsaved.current.size>0);},[dirty]);
 const markBusy=useCallback((key,value)=>{if(value)processing.current.add(key);else processing.current.delete(key);onBusyChange?.(processing.current.size>0);},[onBusyChange]);
 useEffect(()=>{unsaved.current.clear();dirty?.('visual',false);setPanel(null);},[resetVersion,dirty]);
 // Scope loss can unmount a queue mid-request; never leave its parent blocked.
 useEffect(()=>()=>{dirty?.('visual',false);onBusyChange?.(false);},[dirty,onBusyChange]);
 const confirm=()=>!processing.current.size&&(!unsaved.current.size||window.confirm(copyText('authoring.discard')));
 const discard=()=>{unsaved.current.clear();dirty?.('visual',false);setPanel(null);};
 const transition=action=>{if(!confirm())return;discard();action();};
 const download=useCallback(id=>api.download(courseId,id),[courseId]);
 const readCards=useCallback(async()=>{try{const r=await learningManageAPI.cards(selected);setCards(r.cards||[]);setError('');}catch(e){setError(requestError(e));}},[selected]);
 useEffect(()=>{let live=true;setCards([]);setCardIndex(0);if(selected)learningManageAPI.cards(selected).then(r=>{if(live)setCards(r.cards||[]);}).catch(e=>{if(live)setError(requestError(e));});return()=>{live=false;};},[selected,cardEditor]);
 if(!lesson)return <Alert title={copyText('next2.maintenance.empty')}/>;
 const resources=data.resources.filter(r=>!r.lesson_id||r.lesson_id===lesson.id),replays=data.replays.filter(r=>!r.lesson_id||r.lesson_id===lesson.id),published=cards.filter(c=>c.status==='published'),activeCard=published[Math.min(cardIndex,published.length-1)],lessonData={course,lesson,resources,replays,cards:published};
 const open=key=>{if(panel===key)return;transition(()=>{if(key==='schedule'){edit('lesson',lesson);return;}if(key==='cards'){setCardEditor(true);return;}if(key==='tasks'){const task=data.tasks.find(t=>t.lesson_id===lesson.id);if(task)edit('task',task);return;}setPanel(key);});};
 const fieldRegion=(key,children)=>preview?children:<div className="authoring-region" data-authoring-region={key}><button type="button" disabled={disabled||(key==='tasks'&&!data.tasks.some(t=>t.lesson_id===lesson.id))} onClick={()=>open(key)}>{copyText('authoring.edit')} · {copyText('authoring.field.'+key)}</button>{panel===key&&!['resources','replays','schedule','cards','tasks'].includes(key)&&<InlineTeachingEditor key={selected+':'+key} field={key} lesson={lesson} courseId={courseId} resources={data.resources} policy={policy} refresh={refresh} dirty={value=>mark('panel',value)} onBusyChange={value=>markBusy('panel',value)} onClose={()=>setPanel(null)} disabled={disabled}/>} {panel===key&&['resources','replays'].includes(key)&&<div className="authoring-inline-panel"><UploadQueue key={selected+':'+key} courseId={courseId} lessons={[lesson]} boundLessonId={lesson.id} policy={policy} kind={key==='resources'?'resource':'replay'} disabled={disabled||(key==='replays'&&data.authorRole!=='admin')} refresh={refresh} dirty={v=>mark('queue',v)} onBusyChange={v=>markBusy('queue',v)}/>{key==='replays'&&data.authorRole!=='admin'&&<Alert title={copyText('next2.maintenance.replayAdmin')}/>}<Button onClick={()=>{transition(()=>{});}}>{copyText('authoring.close')}</Button></div>}{children}</div>;
 const region=(key,children)=>key==='schedule'?(preview?children:<span>{children}<Button disabled={disabled||(key==='tasks'&&!data.tasks.some(t=>t.lesson_id===lesson.id))} onClick={()=>open(key)}>{copyText('authoring.field.schedule')}</Button></span>):fieldRegion(key,children);
 const experiment=(current,cardId)=><>{region('experiment_guidance',<Sentence>{lesson.experiment_guidance}</Sentence>)}{data.experiments.filter(e=>e.enabled&&(!e.lessonId||e.lessonId===lesson.id)&&(e.stage==null||e.stage===current)&&(!e.cardId||e.cardId===cardId)).map(e=><p key={e.id}>{e.label}</p>)}{!preview&&<Button disabled={disabled} onClick={experiments}>{copyText('next2.preview.links')}</Button>}</>;
 const renderExercise=(e,index)=>{const options=(e.options||[]).map((o,i)=>typeof o==='object'?{label:o.label??o.text,value:o.value??o.key??String(i)}:{label:o,value:o});const input=e.question_type==='single_choice'?<Radio.Group options={options}/>:e.question_type==='multiple_choice'?<Checkbox.Group options={options}/>:e.question_type==='true_false'?<Radio.Group options={[{label:copyText('system.learning.005'),value:true},{label:copyText('system.learning.006'),value:false}]}/>:<Input.TextArea rows={2}/>;return <div key={e.id}><ExerciseView exercise={e} index={index} input={input} readonly/>{!preview&&<><Button disabled={disabled} onClick={()=>open('cards')}>{copyText('authoring.field.exercises')}</Button><p>{copyText('authoring.maintainerAnswer')} {JSON.stringify(e.answer)} · {e.explanation}</p></>}</div>;};
 const works=<StudySection id="lesson-works" number="W" title={copyText('site.422217ee612b1ccc')} description={copyText('site.3de0e858a9327c2c')}>{data.tasks.filter(t=>t.lesson_id===lesson.id).map(t=><article key={t.id} className="study-task"><h4>{t.title}</h4><Sentence>{t.description}</Sentence>{!preview&&<Button onClick={()=>transition(()=>edit('task',t))} disabled={disabled}>{copyText('authoring.field.tasks')}</Button>}</article>)}{!data.tasks.some(t=>t.lesson_id===lesson.id)&&<p>{copyText('next.template.empty')}</p>}</StudySection>;
 const playReplay=async id=>{try{const r=await courseAPI.streamUrl(id);setReplay({url:r.url,id});}catch(e){setError(requestError(e));}};
 return <CoursePreviewTheme course={course}><div className="teaching-preview student-pixel" data-testid="teaching-preview"><Alert type="info" title={copyText('authoring.previewSafety')}/><div className="authoring-toolbar"><label htmlFor="preview-lesson">{copyText('next2.maintenance.select')}</label><Select id="preview-lesson" value={selected} options={data.lessons.map(l=>({value:l.id,label:l.title,disabled:l.status==='cancelled'}))} onChange={value=>{if(value!==selected)transition(()=>{setStage(0);setSelected(value);});}}/><Button aria-pressed={preview} onClick={()=>transition(()=>setPreview(v=>!v))}>{copyText(preview?'authoring.mode.edit':'authoring.mode.preview')}</Button><Button onClick={intro}>{copyText('next2.preview.course')}</Button></div>{error&&<Alert type="error" title={error}/>}
 {lesson.presentation_type==='visit'||lesson.content_state==='preparing'?<LessonTemplateView data={lessonData} region={region} download={download} maintenance replays={<TemplateReplays rows={replays}/>} experiments={experiment(0)} renderResource={r=><Space><Button onClick={()=>setFile(r)}>{copyText('next2.maintenance.previewFile')}</Button>{!preview&&<Button disabled={disabled} onClick={()=>transition(()=>edit('resource',r))}>{copyText('authoring.resource.edit')}</Button>}</Space>}/>:<LessonLearningView data={lessonData} lesson={lesson} cards={published} progress={{}} report={null} activeStage={stage} courseId={courseId} lessonId={lesson.id} reportFields={reportFields()} stageDone={[]} currentStep={0} stageReasons={[]} navigate={()=>{}} setActiveStage={value=>{if(value!==stage)transition(()=>setStage(value));}} activeCard={activeCard} cardIndex={Math.min(cardIndex,Math.max(0,published.length-1))} setCardIndex={value=>{if(value!==cardIndex)transition(()=>setCardIndex(value));}} submitting={false} cardExercisesDone={false} form={form} reportTone="info" draftState={copyText('authoring.previewSafety')} reflectionOpen={[]} setReflectionOpen={()=>{}} renderExercise={renderExercise} region={region} experiment={experiment} works={works} maintenance replayUrl={replay.url} activeReplayId={replay.id} playReplay={playReplay} setReplayError={()=>{}} downloadResource={r=>setFile(r)}/>}
 <Modal open={cardEditor} closable={!cardBusy} maskClosable={!cardBusy} title={copyText('next2.preview.cardTitle')} onCancel={()=>{if(cardBusy||!confirm())return;setCardEditor(false);mark('cards',false);void readCards();void refresh().catch(()=>{});}} footer={null} width={1000} destroyOnHidden>{cardEditor&&<LessonContentEditor key={selected} embeddedCourseId={courseId} embeddedLessonId={selected} onBusyChange={value=>{setCardBusy(value);markBusy('cards',value);}} onDirtyChange={v=>mark('cards',v)}/>}</Modal>{file&&<ResourcePreview courseId={courseId} resource={file} onClose={()=>setFile(null)}/>}</div></CoursePreviewTheme>;
}
