/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from 'react';
import {Alert,Button,Descriptions,Modal,Select,Tag} from 'antd';
import {learningManageAPI} from '../../api';
import {maintenanceAPI as api} from './maintenanceApi';
import {StudyHeader,StudySection} from '../../student/visual/StudyUI';
import {VisitSections,LessonDescription} from '../../student/space/TeachingSections';
import Sentence from '../../content/Sentence';
import {copyText} from '../../content/copy';
import CourseCover from '../../student/space/CourseCover';
import LessonContentEditor from '../mentor/LessonContentEditor';
import {maintenanceText as c} from './maintenanceCopy';
import {requestError} from '../../utils/requestError';
function Region({title,children,onClick,disabled}){return <button type="button" className="visual-edit-region" disabled={disabled} onClick={onClick} aria-label={copyText('next2.preview.edit')+' '+title}><strong>{title} · {copyText('next2.preview.edit')}</strong>{children||<span>{copyText('next2.maintenance.empty')}</span>}</button>;}
export function ResourcePreview({courseId,resource,onClose}){
 const[state,setState]=useState({url:'',error:''});
 useEffect(()=>{let live=true,url;api.download(courseId,resource.id).then(blob=>{if(!live)return;url=URL.createObjectURL(blob);setState({url,error:''});}).catch(e=>{if(live)setState({url:'',error:requestError(e)});});return()=>{live=false;if(url)URL.revokeObjectURL(url);};},[courseId,resource.id]);
 const image=['png','jpg','jpeg','webp','gif'].includes(resource.file_type?.toLowerCase());
 return <Modal open title={resource.title} footer={state.url?<Button href={state.url} download={resource.file_name||resource.title}>{c('upload.download')}</Button>:null} onCancel={onClose} width={820} destroyOnHidden>{state.error?<Alert type="error" title={state.error}/>:state.url?image?<img onError={()=>setState(current=>({...current,error:copyText('next2.preview.fallback')}))} src={state.url} alt={resource.title} style={{maxWidth:'100%',maxHeight:'65dvh'}}/>:<><p>{copyText('next2.preview.fallback')}</p><iframe src={state.url} sandbox="" title={resource.title} style={{width:'100%',height:'60dvh',border:0}}/></>:<p>{copyText('next2.preview.reading')}</p>}</Modal>;
}
export default function TeachingPreview({data,courseId,edit,intro,resources,experiments,disabled,refresh}){
 const[selected,setSelected]=useState(data.lessons[0]?.id),[cards,setCards]=useState([]),[cardError,setCardError]=useState(''),[cardEditor,setCardEditor]=useState(false),[cardBusy,setCardBusy]=useState(false),[file,setFile]=useState(null);
 const lesson=data.lessons.find(l=>l.id===selected),course=data.course;
 useEffect(()=>{let live=true;setCards([]);setCardError('');if(lesson)learningManageAPI.cards(lesson.id).then(r=>{if(live)setCards(r.cards||[]);}).catch(e=>{if(live)setCardError(requestError(e));});return()=>{live=false;};},[lesson,cardEditor]);
 const applicable=data.resources.filter(r=>!r.lesson_id||r.lesson_id===lesson?.id),photos=applicable.filter(r=>r.lesson_id===lesson?.id&&['png','jpg','jpeg','webp'].includes(r.file_type));
 return <div className="teaching-preview" data-testid="teaching-preview"><Alert type="info" title={copyText('next2.maintenance.guide')}/><StudyHeader title={course.title} description={course.theme}/><button className="visual-edit-region preview-cover" onClick={intro} disabled={disabled} aria-label={copyText('next2.preview.cover')}><CourseCover course={course}/><span>{copyText('next2.preview.cover')}</span></button>
 <Region title={copyText('next2.preview.course')} onClick={intro} disabled={disabled}>{['description','driving_question','story_line','materials_needed'].map(k=>course[k]&&<p key={k}>{course[k]}</p>)}</Region>
 <div className="preview-tools"><label htmlFor="preview-lesson">{copyText('next2.maintenance.select')}</label><Select id="preview-lesson" value={lesson?.id} onChange={setSelected} options={data.lessons.map(l=>({value:l.id,label:l.title,disabled:l.status==='cancelled'}))}/><Button onClick={resources}>{copyText('next2.maintenance.position')} / {copyText('next2.preview.materials')}</Button></div>
 {lesson&&<div className="study-workspace preview-lesson"><StudyHeader title={lesson.title} description={copyText('next.type.'+lesson.presentation_type)}/>
 <Region title={copyText('next2.preview.lesson')} onClick={()=>edit('lesson',lesson)} disabled={disabled}><p>{lesson.description||copyText('next2.maintenance.empty')}</p><span>{lesson.start_at||copyText('next2.empty.date')} · {lesson.end_at||copyText('next2.empty.end')} · {lesson.location||copyText('next2.empty.location')} · {data.teachers.find(t=>t.id===lesson.instructor_id)?.real_name||copyText('next2.empty.instructor')} · {lesson.duration==null?copyText('next2.empty.duration'):lesson.duration+' 分钟'}</span></Region>
 {lesson.presentation_type==='visit'?<><Button onClick={()=>edit('lesson',lesson)} disabled={disabled}>{copyText('next2.preview.moments')}</Button><VisitSections lesson={lesson} photos={photos} renderPhoto={r=><figure key={r.id} className="preview-photo"><Region title={r.title} onClick={()=>edit('resource',r)} disabled={disabled}><span>{r.description||copyText('next2.maintenance.empty')}</span></Region><Button onClick={()=>setFile(r)}>{copyText('next2.maintenance.previewFile')}</Button></figure>}/></>:<>
 <StudySection title={copyText('next2.maintenance.review')}><Region title={copyText('next2.preview.review')} onClick={()=>edit('lesson',lesson)} disabled={disabled}>{lesson.description&&<p>{lesson.description}</p>}</Region>{cardError&&<Alert type="error" title={cardError}/>}<Button onClick={()=>setCardEditor(true)} disabled={disabled}>{copyText('next2.preview.cards')}</Button>{cards.filter(c=>c.status==='published').map(c=><div key={c.id} className="study-card-content"><h4>{c.title}</h4><Sentence>{c.content}</Sentence>{(c.exercises||[]).map(e=><div key={e.id} className="study-exercise"><strong>{e.prompt}</strong>{e.options?.map((o,i)=><p key={i}>{typeof o==='string'?o:o?.label||''}</p>)}</div>)}</div>)}</StudySection>
 <StudySection title={copyText('next.template.tasks')}>{data.tasks.filter(t=>t.lesson_id===lesson.id).map(t=><Region key={t.id} title={t.title} onClick={()=>edit('task',t)} disabled={disabled}><p>{t.description}</p></Region>)}{!data.tasks.some(t=>t.lesson_id===lesson.id)&&<p>{copyText('next.template.empty')}</p>}<Button onClick={()=>edit('lesson',lesson)} disabled={disabled}>{copyText('next2.preview.guide')}</Button></StudySection>
 <StudySection title={copyText('next.template.experiment')}><Region title={copyText('next2.preview.experiment')} onClick={()=>edit('lesson',lesson)} disabled={disabled}>{lesson.teaching_tip&&<p>{lesson.teaching_tip}</p>}</Region>{data.experiments.filter(e=>e.enabled&&(!e.lessonId||e.lessonId===lesson.id)).map(e=><Tag key={e.id}>{e.label}</Tag>)}<Button onClick={experiments}>{copyText('next2.preview.links')}</Button></StudySection>
 </>}
 <LessonDescription lesson={lesson}/><StudySection title={copyText('system.map.014')}>{applicable.map(r=><div key={r.id}><Region title={r.title} onClick={()=>edit('resource',r)} disabled={disabled}><span>{r.lesson_id?lesson.title:copyText('next2.public')} · {r.description}</span></Region>{['png','jpg','jpeg','webp','gif','pdf'].includes(r.file_type?.toLowerCase())&&<Button onClick={()=>setFile(r)}>{copyText('next2.maintenance.previewFile')}</Button>}</div>)}{!applicable.length&&<p>{copyText('next.template.noResources')}</p>}<Button onClick={resources}>{copyText('next2.preview.upload')}</Button></StudySection>
 <Descriptions size="small" column={1} items={[{key:'state',label:copyText('next2.preview.state'),children:copyText('next.state.'+lesson.content_state)}]}/></div>}
 <Modal open={cardEditor} closable={!cardBusy} maskClosable={!cardBusy} title={copyText('next2.preview.cardTitle')} onCancel={()=>{if(cardBusy)return;setCardEditor(false);void refresh().catch(()=>{});}} footer={null} width={1000} destroyOnHidden>{cardEditor&&lesson&&<LessonContentEditor key={lesson.id} embeddedCourseId={courseId} embeddedLessonId={lesson.id} onBusyChange={setCardBusy}/>}</Modal>{file&&<ResourcePreview courseId={courseId} resource={file} onClose={()=>setFile(null)}/>}
 </div>;
}
